### PR TITLE
Fix #7436: make display forms of imported names DeadCode roots

### LINKED ISSUE #7436: Code only reachable from display forms not serialised in Agda 2.7.0
This is on  Agda 2.7.0,  MAlonzo, on Debian Linux 12                            
installed by                                                                    
 $ cabal install -foptimise-heavily -j1,                                        
                                                                                
lib-2.1                                                                         
                                                                                
All the application modules are type-checked by type-checking CheckAll.agda.    
CheckAll.agda  consists of many lines of kind                                   
  open import Foo                                                               
And there is only one module in this list that applies the `main' function:                  
  Pol.Univariate.KTest.                                                         
It is the example that uses other modules and needs to be compiled to executable.                                                                     
                                                                                
Type checking:                                                                  
 $ agda $agdaLibOpt $agdaFlags  CheckAll.agda  +RTS -M12G                       
 where                                                                          
 $agdaFlags = "--auto-inline --guardedness"                                     
                                                                                
Compilation to executable example:                                              
 $ agda -c $agdaLibOpt $agdaFlags Pol/Univariate/KTest.agda +RTS -M12G          
                                                                                
It reports                                                                      
"                                                                               
An internal error has occurred. Please report this as a bug.                    
Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/         
TypeChecking/Monad/Signature.hs:869:32 in                                       
Agda-2.7.0-5b1c26af24f71478be7921bfd690317a6888da853b10d78f399aa31cab72a91e:    
Agda.TypeChecking.Monad.Signature                                               
"       

Call the above approach (I).                                                            
a) In a strange way, this error does not appear for other executable examples set instead of  Pol/Univariate/KTest.agda.                                    
b) I also recall (not very surely) that  Agda 2.6.4.3  is free of this effect.   
c) There was some explanation about the effect, may be about year ago, which I did not understand.                                                         
                        
Anyway, I apply the following approach instead.                                 
                                                                                
Approach (II)                                                                   
-------------                                                                   
(1) Start with only *.agda files of application.                                
   Comment out in CheckAll.agda all the lines for the modules that have `main' . 
   This is only to remember the list of examples to be compiled separately.           
(2) Type-check  CheckAll.agda.                                                  
(3) Choose the needed example  Foo.agda  among the commented out lines and      
    command                                                                     
    $ agda -c ... Foo.agda                                                      
(4) Process other examples in this way by repeating (3)  (without type-checking CheckAll.agda).                                      
                                                                                
This compiles the examples correctly.                                           
                                                                                
I write this because users will be frightened by this "internal error"  message and will doubt of how to organize usage of their applications  when such have examples to be compiled to executables.                          
I wonder of whether it is possible to fix Agda in such a way that the above effect would not appear at all.

### PR DESCRIPTION
**Pull request by AndrasKovacs**
PR #7248 erroneously removed them from the root set.

### CODE REVIEW

**Comment by andreasabel** [comment]
Thanks @AndrasKovacs !
I would like a small test for this so that we do not regress.

**Comment by AndrasKovacs** [comment]
@andreasabel Actually, I don't know how to minimally reproduce the problem right now... Display forms shouldn't matter for compilation at all. If definitions that are only reachable through display forms get erased, then nothing should happen in the compiler. The only way to crash in this case should be to do an interactive printing. But apparently the compiler crashes in Sergei's massive code example.

**Comment by andreasabel** [comment]
Isn't it already deserialisation that crashes?

**Comment by AndrasKovacs** [comment]
I don't know. I wasn't able to get any small crashing example today, using nf printing or compilation or checking. Deserialization doesn't crash on dangling qualified names, usually reduction does. Maybe the display form pruning from #1928 prevents me from easily manufacturing an error.

**Comment by andreasabel** [comment]
If it can't be synthesized, it needs to be analysed...
That means shrinking the OP.
I have never spent more than two hours on shrinking a `.agda` reproducer.
I have twice already shrank the whole Agda codebase to isolate Haskell bugs, that took 2 days each time.

**Comment by andreasabel** [comment]
Ok, this time I spend around 3.5 hours...

**Comment by andreasabel** [comment]
I added the test case.

**Comment by andreasabel** [comment]
Cherry-picked onto 
- #7469.

**Pull request merged**
