### PR TITLE
Add Markdown support for literate Agda.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by vlopezj** [comment]
@ak3n This looks pretty good. Can we have some test cases for the new feature? For example, two or three `.lagda.md` files where the code type-checks successfully, and another one where the Agda code fails to type-check.

They can follow the same pattern the `.lagda.rst` tests:

1. Extend the definition of `dropAgdaExtension'` in `test/Utils.hs` to support `.lagda.md` files.
2. Add your successful `.lagda.md` files to the `test/LatexAndHtml/succeed/` directory. 
2. Add your failing `.lagda.md` files to `test/Fail/`.
4. Run `make test`.  Whenever it finds a _new_ test case, it will prompt you to check the result. If you accept it as correct, it will be stored as an `.html` file together with your `.lagda.md` file. The `.html` file has the syntax highlighting information for the Agda code, so the CI can check that the file is parsed correctly.
5. Add all the new files (`.lagda.md` and `.html`) to the pull request.
6. Done :)

**Comment by ghost** [comment]
Thanks for the detailed plan!

I don't know why it failed on this test. It runs fine on my local machine.

**Comment by asr** [comment]
> I don't know why it failed on this test. It runs fine on my local machine

Neither do I. Your branch is behind the stable-2.5 branch by 39 commits. After pulling those commits, I couldn't reproduce the issue using GHC 7.10.3. I'll restart the Travis job.

**Comment by asr** [comment]
Travis tests are OK now.

@vlopezj if the PR is ready, merge it please.

**Comment by vlopezj** [comment]
@ak3n Thanks! Merged in a9c3fb3 .

**Comment by andreasabel** [comment]
If I live to see the next issue number that is a sequence of primes, Agda will rule the world! :1st_place_medal:

**Comment by nad** [comment]
Please document this change in the release notes/documentation.

**Comment by vlopezj** [comment]
@nad @ak3n  Done: b8df80ae; I added some information in the release notes.

Having some detailed documentation with examples on how the different literate modes work (`.lagda.tex`, `.lagda.rst`, `.lagda.md`) would be nice.

**Comment by ice1000** [comment]
Hi there, is it possible to compile the agda code blocks to html only and leave other parts of the markdown document unchanged?

When I'm compiling my lagda.md files to html, the ordinary text parts are made "Comments", preventing the markdown renderer to render it.

**Comment by vlopezj** [comment]
@ice1000 As far as I know, Agda does not currently support this. I made your comment into an issue (#3137).

**Comment by ice1000** [comment]
@vlopezj thx

**Pull request closed without merging**
