### PR TITLE
[ fix #4265 ] Handle generalized function types in `isType_`

### LINKED ISSUE #4265: Unsolved constraints when --no-syntactic-equality is used
Agda does not accept the following code:
```agda
{-# OPTIONS --no-syntactic-equality #-}

open import Agda.Primitive

variable
  a : Level

postulate
  A : Set a
```
Unsolved constraints:
```
Failed to solve the following constraints:
  univSort Setω = univSort Setω
```

### PR DESCRIPTION
**Pull request by jespercockx**
Testing on Travis

### CODE REVIEW

**Comment by nad** [comment]
I was [informed](https://github.com/agda/agda/issues/4457#issuecomment-589698021) that you can run the Travis tests without opening a pull request if the name of your branch starts with `issue`:

https://github.com/agda/agda/blob/9f891f656064197a9766f11ec4e05334c6a0c995/.travis.yml#L25-L26

**Comment by andreasabel** [comment]
> I was [informed](https://github.com/agda/agda/issues/4457#issuecomment-589698021) that you can run the Travis tests without opening a pull request if the name of your branch starts with `issue`:

Indeed, my routine workflow now includes a
```
git push origin master:issue<number>
```
after done recording commits.

**Comment by jespercockx** [comment]
> > I was [informed](https://github.com/agda/agda/issues/4457#issuecomment-589698021) that you can run the Travis tests without opening a pull request if the name of your branch starts with `issue`:
> 
> Indeed, my routine workflow now includes a
> 
> ```
> git push origin master:issue<number>
> ```
> 
> after done recording commits.

How does this work? I have created https://github.com/jespercockx/agda/tree/issue3422 but I don't see anything running on Travis.

**Comment by UlfNorell** [comment]
You need to push to the main repo (Or set up travis for your fork)

**Comment by jespercockx** [comment]
Oh, well but then I might as well run the tests locally and just push straight to master. I don't think we should have a branch on the main repository for every issue.

**Comment by UlfNorell** [comment]
You delete the branch when you're done of course. Why would having the branch on the main repo rather than on your fork be a problem?

**Comment by nad** [comment]
I get notifications for all pull requests. Sometimes there is something interesting to look at, but often not. I'd prefer if we could avoid the non-interesting pull requests.

**Comment by UlfNorell** [comment]
Pull requests are orthogonal to where the branch is. You get a travis job for `issueXXX` branches without creating a PR, and you can create PRs from branches on other forks.

**Pull request merged**
