### PR TITLE
Add DoNotation to example test files

### PR DESCRIPTION
**Pull request by ahmadsalim**
I am having trouble getting it to work locally on the latest `master`, so I thought it might be a good idea to suggest to add to the test suite.

### CODE REVIEW

**Comment by ahmadsalim** [comment]
I found out that I had some error in the compilation process that made me use an older version.
I will leave it up to you whether you still want to include it in the tests or close the PR 😄

**Comment by asr** [comment]
Thank you for the PR.

I thought that the  `examples` directory meant *old examples*. Anyway, if a new example was added (i.e. `DoNotation.agda`) it should be included in the tests.

@ahmadsalim, please make the PR using the `stable-2.5` branch.

**Comment by ahmadsalim** [comment]
@asr Sure, will do.

**Comment by ahmadsalim** [comment]
OK, I will close and redo. It seems that the github change branch functionality did not work as expected.

**Pull request closed without merging**
