### PR TITLE
Remodeled sort system

### PR DESCRIPTION
**Pull request by jespercockx**
This is my attempt at turning Agda's sort system into a proper pure type system (pts). The goals are the following:
- remove the assumption that any sort is of the form `Set l`, thus opening up design space for new sorts such as `Prop`, `SizeUniv`, and others
- remove a bunch of horrible hacks which were conflating level and sort metas
- deal with `Setω` in a hopefully (more) consistent way
- prepare to experiment with cumulativity

The main changes are the following:
- There is a new `Sort` constructor `UnivSort` which takes a sort and computes to the next bigger sort. There is also a new constraint `HasBiggerSort` to ensure that the bigger sort will be computed eventually (HasBiggerSort Setω is unsatisfiable).
- The `DLub` sort has been renamed to `PiSort` and is no longer assumed to be commutative. I also experimented with a `HasPTSRule` constraint to ensure that a sort will be eventually computed (similar to `HasBiggerSort`) but this resulted in lots of noise in the printed constraints so I disabled it for now. This means I currently assume the `PiSort` of two sorts to always exist, which fails to hold for the (currently disabled) `SizeUniv` but should otherwise be fine.
- There is a new `Sort` constructor `MetaS` for a meta sort. Meta sorts use the same meta store as term metas, but the only valid instantiations for a sort meta are `Sort s` or `MetaV x es`. Meta sorts are distinguised from regular sorts by the `IsSort` judgement on the metavariable (instead of `HasType`).
- The constraint solver for equalities and inequalities between sorts has been rewritten to account for the newly added `UnivSort` and `MetaS`.

See the code for more details, in particular `Agda.TypeChecking.Sort` and `Agda.TypeChecking.Conversion`.

There are some small changes required to the test suite (and one very small one in the standard library), but overall Agda manages to figure out the sorts the same as before (of course, more testing is needed). 

Any comments on this PR are very welcome! If no major issues pop up, I hope I can push this in one of the coming days so I can properly implement Prop for Agda.

### CODE REVIEW

**Comment by nad** [comment]
What, exactly, do you mean by "Prop"?

**Comment by jespercockx** [comment]
See [https://lists.chalmers.se/pipermail/agda-dev/2018-February/000323.html](https://lists.chalmers.se/pipermail/agda-dev/2018-February/000323.html) for my initial attempt at implementing a Prop universe for Agda. The prototype implementation doesn't really work very well because of Agda's assumption that any sort must be of the form `Set l` for some level `l`, which is addressed in this PR.

Apart from `Prop`, there are plenty of other reasons to generalize Agda's sort system. This would allow us to re-enable `SizeUniv`, which would help in fixing #1428 and #2820. It would allow me to implement `--omega-in-omega` which I got stuck on last Agda meeting. It could also help for cubical Agda to give the interval its own sort instead of putting it in `Set`. And (I hope) it also helps for future extensions to the sort system, such as having a universe of non-fibrant types à la two-level type theory.

**Comment by L-TChen** [comment]
> prepare to experiment with cumulativity

Is there any update about this?  I think this is also related to #2043.

**Comment by jespercockx** [comment]
Work on adding cumulativity is currently blocked on https://github.com/agda/agda/issues/3099

**Pull request closed without merging**
