### PR TITLE
Remove with inliner

### LINKED ISSUE #3604: With-abstraction fools the productivity checker
Following on from [Thorsten's post to the mailing list](https://lists.chalmers.se/pipermail/agda/2019/010902.html), in the following code, Agda mistakenly accepts `f` as productive. We can use this to make the type checker loop on `test`.

```agda
data Maybe (A : Set) : Set where
  just : A → Maybe A
  nothing : Maybe A

data Is-nothing {A} : Maybe A → Set where
  nothing : Is-nothing nothing

record ℕ∞ : Set where
  coinductive
  field
    prd∞ : Maybe ℕ∞

open ℕ∞

f :  ℕ∞ → ℕ∞
prd∞ (f m) with prd∞ m
prd∞ (f m) | just pm with f pm
prd∞ (f m) | just pm | x = prd∞ x
prd∞ (f m) | nothing = nothing

inf∞ : ℕ∞
prd∞ inf∞ = just inf∞

test : Is-nothing (prd∞ (f inf∞))
test = nothing
```

If this
```
prd∞ (f m) | just pm with f pm
prd∞ (f m) | just pm | x = prd∞ x
```
is replaced by this
```
prd∞ (f m) | just pm = prd∞ (f pm)
```
the productivity checker will notice that this definition is not productive. But it believes that the version of `f` with the `with` is productive, and upon trying to run it fails to produce a result.

Agda version 2.5.4.2

### PR DESCRIPTION
**Pull request by jespercockx**
The aim of this PR is to assess the impact of removing the with-inlining feature of the termination checker (see issues #59 and #3604). If you're reading this, please take a look at the changed test cases and let me know whether you find this acceptable to fix #3604 in this way or if we first need to wait for an alternative to the with-inliner (e.g. as proposed by @andreasabel in #1381).

### CODE REVIEW

**Review by UlfNorell — APPROVED** [review]

**Comment by andreasabel** [comment]
Alternative: keep with-inliner under a flag that is off by default (to wean off our users).
Add some migration guide to the CHANGELOG.

**Comment by ice1000** [comment]
Is there a flag for adding the inliner back?

**Comment by jespercockx** [comment]
We discussed this but there was no-one willing to maintain the implementation of the with-inliner, so I removed it entirely.

**Comment by ice1000** [comment]
How should those code using the with-inliner go then? Is there an alternative solution?

**Comment by jespercockx** [comment]
Depending on the example, you can:

1. Rewrite the code to not use `with`
2. Keep using with, but change the order of pattern matches to make the structural recursion obvious
3. Use sized types

@UlfNorell already did the required changes for the agda-prelude, see https://github.com/UlfNorell/agda-prelude/commit/d8856de570011d0342e9a718cff47a8a2e9aa87f. If you have a specific example that you don't know how to do without with-inlining, you could post it here and we can try to help.

**Pull request merged**
