### PR TITLE
[ new ] use text for string literals

### PR DESCRIPTION
**Pull request by gallais**
This is the second half of #4491 and should fix it.

### CODE REVIEW

**Review by andreasabel — APPROVED** [review]
Thanks, LGTM (don't have an opinion, really).
Seems that `Text` is more appropriate than `String`, since we do not manipulate the literals.

**Comment by gallais** [comment]
Closed and reopened to trigger another build on travis. I have a hard time
believing that merging master in broke the test suite and I can't seem to be
able to restart builds directly on the website...

**Comment by gallais** [comment]
So it looks like the backend is generating `Data.Text` Text but I picked
`Data.Text.Lazy` Text because we already had an instance to serialise that.
May be the reason why the compiled programs are crashing.

I'll change the literals to `Data.Text` then.

**Comment by rwe** [comment]
This is related to https://github.com/agda/agda/issues/3741. Linking here for reference. Would this PR be sufficient to close that issue, I wonder? (The scope in the issue description was vague: "more places").

**Comment by andreasabel** [comment]
Is this PR stuck on some problem?

**Comment by gallais** [comment]
Yep: me not finding the time to deal with it.

**Pull request merged**
