### PR TITLE
Release 2.7.0.1

### LINKED ISSUE #7199: Agda re-checks a file with an up-to-date interface file
Consider the following workflow:
* You load the module `B.agda`, which imports `A.agda`, in (say) Emacs.
* You edit `A.agda` and type-check it by invoking Agda using a shell command.
* You reload `B.agda` in Emacs.

In this case you might hope that `A.agda` should not be type-checked again (if the same options are in effect). However, I have observed that, in at least some cases, Agda *does* type-check the file again instead of loading the interface file.

This is a regression, Agda 2.6.1.2 does not have this bug, but Agda 2.6.2 does. Bisection points towards @rwe's commit 7119290686e02c11eff7695bf37c27582577663f ("imports/refact: Combine more conditions in getStoredInterface").

Here is a script that can be used to demonstrate the bug:
```haskell
#!/usr/bin/env runhaskell

{-# LANGUAGE RecordWildCards #-}

import Data.List
import System.Exit

import RunAgda

moduleA      = "module A where\n"
moduleAExtra = "postulate A : Set\n"
moduleB      = "module B where\nimport A\n"

main :: IO ()
main = runAgda ["--no-libraries"] $ \(AgdaCommands { .. }) -> do

  -- Discard the first prompt.
  echoUntilPrompt

  -- Write A and B.
  writeFile "A.agda" moduleA
  writeFile "B.agda" moduleB

  -- Load B.
  loadAndEcho "B.agda"

  -- Modify A.
  writeFile "A.agda" (moduleA ++ moduleAExtra)

  -- Load A in a separate process.
  (runAgda ["--no-libraries"] $ \(AgdaCommands { .. }) -> do
     echoUntilPrompt
     loadAndEcho "A.agda")

  -- Load B again.
  output <- loadAndEcho "B.agda"

  -- Restore A.
  writeFile "A.agda" moduleA

  -- Check the output.
  if not ("(agda2-status-action \"Checked\")" `elem` output) ||
     any ("Checking A" `isInfixOf`) output
  then exitFailure
  else exitSuccess
```

### LINKED ISSUE #7402: Mimer internal error in hole with constraint
```agda
postulate
  A : Set
  x : A
  f : (P : A → Set) → P x

g : (P : ((A → A) → A) → Set) → P (λ k → k x)
g P = f (λ x → P {! !})
```
Running `C-c C-a` in the hole results in:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Telescope.hs:688:24 in Agda-2.8.0-8OtZvJ9h6Mn4rrWgQM63zA:Agda.TypeChecking.Telescope
```
which is at: https://github.com/agda/agda/blob/5da3f3f2be5fc0d4ed6a2b828bd751e44e29292f/src/full/Agda/TypeChecking/Telescope.hs#L688 called from: https://github.com/agda/agda/blob/5da3f3f2be5fc0d4ed6a2b828bd751e44e29292f/src/full/Agda/Mimer/Mimer.hs#L1141

There's no internal error if `P : ((A → A) → A) → Set` is a postulate instead of a parameter.

### LINKED ISSUE #7436: Code only reachable from display forms not serialised in Agda 2.7.0
This is on  Agda 2.7.0,  MAlonzo, on Debian Linux 12                            
installed by                                                                    
 $ cabal install -foptimise-heavily -j1,                                        
                                                                                
lib-2.1                                                                         
                                                                                
All the application modules are type-checked by type-checking CheckAll.agda.    
CheckAll.agda  consists of many lines of kind                                   
  open import Foo                                                               
And there is only one module in this list that applies the `main' function:                  
  Pol.Univariate.KTest.                                                         
It is the example that uses other modules and needs to be compiled to executable.                                                                     
                                                                                
Type checking:                                                                  
 $ agda $agdaLibOpt $agdaFlags  CheckAll.agda  +RTS -M12G                       
 where                                                                          
 $agdaFlags = "--auto-inline --guardedness"                                     
                                                                                
Compilation to executable example:                                              
 $ agda -c $agdaLibOpt $agdaFlags Pol/Univariate/KTest.agda +RTS -M12G          
                                                                                
It reports                                                                      
"                                                                               
An internal error has occurred. Please report this as a bug.                    
Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/         
TypeChecking/Monad/Signature.hs:869:32 in                                       
Agda-2.7.0-5b1c26af24f71478be7921bfd690317a6888da853b10d78f399aa31cab72a91e:    
Agda.TypeChecking.Monad.Signature                                               
"       

Call the above approach (I).                                                            
a) In a strange way, this error does not appear for other executable examples set instead of  Pol/Univariate/KTest.agda.                                    
b) I also recall (not very surely) that  Agda 2.6.4.3  is free of this effect.   
c) There was some explanation about the effect, may be about year ago, which I did not understand.                                                         
                        
Anyway, I apply the following approach instead.                                 
                                                                                
Approach (II)                                                                   
-------------                                                                   
(1) Start with only *.agda files of application.                                
   Comment out in CheckAll.agda all the lines for the modules that have `main' . 
   This is only to remember the list of examples to be compiled separately.           
(2) Type-check  CheckAll.agda.                                                  
(3) Choose the needed example  Foo.agda  among the commented out lines and      
    command                                                                     
    $ agda -c ... Foo.agda                                                      
(4) Process other examples in this way by repeating (3)  (without type-checking CheckAll.agda).                                      
                                                                                
This compiles the examples correctly.                                           
                                                                                
I write this because users will be frightened by this "internal error"  message and will doubt of how to organize usage of their applications  when such have examples to be compiled to executables.                          
I wonder of whether it is possible to fix Agda in such a way that the above effect would not appear at all.

### PR DESCRIPTION
**Pull request by andreasabel**
I propose to release important bug fixes over 2.7.0 as 2.7.0.1.

Candidate: https://hackage.haskell.org/package/Agda-2.7.0.1/candidate

Please review, in particular the Changelog, and try the candidate!

- **CI deploy.yml: bump base tag for nightly to v2.7.0**
- **Fix internal error for `{-# COMPILE GHC Set1 #-}`**
- **Fix internal error on {-# REWRITE Set1 #-}**
- **Fix internal error with REWRITE on pattern synonym**
- **Makefile: fix fast-succeed target**
- **fix #7402: mimer failing on already instantiated goal**
- **Remove disclaimer that Agda would not follow the Haskell PVP**
- **Makefile: increase heap max for GHC 9.10 compiler**
- **Fixed #7199.**
- **Fix #7436: make display forms of imported names DeadCode roots**
- **Reproducer for issue #7436**
- **Revert default to `--no-save-metas`**
- **Setup.hs: Fix an error introduced by PR #6988**
- **Re #6988: more comments, refactor to allow partial application of toIFile**
- **Re #7455: Setup.hs: catch when Agda did not produce all agdai files**
- **Change Agda version to 2.7.0.1**
- **Move CHANGELOG.md for 2.7.0 to doc/release-notes/2.7.0.md**
- **Changelog for Agda 2.7.0.1**
- **Bump standard and cubical library submodules**

List was extended, see tab "Commits".

### CODE REVIEW

**Comment by andreasabel** [comment]
The failure of the `cabal install` workflow https://github.com/agda/agda/actions/runs/10683742640/job/29612530382?pr=7469 is caused by
- https://github.com/haskell/cabal/issues/10237

**Comment by L-TChen** [comment]
I wonder how a release is published on GitHub since the CI `deploy.yml` is not triggered properly to package the binaries. Maybe I can fix this before releasing `2.7.0.1`?

**Comment by andreasabel** [comment]
> I wonder how a release is published on GitHub since the CI `deploy.yml` is not triggered properly to package the binaries. Maybe I can fix this before releasing `2.7.0.1`?

So far we have not published binaries for the regular releases, only for the `nightly` ones.  I agree it would be nice to get binaries on stable GitHub releases as well.

The current workflow is that a successful `test.yml` triggers a `deploy.yml`.
However, part of our current release procedure is to remove the testsuite, and consequently delete `test.yml` that depends on the testsuite and `deploy.yml` that depends on `test.yml`.

So to get binaries for the regular releases, maybe it is easiest if `deploy.yml` as not only triggered by `test.yml` but also by tags that look like (pre-)releases, that is `v<VERSION>` where `VERSION` is made up from digits and dots.

**Comment by L-TChen** [comment]
> So to get binaries for the regular releases, maybe it is easiest if `deploy.yml` as not only triggered by `test.yml` but also by tags that look like (pre-)releases, that is `v<VERSION>` where `VERSION` is made up from digits and dots.

This is odd. 😕  This case should trigger the workflow I pushed last time:
https://github.com/agda/agda/blob/26ef5bcba940898ca861ea7a46304e3a30dea77b/.github/workflows/deploy.yml#L256-L260

and, if trigged by this condition, the binaries should be published as well:

https://github.com/agda/agda/blob/26ef5bcba940898ca861ea7a46304e3a30dea77b/.github/workflows/deploy.yml#L244-L255

**Comment by andreasabel** [comment]
> This is odd. 😕 This case should trigger the workflow I pushed last time:

Oh, sorry, then I was working under outdated assumptions.

This is good news, so all I need to fix here is to _not_ delete `deploy.yml`.

**Comment by andreasabel** [comment]
One has to be a bit careful though because deploy will delete an existing release with the same tag. https://github.com/agda/agda/blob/26ef5bcba940898ca861ea7a46304e3a30dea77b/src/github/workflows/deploy.yml#L321-L324
In preparing the releases, I included both CHANGELOG and auto-generated release notes, so there is a bit of manual work that could be lost if one recreated the tags for older releases.

**Comment by andreasabel** [comment]
Let's wait a bit for https://github.com/agda/agda-stdlib/pull/2473 to land.
- https://github.com/agda/agda-stdlib/pull/2473

**Comment by andreasabel** [comment]
This PR has been tested with latest std-lib (v2.1.1).

The candidate https://hackage.haskell.org/package/Agda-2.7.0.1/candidate has been updated and is ready for testing!

@UlfNorell @jespercockx @nad @L-TChen @plt-amy

**Pull request merged**
