### PR TITLE
Moved the internal tests to a Cabal test-suite

### PR DESCRIPTION
**Pull request by asr**
I'm working peacefully on #2083. I created this PR to show my current approach. Any suggestion?

### CODE REVIEW

**Comment by asr** [comment]
In the meantime, you can run the (incomplete) internal test-suite by

```
cabal test internal
```

**Comment by andreasabel** [comment]
LGTM!  Only suggestion: rename `Internal` to `AgdaQuickCheck` or `AgdaFuzzing` or `AgdaInternalTests`.

**Comment by asr** [comment]
Thanks for the feedback. I will use `AgdaInternalTests`.

**Comment by phile314** [comment]
Looks good. You could also try to hook up the QuickCheck tests with the existing cabal test suite using tasty-quickcheck ( https://hackage.haskell.org/package/tasty-quickcheck ). That might also improve parallelism, but I am not sure about that.

**Comment by asr** [comment]
I think that _only_ one cabal test-suite is not a good idea. We can use tasty-quickcheck on the internal-tests test-suite later.

**Comment by phile314** [comment]
I don't really see the advantage of having multiple test suites?

I would argue for actually using only _one_ test suite in the long run, as it shortens the Agda.cabal file and it may improve the cabal build time as it has to link one executable less. Test selection would then work using the "-p" pattern option of the existing tasty test runner, instead of choosing by the cabal test suite name.

Moving the tests out of the Agda library makes sense in any case, so feel free to ignore me;-)

**Comment by asr** [comment]
We can discuss about the integration later.

**Comment by asr** [comment]
I'll will push the commit later.

**Comment by asr** [comment]
I'm not receiving Travis email notifications on _my_ pull requests. Am I the only one with this problem?

**Comment by asr** [comment]
From Travis [documentation](https://docs.travis-ci.com/user/notifications/#Email-notifications): "Pull Request builds do not trigger email notifications."

**Pull request closed without merging**
