### PR TITLE
[ #4340 ] Makefile revision

### PR DESCRIPTION
**Pull request by L-TChen**
- [ ] Support cabal-install 3.0.0.0 (#4216).
- ~~[ ] Use `stack` whenever possible if `stack.yaml` is present.~~ (next time)
- [x] Following undefined / outdated targets are removed: 
  * `install-O0-bin`
  * `full`: Use `install` instead
  * `prof`: Same as `install-prof-bin`
  * `*-stack-copy-artefacts`(merged with `*-install-bin`)
  * `quick`: its dependency `install-O0-bin` is not defined, so obviously no one used it
- [x] Add targets `help` for printing the help information and `list` for listing all targets. 
- [x] Target `debug` print variables `STACK_CMD`, `STACK_INSTALL_OPTS`

### CODE REVIEW

**Comment by L-TChen** [comment]
`make help` now prints a list of targets with its comment from `Makefile`. 

A target or a phony target is listed if 
1. the list of (possibly no) dependent targets are followed by `##`, or
2. the phony name is followed by `##`.

then the target name and the comment which can be empty after `##` will be printed. 

For example, an excerpt in `Makefile`
```makefile
.PHONY : compile-emacs-mode ## Compile Agda's Emacs mode.
compile-emacs-mode: install-bin
	$(AGDA_MODE) compile
debug : ## Print debug information.
```
produces the following information 
```
  compile-emacs-mode          Compile Agda's Emacs mode.
  debug                       Print debug information.
```
when `make help` is executed.

Moreover, a block in the help information starts with `##` in the `Makefile` followed by the section name *without* the character `#` in the end. Any line consists of `#` only will be printed as a new line in the help information. Therefore, 
```makefile
##############################################################################
## Auxiliary targets
## I don't want to be printed ##

help: ## Display this information.
	@echo "Available targets:"
	@sed -n \
		-e 's/^\.PHONY[[:blank:]]*:[[:blank:]]*\([[:graph:]]*[[:blank:]]*##\)/\1/p' \
		-e 's/\([[:alnum:]_-]\{1,\}\)[[:blank:]]*:[[:blank:]]*[^#]*##[[:blank:]]*\([^\#]*\)$$/\1 ## \2/p' \
		-e 's/^\(#\{2,\}\)$$//p' \
		-e "s/^\(#\{2,\}[[:blank:]]*\)\([^#]\{1,\}\)$$/\2/p" \
		Makefile | \
		awk 'BEGIN {FS = "##"}; \
			NF == 0 { print };\
			NF == 1 { print $$1 };\
	  	        NF == 2 { printf "  \033[36m%-26s\033[0m %s\n", $$1, $$2};'
```
produces a section when `make help` is invoked:
```
Auxiliary targets
  help                        Display this information.
```

**Comment by L-TChen** [comment]
`make list` lists all (not necessarily phony) targets. The parsing rule is not robust, so run `make -pq` if you need a detailed report.

**Comment by L-TChen** [comment]
The `Makefile` for `hTags` needs to be updated to support cabal's new nix-style build system. Otherwise, this PR should be ready to merge.

**Review by asr — CHANGES_REQUESTED** [review]
Keep alphabetically ordered the variables in the `debug` rule please.

**Review by banacorn — APPROVED** [review]

**Comment by L-TChen** [comment]
> Keep alphabetically ordered the variables in the `debug` rule please.

Done. 

The issue with `TAGS` should also be fixed now. Waiting for the CI verdict...

**Comment by L-TChen** [comment]
It turns out that it is not so simple. 
Oddly, `cabal new-install --enable-tests` emits the error message (bug?)
```
cabal: --enable-tests was specified, but tests can't be enabled in a remote package
```
However `cabal new-configure` does not seem to use `--builddir` properly, as it always build inside `dist-newstyle` instead of `dist-2.6.1`. 

It looks like a bug of cabal?

**Pull request merged**
