### PR TITLE
Fix for issue #5551

### LINKED ISSUE #5551: Panic when showing module contents with pattern synonym
Pressing `C-c C-o` (`agda2-module-contents-maybe-toplevel`) on the hole produces a panic. `Agda version 2.6.2`

```agda
module Scratch where

module Foo where
  pattern pat x = x

foo : Set
foo = {!Foo!}
```

```
/sharedhome/home/james/Documents/agda/Scratch.agda:7,7-14
Panic: Unbound name: Scratch.Foo.pat[0,2,6]@ModuleNameHash
10507650244568858286
when retrieving the contents of a module
```

### LINKED ISSUE #5845: Internal error caused by abstracting `variables`
The following code causes an internal error:
```agda
    module Bug where

    record ⊤ : Set where
    record Σ-stx (A : Set) (B : A → Set) : Set where
      constructor _,_
      field
        fst : A
        snd : B fst

    syntax Σ-stx A (λ x → B) = Σ[ x ∈ A ] B

    module V (X : Set) (El : X → Set) where
      data V : Set where
        el : X → V
        Π : (i : X) → (El i → V) → V

      Sem : V → Set
      Sem (el S) = El S
      Sem (Π S T) = (s : El S) → Sem (T s)

      data Ctx : Set
      Env : Ctx → Set

      data Ctx where
        [] : Ctx
        _∷_ : (Γ : Ctx) → (T : Env Γ → X) → Ctx

      Env [] = ⊤
      Env (Γ ∷ T) = Σ[ γ ∈ Env Γ ] El (T γ)

      variable
        Γ : Ctx
        A B : Env Γ → X
        S T : Env Γ → V

    module L (X : Set) (El : X → Set) where
      open V X El

      Π̂ : (A : Env Γ → X) (B : Env (Γ ∷ A) → V) → Env Γ → V
      Π̂ A B γ = Π (A γ) (λ a → B (γ , a))

      data Tm : (Γ : Ctx) → (T : Env Γ → V) → Set
      eval : Tm Γ T → (γ : Env Γ) → Sem (T γ)

      data Tm where
        lam : Tm (Γ ∷ A) T → Tm Γ (Π̂ A T)

      eval tm = {!!}
```
It seems to be related to quantifying the variables for `lam`. The error message is:

    An internal error has occurred. Please report this as a bug.
    Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Generalize.hs:301:38 in ...

Latest version from the master branch as of this comment.

### PR DESCRIPTION
**Pull request by jespercockx**

### CODE REVIEW

**Comment by andreasabel** [comment]
Weird CI failure: https://github.com/agda/agda/actions/runs/3113139169/jobs/5048018977#step:9:34
```
+out > Compilation error:
+out > MAlonzo/RTE.o.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)
```
Maybe bump the cache:
https://github.com/agda/agda/blob/d135b51628223ecc3129c78100f987830a2fbc5b/src/github/workflows/test.yml#L186

**Comment by jespercockx** [comment]
How does one "bump the cache"? What cache are we talking about?

**Comment by andreasabel** [comment]
> How does one "bump the cache"? What cache are we talking about?

The CI cache.  Bumping would mean to modify in the quoted line `01` towards something else, like `02`.  (To have an effect, also `make -C .github/workflows`.)

**Comment by jespercockx** [comment]
Just rerunning the tests seems to have fixed the issue. There is still the timeout on `windows-latest`, but this seems to be happening on every PR currently so I am going to assume it is not anything specific to this one.

**Pull request merged**
