### PR TITLE
Erased data and record types and modules

### LINKED ISSUE #6271: Cubical: should generated code corresponding to erased constructors be erased?
When `--cubical-compatible` is used Agda generates code for each constructor (in `defineProjections` and `defineCompData`). If a constructor is erased, should the generated code also be erased?

### PR DESCRIPTION
**Pull request by nad**
See issue #4743.

I also addressed issue #6271: If a constructor is erased, then the corresponding generated definitions are also erased. However, I don't know if this is correct.

I have not modified the double-checker, and I don't know if that is necessary. (Is the double-checker still maintained?)

### CODE REVIEW

**Comment by nad** [comment]
> I have not modified the double-checker, and I don't know if that is necessary. (Is the double-checker still maintained?)

The double-checker does not [seem](https://github.com/agda/agda/pull/6288#issuecomment-1304639829) to care too much about erasure, so I don't plan to include any changes to it in this pull request.

**Comment by nad** [comment]
The pull request includes the following text in `doc/user-manual/language/runtime-irrelevance.lagda.rst` (see #6292):
```rst
TODO: Explain how the reflection machinery interacts with run-time
irrelevance.
```

**Review by jespercockx — COMMENTED** [review]
Thanks, this looks great to me. Two small remarks:
- The double checker is maintained but is currently too liberal regarding modalities, this should be fixed but not as part of this PR.
- Regarding reflection, I recently added the ability to run erased macros (see https://github.com/agda/agda/pull/5744). I'm not sure what else we should mention regarding the interaction between erasure and reflection.

**Comment by nad** [comment]
> * Regarding reflection, I recently added the ability to run erased macros (see #5744). I'm not sure what else we should mention regarding the interaction between erasure and reflection.

The manual contains an incomplete explanation of when Agda switches between compile-time and run-time mode. Switches performed by the reflection machinery are omitted, and should be included.

**Review by jespercockx — APPROVED** [review]

**Comment by nad** [comment]
> I also addressed issue #6271: If a constructor is erased, then the corresponding generated definitions are also erased. However, I don't know if this is correct.

@plt-amy [thinks](https://github.com/agda/agda/issues/6271#issuecomment-1334677456) that it is.

**Pull request merged**
