### PR TITLE
The --erased-cubical flag

### PR DESCRIPTION
**Pull request by nad**
See #4701. No support for compilation yet.

### CODE REVIEW

**Comment by andreasabel** [comment]
I see you added a CHANGELOG entry.  Do you want to release this in 2.6.2?  (You didn't add it to the milestone.)

**Comment by andreasabel** [comment]
@nad Btw, if you are preparing a PR, please do not prefix your branch name with `issue`, otherwise CI will run twice: Once for pushing to an `issue` branch, the second time for opening a PR.
(It is of course negotiable whether we should use the `issue` prefix for running CI, or change it to something less canonical.)

**Comment by UlfNorell** [comment]
Didn't we discuss this and decide that we should not run CI on `issue*` branches?

**Comment by nad** [comment]
> I see you added a CHANGELOG entry. Do you want to release this in 2.6.2? (You didn't add it to the milestone.)

The change should be documented in the changelog.

However, I think it makes sense to release this, if we mark it as experimental. I've already ported thousands of lines of code to `--erased-cubical`, and I don't want to keep those changes on separate branches.

Before we release this I'd like @Saizan's feedback on whether there are more cubical features that should be forbidden when `--erased-cubical` is used.

**Comment by andreasabel** [comment]
> Didn't we discuss this and decide that we should not run CI on `issue*` branches?

In the end, I kept the `issue` prefix for CI runs: https://github.com/agda/agda/issues/4729#issuecomment-824094722 
So I am using a different prefix for my PRs.

**Comment by nad** [comment]
I don't want to merge these changes yet.

**Comment by nad** [comment]
@Saizan, can you take a look at the changes in "[ #4701 ] Added support for --erased-cubical to the GHC backend." (currently e1b6f40a36aa622ebc8fe823ce4103a1fdb81c68)? The main changes are in [`Agda.Compiler.MAlonzo.Compiler`](https://github.com/agda/agda/commit/e1b6f40a36aa622ebc8fe823ce4103a1fdb81c68#diff-9daf6c626882c11ca96238650d17641589a4f432fb0c292fc83b0d407800c02a) and [`Agda.Compiler.Malonzo.Primitives`](https://github.com/agda/agda/commit/e1b6f40a36aa622ebc8fe823ce4103a1fdb81c68#diff-180ea11620d58dde6f8b9f012f593fc186aed9482fac4fe055b4e2ece5b03cd0).

**Comment by nad** [comment]
@andreasabel, can you take a look at the latest commit, which adds support for `--erased-cubical` to the JS backend?

**Comment by nad** [comment]
@andreasabel and @Saizan, do you want to take a look at the changes before I push them to the `master` branch?

**Pull request merged**
