### PR TITLE
[ fix #3187 ] applyFlagsToTCWarnings should respect the new flags

### LINKED ISSUE #3187: Acceptable code rejected when -Werror -Wignore is used
Consider the following code:
```agda
open import Agda.Builtin.Bool

F : Bool → Set
F true = Bool
F _    = Bool
```
This code is accepted by Agda, but rejected when `-Werror -Wignore` is used:
```
Exact splitting is enabled, but the following clause could not be
preserved as definitional equalities in the translation to a case
tree:
  F _ = Bool
when checking the definition of F
```
Note that I did not turn on `--exact-split`. Adding `--no-exact-split` to the command line does not help.

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by fredrikNordvallForsberg** [comment]
I'm 10000 km away from my computer at the moment, but would be happy to take a look at this in about a week. On the other hand, if it all looks good, don't wait for me!

**Comment by gallais** [comment]
I am not in a hurry. If master starts moving again and that creates nastier and
nastier merge conflicts, I'll consider going ahead before hearing back from you.
But at the moment it seems fine.

**Comment by gallais** [comment]
I don't understand why we are suddenly getting a ghc panic in InteractionTop which
this PR doesn't touch!

**Comment by asr** [comment]
Neither do I. Note that the Stackage test uses the *same* GHC than the "Cabal" test. I'm trying of reproducing the issue...

**Comment by asr** [comment]
I couldn't reproduce the issue.

**Pull request merged**
