### PR TITLE
Release 2.6.4.2

### LINKED ISSUE #7029: Internal error on confluence check when rewriting a defined symbol with a hole
_Agda version: 2.6.4.1 (installed via `cabal get Agda 2.6.4.1`)_

Type checking the following produces an internal error:

```agda
{-# OPTIONS --rewriting --confluence-check --with-K #-}

open import Agda.Builtin.Equality

{-# BUILTIN REWRITE _≡_ #-}

myrefl : ∀ {ℓ} {A : Set ℓ} {x : A} → x ≡ x
myrefl = ?

UIP : ∀ {ℓ} {A : Set ℓ} {x : A} → myrefl {ℓ} {A} {x} ≡ refl
UIP with refl ← myrefl = refl

{-# REWRITE UIP #-}
```

> An internal error has occurred. Please report this as a bug.
Location of the error: \_\_IMPOSSIBLE\_\_, called at src/full/Agda/TypeChecking/Rewriting/Confluence.hs:606:19

Removing confluence checking yields the following expected (I assume) error:

> UIP  is not a legal rewrite rule, since the left-hand side 
myrefl  reduces to  ?0
when checking the pragma REWRITE UIP

### LINKED ISSUE #7044: Serializer crashes on blocked definitions when using --allow-unsolved-metas
During tinkering with `agda-unimath` repo (and in the process, resetting all definitions to holes), I've encountered an "IMPOSSIBLE" bug.

I reduced the error to a few files: [impossible.zip](https://github.com/agda/agda/files/13802686/impossible.zip)

## Reproduction

From the `src` directory, after extracting the attached zip file, invoke `agda .\foundation\action-on-identifications-functions.lagda.md --allow-unsolved-metas`.

## Expectation

Agda checks the files successfully.

## Result

An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full\Agda\TypeChecking\Serialise\Instances\Internal.hs:232:21 in Agda-2.6.2.2-I0mdgVgXQQ9I75Kwxokerz:Agda.TypeChecking.Serialise.Instances.Internal

I am able to reproduce this both in native Windows and WSL, so it seems independent of the OS.

### LINKED ISSUE #7048: hcomp symbols in interface not hidden under --cubical-compatible
From #7044 ([comment](https://github.com/agda/agda/issues/7044#issuecomment-1873395839_)):

> When printing the signatures of the interface, I see `Inner.hcomp-T`. Why is that generated without `--cubical-compatible`?

Test case:
```agda
module Inner where

data T : Set where
  t : T
```
Running
```shell
agda-quicker Inner.agda -v 5 | grep hcomp
```
shows that cubical-related code is executed:
```
Generated name: [...] "hcomp-T" [...]
```

### LINKED ISSUE #7070: Don't set a default maximum heapsize for Agda runs
A bit more than 4 years ago it was decided to set the maximum heap size for Agda to 3.5G:
https://github.com/agda/agda/blob/a9c17630e4d0f21c845cdd98857174916ed6d7f1/Agda.cabal#L864
- #3759 

A CI run fails for me where this limit is reached: https://github.com/graded-type-theory/graded-type-theory/actions/runs/7666738532/job/20895151382
I was in vain searching workflow- and make-files to look for a setting of the maximum heap size, only to remember that I had seen something in `Agda.cabal`...

From a UX perspective, I find it odd that we ship Agda with a default max heapsize.
Issue #3759 talks in the OP about a custom error should the heap be exhausted:
> Setting a maximum heap size can mean that Agda runs faster and needs less memory. However, it can also mean that Agda crashes when it otherwise wouldn't. Thus, if we change the default maximum heap size, then it might be a good idea to make Agda print a customised error message, informing the user of how to increase the maximum heap size, when the program runs out of heap (by catching the [HeapOverflow](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Exception.html#t:AsyncException) exception; perhaps it makes sense to tweak the [-Mgrace](https://downloads.haskell.org/~ghc/8.6.5/docs/html/users_guide/runtime_control.html#rts-flag--Mgrace=%E2%9F%A8size%E2%9F%A9) RTS option).

Such a nice error has never been implemented, so I suppose from a UX perspective we should also not set a max heap size by default.

ATTN (original contributors): @nad @WolframKahl @jespercockx @UlfNorell

### LINKED ISSUE #7095: Agda build flags appear as "automatic", but they are all "manual"
Is there a reason why the cabal build flags of Agda are mostly "automatic"?  (I think none of it is switched on by the cabal constraint solver...)
https://github.com/agda/agda/blob/34ada52dc8d85ebf5e16c585a2af79bdea75488d/Agda.cabal#L164-L191

Automatic flags are hidden on hackage:

Screenshot 2024-02-07 at 13 54 17

This is how it looks when you show them:

Screenshot 2024-02-07 at 13 49 26

### PR DESCRIPTION
**Pull request by andreasabel**
Todo for RC:
- [x] Remove `-Werror` and testsuite from Agda.cabal, trim stack.yaml files
- [x] Publish release candidate on Hackage: https://hackage.haskell.org/package/Agda-2.6.4.2/candidate
- [x] Announce release candidate

Included commits:
- Delete unused `glue1` bindings (#7021)
- CI user-manual: bump python to 3.11 and setup-python to v5
- issue7020: add note about compilation of irrelevant fields (#7026)
- [ fix #7029 ] Check that function does not have unsolved metas when we add a rewrite rule to it and confluence checking is enabled
- CI: bump stack-9.6.3.yaml to lts-22.0
- Recompute blocker in equalSort (#7039)
- update to stdlib-v2.0
- [ fix #7044 ] Serialize `defBlocked` as `neverUnblock` (#7046)
- [ fix #7048 ] Only define hcomp constructors when --cubical-compatible.
- [ debug #7047 ] `Generalize.hs`: debug printing for open metas
- [ refactor ] replace hand-rolled recursion `suggestNames` by a `zipWithM`
- [ refactor ] simplify isFreshMeta (drop unused argument)
- [ workflows ] Bump up/download-artifact action to v4
- add --keep-pattern-variables to options that don't require recompilation (#7060)
- [ workflows ] bump GHC 9.6.3 to 9.6.4
- [ workflows ] Bump cache action from v3 to v4
- Some documentation fixes (#7065)
- Add 'Inference in Agda' to the list of tutorials
- [ workflow ] Allow any newer PATCH version for `cancel-workflow-action` (#7074)
- Provide a `.agda-lib` for Agda builtins (#6988)
- Make tests for #641 less brittle (#7075)
- Fix #7070: remove built-in max heap setting -M3.5G for Agda
- Add course to “Courses using Agda” (#7091)
- Re #7081: add build with debug-{serialisation,parsing} flags to cabal CI
- Allow ansi-terminal-1.1
- Fix #7095: our cabal build flags are actually all "manual".
- Allow zlib-0.7
- Change version to Agda 2.6.4.2
- Float DefP clauses above catch-alls (#7097)
- Update .mailmap
- Update copyright range to 2024, add doc/release-notes/2.6.4.1.md
- Bump cubical and std-lib to their latest master
- #6972: Also save backcopies in interface file (#6974)
- CHANGELOG for 2.6.4.2

### CODE REVIEW

**Review by jespercockx — APPROVED** [review]

**Review by plt-amy — APPROVED** [review]

**Comment by nad** [comment]
I did not see #6999 in the list above.

**Comment by andreasabel** [comment]
> I did not see #6999 in the list above.

Because it was already on master when 2.6.4.1 was released.  You can see it here: https://github.com/agda/agda/commits/prep-2.6.4.2/?after=16884463a81331bb90d62904b886ba2df84d497b+34
(The list above is auto-generated.)

**Comment by andreasabel** [comment]
I released RC2 as hackage candidate and announced it on the Agda lists and on Zulip.

Changes over Agda 2.6.4.2 RC 1 are three more fixes:

- [Issue #7104](https://github.com/agda/agda/issues/7104):
  Warning "there are two interface files" should not be serialized

- [Issue #7105](https://github.com/agda/agda/issues/7105):
  Internal error in generate-helper (C-c C-h)

- [Issue #7113](https://github.com/agda/agda/issues/7113):
  Instance resolution runs too late, leads to `with`-abstraction failure

**Comment by andreasabel** [comment]
Published on 
- hackage: https://hackage.haskell.org/package/Agda-2.6.4.2
- github: https://github.com/agda/agda/releases/tag/v2.6.4.2
- wiki: https://wiki.portal.chalmers.se/agda/Main/Download
- mailing list and zulip

Made 2.6.4.2 default on readthedocs.

**Comment by andreasabel** [comment]
Mission accomplished.

**Comment by jespercockx** [comment]
Nice, great work!

**Pull request closed without merging**
