### PR TITLE
Fix #4881 - Don't use unique NameId for NoName lookups.

### LINKED ISSUE #4881: Internal error at src/full/Agda/Syntax/Concrete/Definitions.hs:904
You can trigger the following internal error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Syntax/Concrete/Definitions.hs:904
```
Minimal test case:
```
_ : ?
```

### PR DESCRIPTION
**Pull request by uncle-betty**
This is a proposal for fixing #4881, which is caused, I think, by `replaceSigs`'s failure to lookup `NoName`s from `LoneSigs`.

The underlying idea is to keep using the unique `NameId` (`x'`) for the axiom, but do the `LoneSigs` lookup with the original `NoName` `NameId` (`x`), i.e., `NameId 0 0`.

Nothing changes for things that aren't `NoName`s.

### CODE REVIEW

**Comment by rwe** [comment]
@uncle-betty I think this makes sense to me, and the tests pass.

Could this negatively affect cases with multiple distinct `_`? Like:
```agda
_ : x ≡ y
_ = refl

_ : 1 + 2 > 3
_ = _
```

Or in a single expression:
```agda
x : _ → _ → _
x = _>_
```

I imagine the tests must already include something like that?

**Comment by uncle-betty** [comment]
Thanks for the review.

As far as I can see, `replaceSigs` is only ever reached after the available declarations have been matched with the available definitions. What's left in the `LoneSigs` map at this point are only declarations that don't have a definition.

So, any declaration that has a definition shouldn't be affected by a change to `replaceSigs`. I'd thus say that we are OK in cases like your first example, i.e., cases that come with multiple `_` declarations where each declaration has its matching definition.

It also seems like there are tests that cover similar cases, e.g., the test cases for issues #3295 or #2498.

Cases like your second example shouldn't be affected at all, as far as I can tell, as the keys in the `LoneSigs` maps are names of declarations and definitions, i.e., the `x`s in your second example and not the `_`s.

Maybe @andreasabel has additional insights based on his design for introducing unique `NameId`s for `_`s to fix #4157?

**Comment by rwe** [comment]
I've requested review from a couple people. (It's nice to see small PRs with tests go through quickly when possible, vs going stale). If no one else can review, I'll approve because of the justifications above.

**Review by gallais — COMMENTED** [review]
Given all the variations we have seen so far, we could maybe add a test case for
a mutual block with missing definitions

```agda
mutual

  _ : Set

  _ : Set -> Set
```

An implicit mutual block with missing definitions

```agda
_ : Set
_ : Set -> Set
```

**Comment by uncle-betty** [comment]
Thanks for the feedback. Let me make sure that I understand the proposal.

Two `_` declarations without definitions aren't currently supported and lead to a `Duplicate definition of _` error. Which seems to be by design, because `_`s in `LoneSigs` are always keyed by a `NameId` of `NameId 0 0`, so there cannot be more than one lone signature (= a declaration without a matching definition) for `_` at any time.

The only way in which multiple `_`s are supported at this time seems to be alternating `_` declarations and `_` definitions, so that there's never more than one `_` definition that doesn't have a declaration. Something like this:

```agda
data Data : Set where

_ : Set
-- Now LoneSigs contains _

_ = Data
-- Now LoneSigs doesn't contain _

_ : Set -> Set
-- Now LoneSigs contains _ again.
```

The above in fact represents another instance of the issue at hand addressed by this PR.

To clarify:

- Are we saying that we would like to add the test proposed by @gallais to `test/Fail` as a second test for this issue, to make sure that Agda reports the expected `Duplicate definition of _` error?

- Or are we saying that the proposed test case should actually succeed, which it currently wouldn't by design? I think that this would be more involved, though, than a mere bug fix for the issue at hand.

**Comment by andreasabel** [comment]
I think the examples given by @gallais should fail, but maybe with a more refined error than `Duplicate definition of _` (because duplicate _definition_ of `_` _is_ allowed).  The error could be `Missing definition of _` or something more specific like `Duplicate declaration of _ in a mutual block`.

**Comment by uncle-betty** [comment]
Thanks for the explanation.

I added a new exception and error message as well as the two proposed test cases, and I rebased everything off current master.

I went with "Duplicate declaration of _" but left out "in a mutual block", as mutual blocks can be implicit - which I thought might be a little confusing, at least to newbies like me. ("What?! I didn't write a mutual block.") But, obviously, this is really up to you guys. Happy to change the wording.

**Review by andreasabel — APPROVED** [review]
Your analysis looks solid and the solution simple. I do not see any obstacle to merging this.
Thanks for your contribution!

**Pull request merged**
