### PR TITLE
[ re agda/agda-stdlib#726 ] Add FloatToWord and its injectivity

### PR DESCRIPTION
**Pull request by L-TChen**
Regarding https://github.com/agda/agda-stdlib/issues/726, a bit-to-bit primitive conversion `primFloatToWord64` from `Float` to `Word64` which identifies NaNs is proposed as well as an injectivity proof `primFloatToWord64Injective`. 

It is made possible by the casting `castDoubleToWord64` from `Double` to `Word64` added to GHC 8.4.1 in `GHC.Float`. For details, see https://phabricator.haskell.org/D3358. 

Priori to GHC 8.4.1, a possible cheap implementation of `castDoubleToWord64` is to use `poke` and `peek` in `Foreign.Storable` with unsafe IO operations, all in Haskell 2010. This solution comes from a StackOverflow [question](https://stackoverflow.com/questions/6976684/converting-ieee-754-floating-point-in-haskell-word32-64-to-and-from-haskell-floa/7002812#7002812). 

Since `primFloatToWord64` generates a unique representation for every floating number except NaNs, we can then use `primWord64ToNatInjective` to derive a safe decidable propositional equality for `Float`. The inverse is not given. 

Unless there is any float operation differentiating NaNs, this should be consistent, right? 

[ The C preprocessor directives probably need to be done more carefully... ]

### CODE REVIEW

**Comment by banacorn** [comment]
Anyway to activate the Travis CI checks?

**Review by gallais — COMMENTED** [review]
From the primitives side of things, this looks good to me.
I don't know enough about Floats to determine whether the added primitive is indeed safe.

**Comment by nad** [comment]
I seem to recall that we encountered some consistency problem related to NaNs in the past.

**Comment by gallais** [comment]
@nad I had a look and found #2169 and #2155

**Comment by nad** [comment]
It seems as if we expose a bitwise equality test.

**Comment by L-TChen** [comment]
> It seems as if we expose a bitwise equality test.

Yes, I checked the implementation of `identicalIEEE` and it is simply a bitwise comparison, see [here](http://hackage.haskell.org/package/ieee754-0.8.0/src/cbits/double.c). So, the current float equality tests 
```agda
floatEq :: Double -> Double -> Bool
floatEq x y = identicalIEEE x y || (isNaN x && isNaN y)
```
checks if they are bit-wise equal or NaNs. So, if `castDoubleToWord64` really does bitwise copy, then  `primFloatToWord64` should be consistent with the current equality test.

**Comment by phile314** [comment]
Only missing bit I can see here is the primitive implementation for the GHC backend. Adding ``doubleToWord64`` to the RTE should do the trick:

https://github.com/agda/agda/blob/master/src/data/MAlonzo/src/MAlonzo/RTE.hs

**Comment by L-TChen** [comment]
> Only missing bit I can see here is the primitive implementation for the GHC backend. Adding `doubleToWord64` to the RTE should do the trick:
> 
> https://github.com/agda/agda/blob/master/src/data/MAlonzo/src/MAlonzo/RTE.hs

Thanks! 

BTW, `make test` still fails but, I think, it is due to the recent commit on `master`.

**Comment by L-TChen** [comment]
As for testing, when my change is applied to 67bf9f5d4 (the most recent commit on the branch `release-2.6.0.1`), it passes all tests with `latex-html-test` skipped. 

So, I think the Travis CI failed because of the recent commits on `master`.

**Comment by nad** [comment]
> It seems as if we expose a bitwise equality test.

Perhaps I was mistaken. I think we used to expose such a test, but some changes were made back in 2016 (936beb8a5de4885280f74308d9d171c5c7c548dd), and I don't know if any released version of Agda made such a test available to users.

**Comment by L-TChen** [comment]
> > It seems as if we expose a bitwise equality test.
> 
> Perhaps I was mistaken. I think we used to expose such a test, but some changes were made back in 2016 ([936beb8](https://github.com/agda/agda/commit/936beb8a5de4885280f74308d9d171c5c7c548dd)), and I don't know if any released version of Agda made such a test available to users.

Agda does provide a bitwise test, but I'd like to have a decidable propositional equality so that the `Reflection` module in the standard library can be safe. Sorry I didn't make it more clear. 

https://github.com/agda/agda/blob/e4591006e7b1f514e5b456ab03a91df9cde5bfd6/src/full/Agda/Utils/Float.hs#L6-L26

https://github.com/agda/agda/blob/e4591006e7b1f514e5b456ab03a91df9cde5bfd6/src/full/Agda/TypeChecking/Primitive.hs#L2024-L2030

**Review by phile314 — APPROVED** [review]
Looks good to me.

**Comment by nad** [comment]
> Agda does provide a bitwise test

The `floatEq` function can return `True` even if the two arguments aren't bitwise equal, right?

**Comment by L-TChen** [comment]
> > Agda does provide a bitwise test
> 
> The `floatEq` function can return `True` even if the two arguments aren't bitwise equal, right?

Oops, but that's true only if they are NaNs.

**Comment by gallais** [comment]
If we collapse distinct NaN floats then the conversion function to Word is not
actually injective, is it?

**Comment by L-TChen** [comment]
Agda's user manual says 

> Floats are represented by the type checker as IEEE 754 binary64 double precision floats, with the restriction that there is exactly one NaN value.

In fact, the following two NaNs with different raw representations in Haskell are definitionally equal in Agda
```agda
PNaN : Float
PNaN = 0.0 / 0.0

NNaN : Float
NNaN = - (0.0 / 0.0)

_ : PNaN ≡ NNaN
_ = refl
```
And the conversion function always normalises NaNs before converting to machine words.

https://github.com/agda/agda/blob/bcce40db8efed021263fa5f4d3099e774718ff16/src/full/Agda/Utils/Float.hs#L28-L34

**Pull request merged**
