### PR TITLE
Include Word.agda in Setup.hs, fixes #2923

### LINKED ISSUE #2923: Word.agda not included as builtin
The `Setup.hs` script does not include the `Word` module located in `src/data/lib/prim/Agda/`, but it includes every other file. Is this intentional?

### PR DESCRIPTION
**Pull request by iitalics**
See issue #2923

### CODE REVIEW

**Comment by UlfNorell** [comment]
Thanks. Can you make the PR against `stable-2.5`?

**Comment by iitalics** [comment]
Oops, I might have messed something up

**Comment by UlfNorell** [comment]
You might have to close this PR and open a new one against `stable-2.5`, I'm not sure...

**Comment by gallais** [comment]
I made the same mistake in #2895. Turns out you can change the base branch
by editing the title of the PR.

**Pull request merged**
