### PR TITLE
suggest a number of improvements to the documentation

### PR DESCRIPTION
**Pull request by JacquesCarette**
As per recent email to agda-list, propose some improvements to the documentation of the package mechanism.

### CODE REVIEW

**Comment by UlfNorell** [comment]
Nice, thanks!

**Comment by UlfNorell** [comment]
Oh, except it should've gone on stable... I'll cherry-pick.

**Comment by JacquesCarette** [comment]
So can I indeed delete that branch?

**Comment by UlfNorell** [comment]
Yes, it's all merged. Thank you.

**Pull request merged**
