### PR TITLE
5424: incorrect conPType when eta expanding telescope var

### LINKED ISSUE #5424: Internal error in v2.6.2 release candidate 1
Just been testing out my own [library](https://github.com/MatthewDaggitt/agda-routing) with the release candidate and I run into the following reproducible error whenever I try to type check [RoutingLib.Routing.Protocols.ShortestWidestPaths](https://github.com/MatthewDaggitt/agda-routing/blob/master/RoutingLib/Routing/Protocols/ShortestWidestPaths.agda) with v1.7-rc1 of the standard library:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Substitute.hs:136:33 in Agda-2.6.1.3.20210524-532d7bf5851283578419c02fbb50b4ffc0aa65ac0e2fac210b8cc48399568ee1:Agda.TypeChecking.Substitute
```

Will try and condense it down to a minimum example now.

### PR DESCRIPTION
**Pull request by UlfNorell**
Fixes #5424.

- [x] Will cherry-pick to release branch once this is merged.

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
Thanks! Will there be a new release candidate or should I try and install the branch directly myself once you've merged?

**Comment by nad** [comment]
Earlier today we talked about having a second release candidate for both Agda and the standard library.

**Comment by MatthewDaggitt** [comment]
Sounds like a plan :+1:

**Comment by UlfNorell** [comment]
It would be good if you could check if this fixes your original problem before the release candidate though.

**Comment by MatthewDaggitt** [comment]
Sure, I'm afraid I'm currently using my computer for something memory intensive, but I will leave Agda installing overnight tonight and get back to you tomorrow morning if this fixes the problem.

**Pull request merged**
