### PR TITLE
ignore .stack-work directory

### PR DESCRIPTION
**Pull request by swr1bm86**
after build with stack, it will generate a `.stack-work` directory, maybe we should put it in the ignore file?

### CODE REVIEW

**Comment by andreasabel** [comment]
Ah, could you please base this on stable rather than on master?  Thanks!

**Comment by zjhmale** [comment]
cool, i will @andreasabel

**Comment by swr1bm86** [comment]
@andreasabel  should i create a new PR merge to `stable-2.5` instead of `master`? maybe this PR should be closed since the merge destination can not be changed 😂 .

**Comment by swr1bm86** [comment]
@andreasabel now base on `stable-2.5`.

**Comment by andreasabel** [comment]
Yes, I think you need to create a new PR. This one still says

```
zjhmale wants to merge 1 commit into agda:master from zjhmale:ignore-stack-work 
```

**Pull request closed without merging**
