### PR TITLE
[ #4359 ] Separate Agda.Utils.* from the main package

### PR DESCRIPTION
**Pull request by L-TChen**
Following @jespercockx 's suggestion in #4359, most of modules under `Agda.Utils` is moved to `src/agda-utils` as a separate package. The `TAGS` target is updated, too.

There are three exceptions:

1. `Agda.Interaction.Options.IORefs` is included, since it is imported by `Agda.Utils.Suffix` and `Agda.Utils.String`. The only thing defined in `Interaction.Options.IORefs` is just a tag telling us if it is Unicode of ASCII. Shouldn't it be merged with something like `Agda.Utils.String`.

2. `Agda.Utils.Geniplate` is still placed under `src/full`. IMO, it should be placed under `Agda.Syntax`. 

3. `Agda.Utils.Permutation` is also under `src/full`, since it imports `Agda.Syntax.Position`. My suggestion is to split this file into two. Instances of `KillRange` should be placed somewhere else (maybe in `Agda.Syntax.Position` itself).

P.S. I will be traveling in the following days and unavailable to change anything a while.

### CODE REVIEW

**Comment by L-TChen** [comment]
I haven’t updated the `Makefile` to adopt cabal’s nix-style local build system, but it works well with `stack`. The use of local packages is not supported in Cabal 1.24, so we will have to “upgrade” to nix-style commands completely in order to separate `Agda.Utils.*` from the codebase.

**Comment by andreasabel** [comment]
I think this divorce should include splitting the internal testsuite `test/Internal` such that the tests for the Utils are packed with the agda-utils package.
Basically, after the divorce, I would be able to build and test the agda-utils on its own?

**Comment by L-TChen** [comment]
Two issues with moving relevant test suites to `agda-utils`: 
```
Internal.Utils.Graph.AdjacencyMap.Unidirectional
Internal.Utils.Permutation
```
`Permutation` is not part of `agda-utils`, so it should be fine to stay in `Agda`. `Graph.AdjacencyMap.Unidirectional` imports `TypeChecking.Positivity.Occurrence`, so it is not independent from `Agda`.

**Comment by andreasabel** [comment]
> `Graph.AdjacencyMap.Unidirectional` imports `TypeChecking.Positivity.Occurrence`, so it is not independent from `Agda`.

The tests use `Occurrence` as a sample edge type:
```haskell
-- | Sample edge type used to test some graph algorithms.

type E = Occurrence
```
So, the easiest is to copy the `Occurrence` type and its relevant instances over into the test suite.  It does not matter if `Occurrence` would in the future evolve differently in the code for the positivity checker and the utils-test, because it is just one example type to test the graph implementation.

**Comment by andreasabel** [comment]
> `Permutation` is not part of `agda-utils`, so it should be fine to stay in `Agda`.

`Permutation` imports `KillRange` from `Agda.Syntax.Position`.  To decouple the `Permutation` module from Agda, we can organize things the other way round, which is also the more proper way:  `Agda.Syntax.Position` instead imports `Permutation` to define the `KillRange` instances.

**Comment by L-TChen** [comment]
> So, the easiest is to copy the Occurrence type and its relevant instances over into the test suite. 

Done. There are quite a number of instances as well as functions `boundToEverySome` and `productOfEdgesInBoundedWalk` are copied, but it works.

> `Agda.Syntax.Position` instead imports `Permutation` to define the `KillRange` instances.

Also done. It looks more organised now. 

Some modules in Agda's test suite imports `Internal.Utils.*`, so those modules being imported need to be exposed as well...

**Comment by nad** [comment]
> It does not matter if `Occurrence` would in the future evolve differently in the code for the positivity checker and the utils-test, because it is just one example type to test the graph implementation.

That is not quite right:

https://github.com/agda/agda/blob/74d9fd53cd79e1d947b57952760946d24c8cfa8d/test/Internal/Utils/Graph/AdjacencyMap/Unidirectional.hs#L547-L562

**Comment by L-TChen** [comment]
I need to split this PR into a few more smaller PRs. Closing this PR.

**Pull request closed without merging**
