### PR TITLE
Fix `compCCHM` (`primComp`) parameter visibility in primitive library

### PR DESCRIPTION
**Pull request by ice1000**
Spotted by a friend. See https://github.com/agda/agda/blob/3185db9f8a4ad507dd73cbc4068cd56805e3cbf9/src/data/lib/prim/Agda/Primitive/Cubical.agda#L66

### CODE REVIEW

**Comment by ice1000** [comment]
I need help with setting the milestone. I don't know which one should I target.

**Comment by ice1000** [comment]
Sorry, I also forgot `[ci skip]`, but it's too late.

It's too late~ to apologize~ It's too late~

**Comment by andreasabel** [comment]
> Sorry, I also forgot `[ci skip]`, but it's too late.

I would think CI shouldn't be skipped for this change.  The workflows are already set up to not trigger build in this case.

**Comment by Saizan** [comment]
Thanks!

**Pull request merged**
