### PR TITLE
[DONT MERGE THIS] [ tests, MAlonzo ] Add compiler backend tests (for MAlonzo) 

### PR DESCRIPTION
**Pull request by phile314**
This was originally pull request #35 , but I closed that one by accident....

description from the original pull request:
++++++++++ 
Port of the Epic tests to the MAlonzo / UHC backend. This PR also adds a Haskell test runner for the ported Epic tests, implemented using tasty. I had to change the Makefile a little to work around some "cabal test" related issues.
...
The backend tests are only enabled for the MAlonzo backend right now, as building the UHC backend on travis needs some more work. But I think it's worth adding this tests as a first step anyway.

As it adds some new dependencies for the tests and changes the Makefile/travis files quite a bit, I thought I would open a PR instead of directly pushing to master. If you prefer if I just push this kind of changes, just let me know.
++++++++++

The tests now work also on the GHC 7.4.2 travis instance, unlike my last pull-request.

### CODE REVIEW

**Comment by asr** [comment]
Some questions and observations:

1. From your description, the tests in `test/Exec/simple/tests/` should be tested with MAlonzo and UHC. How to handle if says `Test1.agda` works with UHC but it doesn't work with MAlonzo?

2. I don't to want use two different preludes in the test suite, i.e. the current modules in `test/Common/` and the new modules in `test/Exec/simple/Prelude/`. Isn't possible to use one prelude only?

3. I don't see any reason for not starting by adding the compiler back-end tests for MAlonzo in the maintenance branch first. It is more difficult to have files such as `Agda.cabal`, `Makefile` and `.travis.yml` with many differences in both branches.

**Comment by phile314** [comment]
1. For each *.agda test file, multiple test cases are generated, one for UHC, and one for MAlonzo. The test cases are organized in a tree structure in tasty, and the output looks like this:
<pre><code>
all
  Exec
    MAlonzo
      simple
        HelloWorld:     OK (2.70s)
    UHC
      simple
        HelloWorld: FAIL (0.09s)
                    Result did not match golden value.
                    Diff between actual and golden value:
========================================
diff --git a/run/user/1000/HelloWorld9564.golden b/run/user/1000/HelloWorld9564.actual
index 0118d5f..832bf0d 100644
--- a/run/user/1000/HelloWorld9564.golden
+++ b/run/user/1000/HelloWorld9564.actual
@@ -1,4 +1,9 @@
-EXECUTED_PROGRAM
+COMPILE_FAILED
-ret > ExitSuccess
-out > Hello World
+ret > ExitFailure 1
+out > Checking tests.HelloWorld (/home/philipp/Projects/agda/agda-compiler-tests/test/exec/simple/tests/HelloWorld.agda).
+out >  Checking Prelude.IO (/home/philipp/Projects/agda/agda-compiler-tests/test/exec/simple/Prelude/IO.agda).
+out > /home/philipp/Projects/agda/agda-compiler-tests/test/exec/simple/Prelude/IO.agda:34,5-5
+out > /home/philipp/Projects/agda/agda-compiler-tests/test/exec/simple/Prelude/IO.agda:34,5:
+out > Parse error COMPILED_CORE<ERROR> return (\_ _ x -> UHC.Agda.Bu...
+out >
========================================
1 out of 2 tests failed (0.19s)
</code></pre>

There is also an interactive mode for this tests, similar to the one in the current Makefile.

2. That should be possible, I will try to merge the two preludes and will see how far I get.

3. Sounds like a good idea. Then the only difference between maint and master will be which tests are disabled.

**Comment by phile314** [comment]
I ported the changes to the maint-2.4.2 branch and that worked out fine.

I also merged my own "prelude" with the existing one in test/Common/. I had to update a few existing tests because some errors messages changed slightly and some imports needed fixing, but this changes are very small.

Travis builds:
maint-2.4.2: https://travis-ci.org/phile314/agda/builds/58605954
master: https://travis-ci.org/phile314/agda/builds/58615093

Example test output:
<pre>
======================================================================
======================== Compiler/exec tests =========================
======================================================================
all
  Exec
    MAlonzo
      simple
        VaryingClauseArity: OK (1.67s)
        TrailingImplicits:  OK (1.59s)
        StringPattern:      OK (1.54s)
        String:             OK (1.52s)
        Records:            OK (1.62s)
        PrintBool:          OK (1.63s)
        Mutual:             OK (1.69s)
        ModuleReexport:     OK (1.63s)
        ModuleArgs:         OK (1.56s)
        Literals:           OK (1.55s)
        Irrelevant:         OK (1.52s)
        HelloWorld:         OK (1.50s)
        Forcing4:           OK (2.26s)
        Forcing3:           OK (1.87s)
        Forcing2:           OK (1.74s)
        Forcing:            OK (2.51s)
        Coind:              OK (1.76s)
        CatchAllVarArity:   OK (1.72s)
        Arith:              OK (1.66s)
All 19 tests passed (32.54s)
</pre>

The changes for maint-2.4.2 are 99.9% identical to the ones in this pull request for master, so I think we can just discuss this using the diff for master instead of opening (yet) another pull request for maint-2.4.2. As soon as it is ready to merge, I can just push my maint-2.4.2 branch and merge it with master myself.

Is there anything else I should change or is everything okay now?

**Comment by phile314** [comment]
(Also very curiously, the exact same source fails the travis build in the agda/agda repo, but works in my phile314/agda repo. Very strange...)

**Comment by asr** [comment]
Why did you remove `travis_wait` from the command `make BUILD_DIR=$BUILD_DIR install-bin CABAL_OPTS=-v2`?

**Comment by asr** [comment]
Please add an upper bound for `process-extras` in Agda.cabal.

**Comment by asr** [comment]
From the documentation in Hackage, I couldn't see the difference between `tasty-sylver` and `tasty-golden`. Which is the difference?

**Comment by asr** [comment]
From the changes in `mk/paths` it seems you are using `cabal sandbox` somewhere. Where is `cabal sandbox` used?

**Comment by asr** [comment]
> I ported the changes to the maint-2.4.2 branch and that worked out fine.

Great!

> I also merged my own "prelude" with the existing one in test/Common/. I had to update a few existing tests because some errors messages changed slightly and some imports needed fixing, but this changes are very small.

Great!

**Comment by phile314** [comment]
>Why did you remove travis_wait from the command make BUILD_DIR=$BUILD_DIR install-bin CABAL_OPTS=-v2?

I believe this was only necessary because travis built Agda twice before this commit:
https://github.com/agda/agda/commit/ccdc6596d20fedfad2598c77c0fc080b4e15c391
So I think it's better to remove it, so that we notice if that should happen again. (not that I care much about it..)

I can split this into a seperate commit and add a comment about it in .travis.yml, if you agree with removing it?

> Please add an upper bound for process-extras in Agda.cabal.

Will do.

>From the documentation in Hackage, I couldn't see the difference between tasty-sylver and tasty-golden. Which is the difference?

- Interactive mode similar to the one in Agda's makefile.
- Better/easier API.
- Command line argument to exclude tests (see https://github.com/feuerbach/tasty/issues/38 ). There are some known failing tests which I had to disable, or travis will always report errors (see https://code.google.com/p/agda/issues/detail?id=1414 ).

>From the changes in mk/paths it seems you are using cabal sandbox somewhere. Where is cabal sandbox used?

I will split this changes off, we can discuss them separately. (I'm using the NIX package manager, and then it's annoying when cabal uses the user package database so I've been using sandboxes in my development environment. And at the moment, the Makefile is useless if one's using sandboxes.)

**Comment by asr** [comment]
> I believe that travis_wait was only necessary because travis built Agda twice before this commit: ccdc659

No. I added `travis_wait` for avoiding an error (see https://github.com/agda/agda/commit/afb1ab05c2992ab11660624af3951800ba766c25).

**Comment by asr** [comment]
>> From the changes in mk/paths it seems you are using cabal sandbox somewhere. Where is cabal sandbox used?

> I will split this changes off, we can discuss them separately.

Please, do it.

**Comment by phile314** [comment]
> > I believe that travis_wait was only necessary because travis built Agda twice before this commit: ccdc659

> No. I added travis_wait for avoiding an error (see afb1ab0).

The "make install-bin" step shouldn't take long, on the last build of master it took 20s ( https://travis-ci.org/agda/agda/jobs/58161846 ). In the revision where travis_wait was added, it looks like the Makefile uses ./dist-2.4.2.3 as build directory but "cabal build" does use the normal ./dist. Just linking the Agda executable without building certainly shouldn't take 10 minutes.

**Comment by asr** [comment]
>The "make install-bin" step shouldn't take long, on the last build of master it took 20s ( https://travis-ci.org/agda/agda/jobs/58161846 ). In the revision where travis_wait was added, it looks like the Makefile uses ./dist-2.4.2.3 as build directory but "cabal build" does use the normal ./dist. Just linking the Agda executable without building certainly shouldn't take 10 minutes.

You are right. Please forget my comment.

**Comment by phile314** [comment]
* added upper bound on process-extras
* Removed the cabal sandbox related changes
* travis_wait removal and a comment explaining the whole problem is in maint & master now, not part of this pull request anymore. (see https://github.com/agda/agda/commit/8295302cb7adfb68ac175f984f8f4013c556503c )

**Comment by asr** [comment]
> Is there anything else I should change or is everything okay now?

Please merge this pull request.

**Comment by asr** [comment]
Thanks!

**Pull request merged**
