### PR TITLE
[ fix #5379 ] sequence Applicative ReduceM to force unsafePerformIO

### LINKED ISSUE #5372: Use GHC 9.0.1 on GitHub workflows
Since `stack 2.7.1` is not in GitHub [virtual environments](https://github.com/actions/virtual-environments) we cannot use GHC 9.0.1 on the GitHub workflows.

### LINKED ISSUE #5379: __IMPOSSIBLE_VERBOSE__ isn't verbose any more
Somehow `__IMPOSSIBLE_VERBOSE__` doesn't work anymore, for quite a while already, says my stomach.
https://github.com/agda/agda/blob/b8f3916b107ada9a3b7376c2fccc0b147a2311b7/src/full/Agda/TypeChecking/Monad/Debug.hs#L193-L197
Agda does not actually print the message when instructed so via `-v impossible:10`:
```
$ agda -v impossible:10 Test3.agda 
Checking Test3 (/Users/abel/play/agda/bugs/Issue5378/Test3.agda).
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/TypeChecking/Monad/Signature.hs:703:32 in Agda-2.6.2-5NrKPj0LeUQ9NGWz0nEnLL:Agda.TypeChecking.Monad.Signature
```
Did this functionality maybe get lost in your refactoring, @rwe ?

### PR DESCRIPTION
**Pull request by andreasabel**
[ fix #5379 ] sequence `Applicative ReduceM` to force `unsafePerformIO`

`ReduceM` was losing debug messages.  By forcing whnfs in sequencing like (`*>`), we make sure that no `unsafePerformIO` (which prints the debug messages) is missed.

This PR
1. adds testing facilities for `__IMPOSSIBLE_VERBOSE__`
2. modifies `Applicative ReduceM`

### CODE REVIEW

**Comment by andreasabel** [comment]
Mmh, the tests do not run, likely because of #5380.

**Comment by andreasabel** [comment]
[CI currently fails](https://github.com/agda/agda/pull/5385/checks?check_run_id=2573174414) with a strange error:
```diff
    ImpossibleVerboseReduceM:                          FAIL (0.11s)
                                                       Result did not match golden value.
                                                       Diff between actual and golden value:
========================================
diff --git a/tmp/ImpossibleVerboseReduceM11765-0.golden b/tmp/ImpossibleVerboseReduceM11765-1.actual
index b0224fd..85aa314 100644
--- a/tmp/ImpossibleVerboseReduceM11765-0.golden
+++ b/tmp/ImpossibleVerboseReduceM11765-1.actual
@@ -1,6 +1,3 @@
-ret > ExitFailure 154
-out > ReduceM should also print this debug message.
-out > An internal error has occurred. Please report this as a bug.
-out > Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/ImpossibleTest.hs:«line»:«col» in «Agda-package»:Agda.ImpossibleTest
-out >   impossibleTestReduceM, called at src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:«line»:«col» in «Agda-package»:Agda.Syntax.Translation.ConcreteToAbstract
-out >
+ret > ExitFailure 1
+err > agda: Prelude.last: empty list
```
On my machine, this test works fine...

Update: Ran crusade #5387 against Prelude.last, but did not see anything that could have triggered this...

**Comment by andreasabel** [comment]
Now [CI fails](https://github.com/agda/agda/pull/5385/checks?check_run_id=2575428091) as if my change had no effect, i.e., the debug message is not printed:
```diff
    ImpossibleVerboseReduceM:                          FAIL (0.10s)
                                                       Result did not match golden value.
                                                       Diff between actual and golden value:
========================================
diff --git a/tmp/ImpossibleVerboseReduceM11521-0.golden b/tmp/ImpossibleVerboseReduceM11521-1.actual
index b0224fd..8897c48 100644
--- a/tmp/ImpossibleVerboseReduceM11521-0.golden
+++ b/tmp/ImpossibleVerboseReduceM11521-1.actual
@@ -1,5 +1,4 @@
 ret > ExitFailure 154
-out > ReduceM should also print this debug message.
 out > An internal error has occurred. Please report this as a bug.
 out > Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/ImpossibleTest.hs:«line»:«col» in «Agda-package»:Agda.ImpossibleTest
 out >   impossibleTestReduceM, called at src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:«line»:«col» in «Agda-package»:Agda.Syntax.Translation.ConcreteToAbstract
```
It seems to use this cached Agda:
```
.stack-work/install/x86_64-linux/496e14715f4d8b6113d6fd3a70d6ff58afee79e74f256eb3a735a6ab54fbbb78/8.10.4/bin/agda
```
which has been generated in the same action run:
```
Installing executable agda in /home/runner/work/agda/agda/.stack-work/install/x86_64-linux/496e14715f4d8b6113d6fd3a70d6ff58afee79e74f256eb3a735a6ab54fbbb78/8.10.4/bin
```

I wonder whether the behavior of `ReduceM` is now specific to the ghc version or the optimization level...

**Comment by nad** [comment]
> I wonder whether the behavior of `ReduceM` is now specific to the ghc version or the optimization level...

Well, the code does use `unsafePerformIO`…

**Comment by andreasabel** [comment]
On my machine with ghc 8.10.4 -O1 the test fails also (same as on CI). 
Succeeds with -O0 (agda-quicker).

**Comment by andreasabel** [comment]
> > I wonder whether the behavior of `ReduceM` is now specific to the ghc version or the optimization level...
> 
> Well, the code does use `unsafePerformIO`…

See https://github.com/agda/agda/issues/5379#issuecomment-840638107 for a MWE.

**Comment by andreasabel** [comment]
I found out that my fixes are sufficient for GHC <= 8.6 and GHC >= 9.0, so a solution to close this issue is to switch CI to a version within this range.  I am now trying GHC 9.0 (see #5372).

**Comment by andreasabel** [comment]
Now all tests pass, this PR is ready to be merged.

**Pull request merged**
