### PR TITLE
[agda2-mode] Use the inheritance attribute when using the 'default-faces

### PR DESCRIPTION
**Pull request by fredefox**

### CODE REVIEW

**Comment by fredefox** [comment]
I think it would also be sensible for `'default-faces` to be the default.

**Comment by UlfNorell** [comment]
Pardon my Elisp illiteracy. What is the purpose and effect of this change? cc @nad

**Comment by fredefox** [comment]
In stead of copying over all the face-attributes deemed to be `agda2-highlight-face-attributes` we just set the `:inherit` attribute to the corresponding face from font lock.

So if e.g. font lock keywords are light blue, then in stead of saying "Agda keywords are lightblue" (which happens to coincide with the font lock setting) we say "Agda keywords inherit face attributes from font lock keywords".

**Comment by fredefox** [comment]
This also happens to be how `haskell-mode` sets its font attributes by default.

**Comment by nad** [comment]
Does this change affect the appearance of code for those who have not made any changes to the Emacs defaults?

**Comment by nad** [comment]
I suppose you could also remove `agda2-highlight-face-attributes` and `agda2-highlight-face-attributes-list`.

**Comment by fredefox** [comment]
> Does this change affect the appearance of code for those who have not made any changes to the Emacs defaults?

No. It also does not change the way it looks if you're using `'default-faces' and haven't configured the fonts further.

> I suppose you could also remove agda2-highlight-face-attributes and agda2-highlight-face-attributes-list.

Yeah that's probably right.

**Comment by fredefox** [comment]
> I suppose you could also remove agda2-highlight-face-attributes and agda2-highlight-face-attributes-list.

I've adressed this now.

**Comment by potato4444** [comment]
Will this effect the fact I use I `custom-set-faces` to set my agda highlighting scheme? I don't understand elisp enough to understand what exactly this change does. Relevent snippet of my `.emacs` below:

```
(let ((base03    "#002b36")
        (base02    "#073642")
        (base01    "#586e75")
        (base00    "#657b83")
        (base0     "#839496")
        (base1     "#93a1a1")
        (base2     "#eee8d5")
        (base3     "#fdf6e3")
        (yellow    "#b58900")
        (orange    "#cb4b16")
        (red       "#dc322f")
        (magenta   "#d33682")
        (violet    "#6c71c4")
        (blue      "#268bd2")
        (cyan      "#2aa198")
        (green     "#859900"))
    (custom-set-faces
     `(agda2-highlight-keyword-face ((t (:foreground ,orange))))
     `(agda2-highlight-string-face ((t (:foreground ,magenta))))
     `(agda2-highlight-number-face ((t (:foreground ,violet))))
     `(agda2-highlight-symbol-face ((((background ,base3)) (:foreground ,base01))))
     `(agda2-highlight-primitive-type-face ((t (:foreground ,blue))))
     `(agda2-highlight-bound-variable-face ((t nil)))
     `(agda2-highlight-inductive-constructor-face ((t (:foreground ,green))))
     `(agda2-highlight-coinductive-constructor-face ((t (:foreground ,yellow))))
     `(agda2-highlight-datatype-face ((t (:foreground ,blue))))
     `(agda2-highlight-field-face ((t (:foreground ,red))))
     `(agda2-highlight-function-face ((t (:foreground ,blue))))
     `(agda2-highlight-module-face ((t (:foreground ,violet))))
     `(agda2-highlight-postulate-face ((t (:foreground ,blue))))
     `(agda2-highlight-primitive-face ((t (:foreground ,blue))))
     `(agda2-highlight-record-face ((t (:foreground ,blue))))
     `(agda2-highlight-dotted-face ((t nil)))
     `(agda2-highlight-operator-face ((t nil)))
     `(agda2-highlight-error-face ((t (:foreground ,red :underline t))))
     `(agda2-highlight-unsolved-meta-face ((t (:background ,base03 :foreground ,yellow))))
     `(agda2-highlight-unsolved-constraint-face ((t (:background ,base03 :foreground ,yellow))))
     `(agda2-highlight-termination-problem-face ((t (:background ,orange :foreground ,base03))))
     `(agda2-highlight-incomplete-pattern-face ((t (:background ,orange :foreground ,base03))))
     `(agda2-highlight-typechecks-face ((t (:background ,cyan :foreground ,base03))))))
```

**Comment by fredefox** [comment]
> Will this effect the fact I use I `custom-set-faces`

Your value for `agda2-highlight-keyword-face` will become e.g.:

```
(agda2-highlight-keyword-face ((t (:foreground orange :inherit font-lock-keyword-face))))
```

The default setting for `font-lock-keyword-face` is:

```
(font-lock-keyword-face ((t (:foreground Cyan1))))
```

So it will not have a visible effect in your case.

**Comment by jespercockx** [comment]
This is rather old, but it could still be merged. Anyone opposed to this?

**Comment by andreasabel** [comment]
I wonder why this PR by an external contributor was just left to sit here after it received comments from HQ, @nad, @UlfNorell ?
We need to make sure such does not happen. Maybe some rotating job as PR responsible?

**Pull request merged**
