### PR TITLE
add ranges to goals in --interaction-json

### PR DESCRIPTION
**Pull request by msuperdock**
Addresses issue #4823.

Each of the functions `encodeOC` and `encodeOCCmp` previously took an argument of type `a -> Value`, where `a` is the second parameter of the type `OutputConstraint`. I've adjusted this type to `a -> TCM Value`, which makes the arguments of `encodeOC` more symmetric, and allows us to pass `encodeTCM` for this argument.

The result is that the `constraintObj` fields of visible and invisible goals will no longer be just a number for visible goals (e.g. `0`) or a string for invisible goals (e.g. `"_0"`), but an object with fields "range" and "id" for visible goals and fields "range" and "name" for invisible goals. In particular, for visible goals this object matches the object found in the "interaction points" response.

### CODE REVIEW

**Comment by msuperdock** [comment]
@ice1000: Maybe you would want to see if you like the resulting JSON structure?

**Comment by rwe** [comment]
Seeing something like a diff of the JSON structure would be pretty useful. Not sure how difficult that is to do: since the build is passing right now, it would appear there are no tests already in place to compare the output?

If I recall correctly, I _think_ @banacorn's [`agda-mode`](https://github.com/banacorn/agda-mode) is the main existing consumer of that protocol and so he might have some thoughts on the changes.

**Review by ice1000 — APPROVED** [review]
Looks good so far

**Comment by banacorn** [comment]
Looks good for me!

@rwe currently neither [agda-mode](https://github.com/banacorn/agda-mode) nor [agda-mode-vscode](https://github.com/banacorn/agda-mode-vscode) is consuming the JSON protocol. I will comeback to this protocol when I'm done with my stuff someday. 

Meanwhile, I think perhaps we should maintain some kind of versioning or CHANGELOG for the protocol. But I'm not sure how do this.

**Review by banacorn — APPROVED** [review]

**Pull request merged**
