### PR TITLE
[ re #1625 ] Rename --experimental-lossy-unification -> --lossy-unification

### LINKED ISSUE #1625: Remove "--experimental" from "--experimental-lossy-unification"
In the [AContext-2.1 Agda sources](http://relmics.mcmaster.ca/RATH-Agda/AContext-2.1.tar.gz)
(available under GPL, linked from [the RATH-Agda page](http://relmics.mcmaster.ca/RATH-Agda/#AContext-2.1)),
there are two modules `Categoric.OCC.CSL.ToFromAContext` and `Categoric.OCC.CSL.FromToAContext`
which each only consist of imports and three lines of the shape:

```
ComposedFunctorName : Functor CatX CatX
ComposedFunctorName = Functor1 functorCompose Functor2

module ComposedFunctorName = Functor ComposedFunctorName
```

Typechecking these is slower than typechecking the whole development these depend on,
and the time is spent on the second line --- commenting out the first and the third line
does not change the typechecking time significantly.
Since the functors in question have previously been typechecked as going from `CatX` to `CatY` respectively vice versa, it is not intuitive that this should take any time at all...

There are more unreasonably slow modules in that package, with more detailed information about the slowness on page 184 of [the accompanying PDF literate document](http://relmics.mcmaster.ca/RATH-Agda/AContext-2.1.pdf). The only update since writing that: For `ToFromAContextNatIso`, 52GB of heap are not sufficient (90 hours).

### PR DESCRIPTION
**Pull request by jespercockx**

### CODE REVIEW

**Comment by plt-amy** [comment]
Bumping the cubical submodule will probably cause CI failures due to #6047. I haven't yet had time to sit down and figure out which, if any, functions matching on formal transports should be marked injective.

**Comment by andreasabel** [comment]
@jespercockx : Thanks for the fix!

As a general rule, when changing Agda syntax (including options), please keep the old syntax as a synonym (+ deprecation warning), if at all feasible.
- #6337

**Comment by jespercockx** [comment]
I personally do not see a reason to go through the deprecation process for an option that is explicitly marked as experimental.

**Comment by andreasabel** [comment]
> I personally do not see a reason to go through the deprecation process for an option that is explicitly marked as experimental.

Yes, same for me, a priori, but then, customers complained anyway...

**Comment by andreasabel** [comment]
> if at all feasible.

This will be very feasible after merging of:
- #6339

**Comment by jespercockx** [comment]
> > I personally do not see a reason to go through the deprecation process for an option that is explicitly marked as experimental.
> 
> Yes, same for me, a priori, but then, customers complained anyway...

I object to the characterization of Agda users as "customers", since no-one here is paying for Agda development (well, except for certain crypto companies...)

**Pull request merged**
