### PR TITLE
[ #4171 ] Exposing constraints to reflection & add delayMacro command.

### PR DESCRIPTION
**Pull request by xekoukou**
Checking for travis output.
Any critique is welcome.

### CODE REVIEW

**Comment by jespercockx** [comment]
Looking good to me. Could you please add a small test case to the test suite?

Edit: please also add the new primitives to the changelog and the user manual.

**Comment by xekoukou** [comment]
There are some bugs that I have fixed in my local repo. 

My main problem at the moment is that it seems that the constraints are introduced after the macro is executed. You can verify this by looking at the debug output of this example : 

```agda
{-# OPTIONS --verbose tc.constr:1000 #-}
module test3 where

open import Agda.Builtin.Reflection
open import Prelude.Nat
open import Prelude.Unit
open import Prelude.List
open import Prelude.Equality

q : Nat → Nat
q zero = 4
q (suc x) = 4


macro
  mfun : Term → TC ⊤
  mfun hole
       = do
           unify hole (def (quote q) [])



g : (Q : Nat → Nat) → ∀ k → Q k ≡ 4
g = {!!}

f : ∀ k → q k ≡ 4
f k = g {!mfun!} k

```

**Comment by xekoukou** [comment]
I added a delay command. Next, I will add tests and documentation.

**Comment by xekoukou** [comment]
This seems ready.

With regards to the `delayMacro` command, macros are kept in a variable and are executed at the end of the typechecking of a Declaration as long as we are not inside a mutual block.

When the Declaration is a section, this might not be the correct behavior. It might be better to wait till all Declarations of a section have been typechecked before executing the macros.

I opted for the simplest solution and we could change the behavior if the above functionality is useful.

**Comment by xekoukou** [comment]
My main concern with this exposure of constraints is that I have omitted to expose its Closure, the context under which the term is valid.
A term from a constraint for example could require a change of its de bruijn indexes to work, and that would require to know the number of variables present in its closure and compare them with those of the current context.

For this reason, I think that we might have to also expose the context of the constraint in some way.

**Comment by xekoukou** [comment]
I added a closure data type. If there is agreement in this direction, I will also update the documentation / changelog and add a test case.

**Comment by jespercockx** [comment]
I think this should be merged after the release of 2.6.1 so we can test it out before releasing it into the wild.

**Comment by asr** [comment]
It could be merge into `master`. I'll release from the frozen `release-2.6.1` branch.

**Comment by xekoukou** [comment]
Keep in mind that there are unsolved questions, as in what we do with the Scope(#4388).

Also, there seems to be a bug which is related to the "delayMacro".
Informally and not very precisely, depending on which file is the main file that is typechecked , the typechecking information that is obtained by the macro is lost. I haven't managed to understand why this is the case.

I will be able to work on agda on the start of the summer and forward.

**Comment by jespercockx** [comment]
@xekoukou is there any progress to report since your last comment?

**Comment by xekoukou** [comment]
Unfortunately, not. Do not merge.

**Pull request closed without merging**
