### PR TITLE
fix instructions for Installation of the Development Version

### PR DESCRIPTION
**Pull request by halfaya**

### CODE REVIEW

**Comment by asr** [comment]
The current documentation is the "Agda User Manual, Release X.Y.Z", so instructions for installing the upstream version shouldn't be in the user manual, but elsewhere. I suggest to add these instructions in the [Wiki](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.Download).

**Review by asr — COMMENTED** [review]
The current documentation is the "Agda User Manual, Release X.Y.Z", so instructions for installing the upstream version shouldn't be in the user manual, but elsewhere. I suggest to add these instructions in the [Wiki](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.Download).

**Comment by halfaya** [comment]
These instructions were already in the user manual--I was merely correcting a mistake. I personally think they are fine in the manual--it's an easy location to find the instructions. I'd like to get rid of the various wiki pages many of which are outdated, and have a single unified source for information, which would be the user manual.

**Comment by asr** [comment]
> I was merely correcting a mistake.

You are right.

Please close this PR and create a new one using the `stable-2.5` branch.

**Comment by halfaya** [comment]
Yes, thanks, I am at AIM now and was told I need to do the PR against stable. Closing.

**Pull request closed without merging**
