### PR TITLE
add fixity change howto to Precedence

### LINKED ISSUE #4538: changing the predefined precedence of an operator
I am reading the documentation about [Precedence](https://agda.readthedocs.io/en/v2.6.1/language/mixfix-operators.html#precedence) but i don't find this. Is it possible to change the precedence of an operator once imported?

Example, this does not seem to work:
```agda
open import Agda.Builtin.Sigma using (_,_)
infix 3 _,_
```

### PR DESCRIPTION
**Pull request by pnlph**
Issue #4538 add to user-manual

### CODE REVIEW

**Comment by gallais** [comment]
Thank you!

**Comment by andreasabel** [comment]
Travis is broken by this PR.
@gallais : Unluckily, the `2 of 3 checks passed` wasn't a false alarm here. 

The problem is:
```
No module M in scope
when scope checking the declaration
open M using (_\8729_)
```

**Comment by gallais** [comment]
Every time I let my guard down I get bitten. :sob:
Thanks for the heads up!

**Comment by pnlph** [comment]
@andreasabel thanks also and sorry about the headache! I did not know that the examples in the docs would typecheck also.

@gallais How should I rename the module? Or do you want to edit the PR directly?

**Comment by gallais** [comment]
I've already pushed a fix: https://github.com/agda/agda/commit/5b90d40f34e653e611fd54a752f845b31218a861

**Comment by andreasabel** [comment]
> Every time I let my guard down I get bitten. 😭

I also had to acknowledge that I am unable to correctly predict when test suites could fail.  My workflow (unless I want to make a PR) is now always:
```
git push origin master:issueNNNN
# wait for actions and travis to ok
git push 
```

**Pull request merged**
