### PR TITLE
Pretty-print constraints in JSON interaction

### PR DESCRIPTION
**Pull request by ashinkarov**
When calling `Cmd_constraints` via json-interaction, one gets Haskell values in JSON.

Without the fix

```
JSON> IOTCM "/tmp/y.agda" NonInteractive Indirect ( Cmd_constraints )

{"info":{"constraints":[{"range":[],"constraint":{"comparison":"CmpEq","kind":"CmpInType","constraintObjs":["App NoRange (OpApp (Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6015, posLine = 203, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6018, posLine = 203, posCol = 4}}])) (QName (Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6015, posLine = 203, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6018, posLine = 203, posCol = 4}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215\"]})) (fromList [Name {nameId = NameId 288 (ModuleNameHash 9835399560186697556), nameConcrete = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6476, posLine = 219, posCol = 17}, iEnd = Pn {srcFile = (), posPos = 6477, posLine = 219, posCol = 18}},Interval {iStart = Pn {srcFile = (), posPos = 6480, posLine = 219, posCol = 21}, iEnd = Pn {srcFile = (), posPos = 6481, posLine = 219, posCol = 22}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215\"]}, nameCanonical = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6015, posLine = 203, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6018, posLine = 203, posCol = 4}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215\"]}, nameBindingSite = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6015, posLine = 203, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6018, posLine = 203, posCol = 4}}]), nameFixity = Fixity' {theFixity = Fixity {fixityRange = NoRange, fixityLevel = Unrelated, fixityAssoc = NonAssoc}, theNotation = [], theNameRange = NoRange}, nameIsRecordName = False}]) [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"x\" :| []}))))}}]) (Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = Paren NoRange (App NoRange (OpApp (Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6046, posLine = 204, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6050, posLine = 204, posCol = 5}}])) (QName (Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6046, posLine = 204, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6050, posLine = 204, posCol = 5}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215s\"]})) (fromList [Name {nameId = NameId 290 (ModuleNameHash 9835399560186697556), nameConcrete = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6483, posLine = 219, posCol = 24}, iEnd = Pn {srcFile = (), posPos = 6484, posLine = 219, posCol = 25}},Interval {iStart = Pn {srcFile = (), posPos = 6487, posLine = 219, posCol = 28}, iEnd = Pn {srcFile = (), posPos = 6489, posLine = 219, posCol = 30}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215s\"]}, nameCanonical = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6046, posLine = 204, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6050, posLine = 204, posCol = 5}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215s\"]}, nameBindingSite = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6046, posLine = 204, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6050, posLine = 204, posCol = 5}}]), nameFixity = Fixity' {theFixity = Fixity {fixityRange = NoRange, fixityLevel = Unrelated, fixityAssoc = NonAssoc}, theNotation = [], theNameRange = NoRange}, nameIsRecordName = False}]) [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (OpApp (Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 1840, posLine = 75, posCol = 38}, iEnd = Pn {srcFile = (), posPos = 1841, posLine = 75, posCol = 39}}])) (QName (Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 1235, posLine = 55, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 1237, posLine = 55, posCol = 3}}]), nameInScope = InScope, nameNameParts = Hole :| [Id \"^\"]})) (fromList [Name {nameId = NameId 70 (ModuleNameHash 9835399560186697556), nameConcrete = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 1840, posLine = 75, posCol = 38}, iEnd = Pn {srcFile = (), posPos = 1841, posLine = 75, posCol = 39}}]), nameInScope = InScope, nameNameParts = Hole :| [Id \"^\"]}, nameCanonical = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 1235, posLine = 55, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 1237, posLine = 55, posCol = 3}}]), nameInScope = InScope, nameNameParts = Hole :| [Id \"^\"]}, nameBindingSite = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 1235, posLine = 55, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 1237, posLine = 55, posCol = 3}}]), nameFixity = Fixity' {theFixity = Fixity {fixityRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 301, posLine = 10, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 307, posLine = 10, posCol = 7}},Interval {iStart = Pn {srcFile = (), posPos = 308, posLine = 10, posCol = 8}, iEnd = Pn {srcFile = (), posPos = 310, posLine = 10, posCol = 10}},Interval {iStart = Pn {srcFile = (), posPos = 311, posLine = 10, posCol = 11}, iEnd = Pn {srcFile = (), posPos = 313, posLine = 10, posCol = 13}}]), fixityLevel = Related 15.0, fixityAssoc = LeftAssoc}, theNotation = [], theNameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 311, posLine = 10, posCol = 11}, iEnd = Pn {srcFile = (), posPos = 313, posLine = 10, posCol = 13}}])}, nameIsRecordName = False}]) [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"\\947\" :| []}))))}}]))}}]) (Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = Paren NoRange (OpApp NoRange (QName (Name {nameRange = NoRange, nameInScope = InScope, nameNameParts = Hole :| [Id \",\",Hole]})) (fromList [Name {nameId = NameId 32 (ModuleNameHash 15581396396021577314), nameConcrete = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6419, posLine = 217, posCol = 26}, iEnd = Pn {srcFile = (), posPos = 6420, posLine = 217, posCol = 27}}]), nameInScope = InScope, nameNameParts = Hole :| [Id \",\",Hole]}, nameCanonical = Name {nameRange = NoRange, nameInScope = InScope, nameNameParts = Hole :| [Id \",\",Hole]}, nameBindingSite = Range (Just (AbsolutePath {textPath = \"/home/tema/.cabal/share/x86_64-linux-ghc-8.10.7/Agda-2.6.3/lib/prim/Agda/Builtin/Sigma.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 209, posLine = 8, posCol = 15}, iEnd = Pn {srcFile = (), posPos = 212, posLine = 8, posCol = 18}}]), nameFixity = Fixity' {theFixity = Fixity {fixityRange = NoRange, fixityLevel = Related 4.0, fixityAssoc = RightAssoc}, theNotation = [], theNameRange = NoRange}, nameIsRecordName = False}]) [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"x\\8321\" :| []}))))}},Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"x\\8322\" :| []}))))}}])}}))}})","App NoRange (App NoRange (App NoRange (QuestionMark (Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6715, posLine = 225, posCol = 34}, iEnd = Pn {srcFile = (), posPos = 6716, posLine = 225, posCol = 35}}])) (Just 0)) (Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = Substitution, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Just (WithOrigin {woOrigin = Inserted, woThing = Ranged {rangeOf = NoRange, rangedThing = \"i\"}}), namedThing = Ident (QName (Name {nameRange = NoRange, nameInScope = InScope, nameNameParts = Id \"i1\" :| []}))}})) (Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = Substitution, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Just (WithOrigin {woOrigin = Inserted, woThing = Ranged {rangeOf = NoRange, rangedThing = \"\\961\"}}), namedThing = Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"x\\8321\" :| []}))}})) (Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = Substitution, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Just (WithOrigin {woOrigin = Inserted, woThing = Ranged {rangeOf = NoRange, rangedThing = \"x\"}}), namedThing = Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"x\\8322\" :| []}))}})"],"type":"OpApp (Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 5893, posLine = 195, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 5897, posLine = 195, posCol = 5}}])) (QName (Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 5893, posLine = 195, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 5897, posLine = 195, posCol = 5}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215t\"]})) (fromList [Name {nameId = NameId 276 (ModuleNameHash 9835399560186697556), nameConcrete = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 5945, posLine = 197, posCol = 24}, iEnd = Pn {srcFile = (), posPos = 5946, posLine = 197, posCol = 25}},Interval {iStart = Pn {srcFile = (), posPos = 5950, posLine = 197, posCol = 29}, iEnd = Pn {srcFile = (), posPos = 5952, posLine = 197, posCol = 31}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215t\"]}, nameCanonical = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 5893, posLine = 195, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 5897, posLine = 195, posCol = 5}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215t\"]}, nameBindingSite = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 5893, posLine = 195, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 5897, posLine = 195, posCol = 5}}]), nameFixity = Fixity' {theFixity = Fixity {fixityRange = NoRange, fixityLevel = Unrelated, fixityAssoc = NonAssoc}, theNotation = [], theNameRange = NoRange}, nameIsRecordName = False}]) [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"\\963\" :| []}))))}}]"},"problems":[],"unblocker":{"kind":"UnblockOnMeta","meta":{"id":2330,"module":9835399560186697556}}},{"range":[],"constraint":{"comparison":"CmpEq","kind":"CmpInType","constraintObjs":["App NoRange (OpApp (Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6015, posLine = 203, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6018, posLine = 203, posCol = 4}}])) (QName (Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6015, posLine = 203, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6018, posLine = 203, posCol = 4}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215\"]})) (fromList [Name {nameId = NameId 288 (ModuleNameHash 9835399560186697556), nameConcrete = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6410, posLine = 217, posCol = 17}, iEnd = Pn {srcFile = (), posPos = 6411, posLine = 217, posCol = 18}},Interval {iStart = Pn {srcFile = (), posPos = 6414, posLine = 217, posCol = 21}, iEnd = Pn {srcFile = (), posPos = 6415, posLine = 217, posCol = 22}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215\"]}, nameCanonical = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6015, posLine = 203, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6018, posLine = 203, posCol = 4}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215\"]}, nameBindingSite = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6015, posLine = 203, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6018, posLine = 203, posCol = 4}}]), nameFixity = Fixity' {theFixity = Fixity {fixityRange = NoRange, fixityLevel = Unrelated, fixityAssoc = NonAssoc}, theNotation = [], theNameRange = NoRange}, nameIsRecordName = False}]) [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"x\" :| []}))))}}]) (Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = Paren NoRange (OpApp NoRange (QName (Name {nameRange = NoRange, nameInScope = InScope, nameNameParts = Hole :| [Id \",\",Hole]})) (fromList [Name {nameId = NameId 32 (ModuleNameHash 15581396396021577314), nameConcrete = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6419, posLine = 217, posCol = 26}, iEnd = Pn {srcFile = (), posPos = 6420, posLine = 217, posCol = 27}}]), nameInScope = InScope, nameNameParts = Hole :| [Id \",\",Hole]}, nameCanonical = Name {nameRange = NoRange, nameInScope = InScope, nameNameParts = Hole :| [Id \",\",Hole]}, nameBindingSite = Range (Just (AbsolutePath {textPath = \"/home/tema/.cabal/share/x86_64-linux-ghc-8.10.7/Agda-2.6.3/lib/prim/Agda/Builtin/Sigma.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 209, posLine = 8, posCol = 15}, iEnd = Pn {srcFile = (), posPos = 212, posLine = 8, posCol = 18}}]), nameFixity = Fixity' {theFixity = Fixity {fixityRange = NoRange, fixityLevel = Related 4.0, fixityAssoc = RightAssoc}, theNotation = [], theNameRange = NoRange}, nameIsRecordName = False}]) [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (App NoRange (OpApp (Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6046, posLine = 204, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6050, posLine = 204, posCol = 5}}])) (QName (Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6046, posLine = 204, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6050, posLine = 204, posCol = 5}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215s\"]})) (fromList [Name {nameId = NameId 290 (ModuleNameHash 9835399560186697556), nameConcrete = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6483, posLine = 219, posCol = 24}, iEnd = Pn {srcFile = (), posPos = 6484, posLine = 219, posCol = 25}},Interval {iStart = Pn {srcFile = (), posPos = 6487, posLine = 219, posCol = 28}, iEnd = Pn {srcFile = (), posPos = 6489, posLine = 219, posCol = 30}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215s\"]}, nameCanonical = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6046, posLine = 204, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6050, posLine = 204, posCol = 5}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215s\"]}, nameBindingSite = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6046, posLine = 204, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 6050, posLine = 204, posCol = 5}}]), nameFixity = Fixity' {theFixity = Fixity {fixityRange = NoRange, fixityLevel = Unrelated, fixityAssoc = NonAssoc}, theNotation = [], theNameRange = NoRange}, nameIsRecordName = False}]) [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"\\947\" :| []}))))}}]) (Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"x\\8321\" :| []}))}})))}},Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"x\\8322\" :| []}))))}}])}})","App NoRange (App NoRange (App NoRange (QuestionMark (Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 6715, posLine = 225, posCol = 34}, iEnd = Pn {srcFile = (), posPos = 6716, posLine = 225, posCol = 35}}])) (Just 0)) (Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = Substitution, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Just (WithOrigin {woOrigin = Inserted, woThing = Ranged {rangeOf = NoRange, rangedThing = \"i\"}}), namedThing = Ident (QName (Name {nameRange = NoRange, nameInScope = InScope, nameNameParts = Id \"i0\" :| []}))}})) (Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = Substitution, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Just (WithOrigin {woOrigin = Inserted, woThing = Ranged {rangeOf = NoRange, rangedThing = \"\\961\"}}), namedThing = Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"x\\8321\" :| []}))}})) (Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = Substitution, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Just (WithOrigin {woOrigin = Inserted, woThing = Ranged {rangeOf = NoRange, rangedThing = \"x\"}}), namedThing = Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"x\\8322\" :| []}))}})"],"type":"OpApp (Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 5893, posLine = 195, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 5897, posLine = 195, posCol = 5}}])) (QName (Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 5893, posLine = 195, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 5897, posLine = 195, posCol = 5}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215t\"]})) (fromList [Name {nameId = NameId 276 (ModuleNameHash 9835399560186697556), nameConcrete = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 5945, posLine = 197, posCol = 24}, iEnd = Pn {srcFile = (), posPos = 5946, posLine = 197, posCol = 25}},Interval {iStart = Pn {srcFile = (), posPos = 5950, posLine = 197, posCol = 29}, iEnd = Pn {srcFile = (), posPos = 5952, posLine = 197, posCol = 31}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215t\"]}, nameCanonical = Name {nameRange = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 5893, posLine = 195, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 5897, posLine = 195, posCol = 5}}]), nameInScope = InScope, nameNameParts = Id \"\\10214\" :| [Hole,Id \"\\10215t\"]}, nameBindingSite = Range (Just (AbsolutePath {textPath = \"/tmp/y.agda\"})) (fromList [Interval {iStart = Pn {srcFile = (), posPos = 5893, posLine = 195, posCol = 1}, iEnd = Pn {srcFile = (), posPos = 5897, posLine = 195, posCol = 5}}]), nameFixity = Fixity' {theFixity = Fixity {fixityRange = NoRange, fixityLevel = Unrelated, fixityAssoc = NonAssoc}, theNotation = [], theNameRange = NoRange}, nameIsRecordName = False}]) [Arg {argInfo = ArgInfo {argInfoHiding = NotHidden, argInfoModality = Modality {modRelevance = Relevant, modQuantity = Quantityω QωInferred, modCohesion = Continuous}, argInfoOrigin = UserWritten, argInfoFreeVariables = UnknownFVs, argInfoAnnotation = Annotation {annLock = IsNotLock}}, unArg = Named {nameOf = Nothing, namedThing = NoPlaceholder Nothing (Ordinary (Ident (QName (Name {nameRange = NoRange, nameInScope = NotInScope, nameNameParts = Id \"\\963\" :| []}))))}}]"},"problems":[],"unblocker":{"kind":"UnblockOnMeta","meta":{"id":2330,"module":9835399560186697556}}}],"kind":"Constraints"},"kind":"DisplayInfo"}

```

With the fix, the output looks as expected.

```
JSON> IOTCM "/tmp/y.agda" NonInteractive Indirect ( Cmd_constraints )


{"info":{"constraints":[{"range":[],"constraint":{"comparison":"CmpEq","kind":"CmpInType","constraintObjs":["⟦ x ⟧ (⟦ γ ^ ⟧s (x₁ , x₂))","?0 (i = i1) (ρ = x₁) (x = x₂)"],"type":"⟦ σ ⟧t"},"problems":[],"unblocker":{"kind":"UnblockOnMeta","meta":{"id":2330,"module":9835399560186697556}}},{"range":[],"constraint":{"comparison":"CmpEq","kind":"CmpInType","constraintObjs":["⟦ x ⟧ (⟦ γ ⟧s x₁ , x₂)","?0 (i = i0) (ρ = x₁) (x = x₂)"],"type":"⟦ σ ⟧t"},"problems":[],"unblocker":{"kind":"UnblockOnMeta","meta":{"id":2330,"module":9835399560186697556}}}],"kind":"Constraints"},"kind":"DisplayInfo"}

```

### CODE REVIEW

**Comment by andreasabel** [comment]
@msuperdock @rwe @isovector @ice1000 Any comments, approval?

**Review by isovector — APPROVED** [review]
lgtm

**Comment by ice1000** [comment]
I have no comment, I don't understand relevant code. Would rather stay silent

**Comment by rwe** [comment]
Sorry, I've been out on other things! This looks reasonable to me.

**Pull request merged**
