### PR TITLE
Tried to optimise checkArgumentsE'

### LINKED ISSUE #6097: Optimise checkArgumentsE'
This issue is related to issue #5983. I tried to see what makes Agda slow for code of the following form, where the number of arguments is *n*:
```agda
postulate
  F : Set₁ → … → Set₁

_ = F Set … Set
```
Some observations:
* In the following code `n` is *n*, *n-1* and so on down to *1*:
  https://github.com/agda/agda/blob/27ea7f2207c25d6f68387c264aaed9ffc1a733e8/src/full/Agda/TypeChecking/Rules/Application.hs#L653-L660
  However, in this case the code does not do anything useful, the following tests always fail (the target type, `Set₁`, is not treated as rigid):
  https://github.com/agda/agda/blob/27ea7f2207c25d6f68387c264aaed9ffc1a733e8/src/full/Agda/TypeChecking/Rules/Application.hs#L682-L686
  I tried to replace this part of the code with `chk' <- return chk`, and obtained a massive performance improvement for large *n*. However, not surprisingly the test suite did not pass. How can this be fixed?
  * I would assume that it makes sense to treat more types as rigid, including `Set₁`:
    https://github.com/agda/agda/blob/27ea7f2207c25d6f68387c264aaed9ffc1a733e8/src/full/Agda/TypeChecking/Rules/Application.hs#L661-L674
    When I added a special case for `Setᵢ` for fixed `i` I obtained a massive performance improvement for large *n*. @UlfNorell, you wrote the first version of that code. Would it make sense to return `True` more often?
  * However, some types are not rigid. Can the information be cached in some way?
    * There is no need to recompute `n`.
    * The code `all visible args0` does not need to be run repeatedly, one can find all suffixes that satisfy the predicate in linear time (if `visible` is *O(1)*).
    * What can be done about `telViewUpTo n t0'`? Perhaps it would make sense to replace the `t0` argument of `checkArgumentsE'` with a `TelView`, and work with that instead of the current `Type`. Then one can also cache `all visible (telToList tel)`. (But note that `size tel` is not necessarily `n`.)
    * I guess that `n` could be `size tel` in the definition of `dep` (#6096), and I suppose that one could cache the set of free variables less than `size tel`.
* The following call to `absApp` is benign in this case, because all the abstractions (`b`) are `NoAbs` abstractions:
  https://github.com/agda/agda/blob/27ea7f2207c25d6f68387c264aaed9ffc1a733e8/src/full/Agda/TypeChecking/Rules/Application.hs#L727
  In the case of `Abs` abstractions Agda would have repeatedly substituted `Set` for variable 0 in shorter and shorter (possibly modified) "tails" of the type of `F`. I wonder if this potential problem could also be alleviated through the use of a `TelView`, perhaps the substitutions could be combined before they are applied to individual elements of the `TelView`.

### PR DESCRIPTION
**Pull request by nad**
Closes #6097.
- #6097

### CODE REVIEW

**Comment by nad** [comment]
What do you think about the change to the `Term` type (or the other changes)?

**Comment by UlfNorell** [comment]
The `Pi` change looks sensible in principle, although my experiences using pattern synonyms with the completeness checker are not very good. Why did you have to move the `Pi` cases around? What happens if you don't?

Since this is kind of invasive, it would also be nice to have some concrete numbers on what we gain by this.

**Comment by nad** [comment]
> The `Pi` change looks sensible in principle, although my experiences using pattern synonyms with the completeness checker are not very good.

I turned off the completeness checker for GHC 8.8 and below. For GHC 8.10 to 9.4 the completeness checker does not complain.

> Why did you have to move the `Pi` cases around? What happens if you don't?

That was an experiment. I noticed that GHC might generate better code if you put the `Pi` cases last, but (as expected) the performance difference seems to be very small, so I don't think we need to worry about the order of the clauses. Here is some more discussion:

https://github.com/agda/agda/blob/e2b712b565f99a13d7285c5bb04dd7a23a743a12/src/full/Agda/Syntax/Internal.hs#L378-L415

> Since this is kind of invasive, it would also be nice to have some concrete numbers on what we gain by this.

For some contrived test cases (`test/Succeed/Issue6097-N.agda`) the gain is massive. For the standard library up to and including `Data.Nat` (and Agda compiled without `-foptimise-heavily`) the changes seem to be small, but the numbers are noisy, and I have not used something like criterion or Stabilizer. Perhaps you get a small performance improvement for `Data.Nat` if you stop before the switch from `Pi` to `Tel`.

Currently the only piece of the type-checker that takes advantage of `Tel` is `checkArgumentsE'`, for the rest of the code I would expect a small overhead due to the use of the pattern synonym `Pi`. Perhaps other parts of the code can also make use of the new representation of Π's to avoid recomputing things, but that requires switching from the telescopes returned by `telView` to telescopes that include both `Abs` and `NoAbs`. In the case of `checkArgumentsE'` this switch paid off because `telViewUpTo` was sometimes applied to a Π, then to an instantiated codomain of the Π, and so on (and the results are now preserved because the result of `termToTel` can easily be turned into a `Term` for the next iteration of the loop). I don't know if other parts of the code do similar things.

**Comment by nad** [comment]
I ran some experiments for a larger project with Agda compiled using GHC 9.4.2 with `-foptimise-heavily` on and the run-time options `+RTS -M4G -s`. Unfortunately you can get rather different numbers when you rerun a test: for one of the tests below the difference between two of the runs is almost a minute. Furthermore it [might](https://curtsinger.cs.grinnell.edu/files/stabilizer_slides.pdf) be the case that changes to how the code is laid out in memory could affect its performance. For these reasons it can be hard to interpret the following numbers (I've listed the user times, as reported by `time`):

* Before a sequence of potential optimisations (fff069926): 738-771 s (three runs).

* Some commits that are part of that sequence:

  * 29cac08e8: 750-792 s (three runs).
  * 42820f191: 735-794 s (three runs).
  * 1cfe553a7: 748-788 s (three runs).
  * 54a4b5541: 724-745 s (three runs).
  * b36173cd1: 760-769 s (three runs).
  * 6520d7719: 761-768 s (three runs).
  * 118d4478a: 760-773 s (three runs).
  * 1f2de0786: 788-795 s (three runs).

* The final commit of that sequence (8cb73675e): 784-793 s (three runs).

* The merge commit after that sequence (27ea7f220): 757-779 s (three runs).

* After optimising the support for `-v` (a78ca6ab5): 743-775 s (four runs).

* After fixing #6080 (9296a1193): 752-765 s (four runs).

* After more potential optimisations (d17fc5654): 732-755 s (four runs).

* After more potential optimisations (e3bf58d8b): 729-747 s (four runs).

* Before starting to fix #6097 (most likely 643c72b31): 725-750 s (three runs).

* The first fix of #6097 (f9648a68e): 736-744 s (three runs).

* After switching from `Pi` to `Tel` (becb5c916): 766-776 s (three runs).

I'm not quite sure how to interpret these numbers. I would not be surprised if the switch from `Pi` to `Tel` has led to a slowdown for this project. Most of the potential optimisations mentioned above are aimed at avoiding blowup for atypical code where something is unusually large, and could lead to slowdown for more typical code. Perhaps it would make sense to revert or revise a few of the potential optimisations.

**Comment by andreasabel** [comment]
@nad: Parts of this have been merged.  Do you want to finish the rest for `2.6.4` or shall we bump to `later`?

**Comment by andreasabel** [comment]
No answer, so I bump to 2.6.5.

**Comment by nad** [comment]
I do not currently plan to continue working on this.

**Comment by andreasabel** [comment]
We should do something about
- #5066

**Comment by UlfNorell** [comment]
Superseded by #7171 to address #5066

**Pull request closed without merging**
