### PR TITLE
INJECTIVE pragmas

### PR DESCRIPTION
**Pull request by jespercockx**
This commit adds a new pragma to Agda to mark a specific definition as injective for the pattern matching unifier. It's basically a more flexible version of --injective-type-constructors that can also be used on postulates ect. The main reason why this is a pull request is because I'm not sure about the name of the pragma: maybe the word injective could be confusing to the user, as there is already a similar notion for the _other_ unifier. OTOH, that notion is inferred instead of declared by the user, so maybe that wouldn't be a problem? Suggestions for a better name for the pragma are welcome.

### CODE REVIEW

**Comment by asr** [comment]
I have no the limitations of  `--injective-type-constructor` in the top of my head, but I'm confused because above you wrote

>  It's basically a more flexible version of --injective-type-constructors that can also be used on postulates ect

but in the CHANGELOG you wrote

> This can be used as a more limited version of --injective-type-constructors.

So, is the new pragma more flexible or more limited than `--injective-type-constructors`?

**Comment by asr** [comment]
Is there an example of some expression which doesn't type-check using `--without-K` but it does by adding `INJECTIVE`?

**Comment by jespercockx** [comment]
It's both more limited and more flexible than --injective-type-constructors: it can be used to only mark specific datatypes as injective (instead of all of them at once), and can also be used on other def's like axioms and such. I'll update the notes to make this a bit clearer.

The motivation for adding this feature comes from #1993. It isn't immediately related to `--without-K`, as the problems with `--injective-type-constructors` extend beyond that and also allow one to refute e.g. the excluded middle.

**Comment by Blaisorblade** [comment]
For the record: this PR was merged through 6e65e6f1c9d029bc361fcf845fa76c183eb621b4.

**Pull request closed without merging**
