### PR TITLE
Revert 5837

### LINKED ISSUE #5837: Occurs check does not properly handle singleton type
I encountered this issue while working on a possible solution for https://github.com/agda/agda/issues/5703. Consider the following example:
```agda
open import Agda.Builtin.Unit
open import Agda.Builtin.Equality

postulate
  F : Set → ⊤
  G : ⊤ → Set

mutual
  X : Set
  X = _

  solve : {Y : Set} → X ≡ G (F Y)
  solve = refl

{- ERROR:
Cannot instantiate the metavariable _5 to solution G (F Y)
since it contains the variable Y
which is not in scope of the metavariable
when checking that the expression refl has type X ≡ G (F Y)
-}
```
Here we get a hard error, even though eta-expanding `F Y` to `tt` leads to a valid solution. The problem is that the occurs check currently only considers singleton types for variables, but not for general expressions containing variables such as `F Y`.

To solve this properly, it seems like we might have to make the occurs check typed, and at every position consider whether the type is actually a singleton type so we can eta-expand the term away. Or perhaps it would be sufficient to do it for `Def`s and `MetaV`s, since these are the only ones where there's actually a chance that the type is a singleton type.

### LINKED ISSUE #6535: Type checker performance regression surfacing in `cubical`
The `cubical` library has balooned to a checking time of 40-50 minutes in CI, see e.g. https://github.com/agda/agda/actions/runs/4431902203/jobs/7775631935.
This seems unsustainable. We need to find a solution.

### PR DESCRIPTION
**Pull request by jespercockx**
This PR reverts the type-directed occurs checker, which fixed !! #5837 but caused a major performance regression. It also includes a number of small fixes and refactorings that I did while trying (unsuccessfully) to improve the performance, but that I believe are worthwhile on their own.

### CODE REVIEW

**Comment by jespercockx** [comment]
How do I unlink this issue from #5837? This PR is not intended to fix that issue, in fact the reverse is true. But Github does not seem to allow me to unlink it.

UPDATE: managed to do it by editing the OP, thanks github :roll_eyes:

**Comment by jespercockx** [comment]
It seems this does not yet fix #6593 or #6594, I'll have to investigate further for those. In the mean time this PR should at least fix the performance issues that the typed occurs check introduced.

**Comment by jespercockx** [comment]
Meta comment: I'm experimenting with [fixup commits](https://github.com/angular/angular/blob/main/docs/FIXUP_COMMITS.md), which should be squashed using `git rebase --autosquash` before merging this PR. I'm not sure if this can be done on github or needs to be done locally though.

**Comment by andreasabel** [comment]
> I'm not sure if this can be done on github or needs to be done locally though.

Googling does not bring up anything, so I assuming you have to do it manually.

**Pull request merged**
