### PR TITLE
[WIP] Python backend

### PR DESCRIPTION
**Pull request by andorp**
Python support for the agda compiler. 
Work in progress, sorry for the noise.

### CODE REVIEW

**Comment by andorp** [comment]
I would like to contribute to agda development. This is an experiment, and luckily the PR landed here. Closing for now. I will create a new PR when everything is working. Sorry for the noise.

**Comment by andorp** [comment]
I will be interested in the maintanence and development of the JS (and maybe Python backend).

**Comment by asr** [comment]
> I will be interested in the maintanence and development of the JS (and maybe Python backend).

This is great! The JS backend needs a maintainer. The current open issues labelled with JS are #684, #1661, #1627 and #1072.

**Comment by andorp** [comment]
> This is great! The JS backend needs a maintainer. The current open issues labelled with JS are #684, #1661, #1627 and #1072.

Thanks, currently I am learning the architecture, mimicing the current behaviour in python. Gradually I will reach the point to start to work on the issues.

**Pull request closed without merging**
