### PR TITLE
[ fix #3187 ] applyFlagsToTCWarnings should respect the new flags (#3193)

### LINKED ISSUE #3187: Acceptable code rejected when -Werror -Wignore is used
Consider the following code:
```agda
open import Agda.Builtin.Bool

F : Bool → Set
F true = Bool
F _    = Bool
```
This code is accepted by Agda, but rejected when `-Werror -Wignore` is used:
```
Exact splitting is enabled, but the following clause could not be
preserved as definitional equalities in the translation to a case
tree:
  F _ = Bool
when checking the definition of F
```
Note that I did not turn on `--exact-split`. Adding `--no-exact-split` to the command line does not help.

### PR DESCRIPTION
**Pull request by gallais**
(cherry picked from commit e54a8e22921397fbb8f7518586d716a215347eff)

### CODE REVIEW

**Comment by gallais** [comment]
There are confusing merge conflicts on the test cases and I can't build this branch
locally because of dependency issues so let's get travis to do the work for us.

**Comment by asr** [comment]
The error in Travis was fixed in master by d57339411566cd02fdb04e1a0b6502b3a6d56264 and cherry-picked in 2.5.4.2 in f4264045b31613899bea6c83258a7520a9a3bfd6, so I'm running Travis again.

**Comment by asr** [comment]
Travis is green, I'll manually merge the PR.

**Comment by asr** [comment]
> I'll manually merge the PR.

Done. @gallais, please remove the branch.

**Pull request closed without merging**
