### PR TITLE
Fix build issue (sphinx v1.4.5) in user-manual

### PR DESCRIPTION
**Pull request by carlostome**
There was a problem (bad alignment) with one of the tables building the documentation with sphinx v1.4.5.

### CODE REVIEW

**Comment by asr** [comment]
Did you get some error message from Sphinx 1.4.5?

I'm asking because I couldn't reproduce the problem in my machine, but I see there is a problem in http://agda.readthedocs.io/en/latest/tools/emacs-mode.html.

**Comment by asr** [comment]
Please close this PR and create a new PR using the stable-2.5 branch.

**Comment by asr** [comment]
Testing the PR I got the following warning:

``` bash
make html
...
Warning, treated as error:
/tmp/agda/doc/user-manual/tools/emacs-mode.rst:203: ERROR: Malformed table.

+----------+-----------+-------------------+-------------+
| Hex code | Character | Short key-binding | TeX command |
+==========+===========+===================+=============+
| 2081     | ``\u2081``     | ``\_1``           |             |
+----------+-----------+-------------------+-------------+
| 2082     | ``\u2082``     | ``\_2``           |             |
+----------+-----------+-------------------+-------------+
| 2083     | ``\u2083``     | ``\_3``           |             |
+----------+-----------+-------------------+-------------+
| 2084     | ``\u2084``     | ``\_4``           |             |
+----------+-----------+-------------------+-------------+
| 2096     | ``\u2096``     | ``\_k``           |             |
+----------+-----------+-------------------+-------------+
| 2098     | ``\u2098``     | ``\_m``           |             |
+----------+-----------+-------------------+-------------+
| 2099     | ``\u2099``     | ``\_n``           |             |
+----------+-----------+-------------------+-------------+
```

**Comment by vlopezj** [comment]
@asr At least [readthedocs.org](http://agda.readthedocs.io/en/latest/tools/emacs-mode.html) renders the table properly now.
However, GitHub's own reStructuredText renderer doesn't now (see [before](https://github.com/agda/agda/blob/79be13d437fb0ae3b4a87d7491d94165c79407ec/doc/user-manual/tools/emacs-mode.rst) and [after](https://github.com/agda/agda/blob/acf4afab4ed47b60329cb27b89fa416cf440aacb/doc/user-manual/tools/emacs-mode.rst)).

It seems to be a matter of which (version of the) reStructuredText parsing library is used.

**Comment by asr** [comment]
This is my version of docutils:

```
~/.local/lib/python2.7/site-packages/docutils-0.12.egg-info
```

Which version are you using?

**Comment by asr** [comment]
[Travis](https://travis-ci.org/agda/agda/jobs/146674748) generated the same warning that I got in my machine. Good :-)

**Comment by carlostome** [comment]
Using Python 3.5.2 I get the following error:

Running Sphinx v1.4.5
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 47 source files that are out of date
updating environment: 47 added, 0 changed, 0 removed
reading sources... [100%] tools/package-system

Warning, treated as error:
/home/carlos/Dev/contrib/agda/doc/user-manual/tools/emacs-mode.rst:201: ERROR: Malformed table.

+----------+-----------+-------------------+-------------+
| Hex code | Character | Short key-binding | TeX command |
+==========+===========+===================+=============+
| 2081     | `\u2081`     | `\_1`           |             |
+----------+-----------+-------------------+-------------+
| 2082     | `\u2082`     | `\_2`           |             |
+----------+-----------+-------------------+-------------+
| 2083     | `\u2083`     | `\_3`           |             |
+----------+-----------+-------------------+-------------+
| 2084     | `\u2084`     | `\_4`           |             |
+----------+-----------+-------------------+-------------+
| 2096     | `\u2096`    | `\_k`           |             |
+----------+-----------+-------------------+-------------+
| 2098     | `\u2098`    | `\_m`           |             |
+----------+-----------+-------------------+-------------+
| 2099     | `\u2099`    | `\_n`           |             |
+----------+-----------+-------------------+-------------+

**Comment by vlopezj** [comment]
Bumping the python version in Travis to 3.5 to match the one that readthedocs.org uses seems to fix the issue. 

https://github.com/agda/agda/pull/2109

I will merge it in as soon as the CI completes.

**Comment by vlopezj** [comment]
Build works again; merged.

**Comment by asr** [comment]
@vlopezj  I confirm that using Python 3.5.2 fix the problem reported [here](https://github.com/agda/agda/pull/2107#issuecomment-234580791). Thanks!

**Comment by asr** [comment]
> Bumping the python version in Travis to 3.5 to match the one that readthedocs.org

How you know that the Python version used by readthedocs.org?

Anyway, bumping the Python version to 3.3 was enough on my machine and Travis ([here](https://travis-ci.org/agda/agda/jobs/146942304) is the Travis job for the commit e7c628b).

**Comment by vlopezj** [comment]
@asr I checked their [build logs](https://readthedocs.org/projects/agda/builds/4230560/) for the name of the directory where the packages are installed.

```
 python /home/docs/checkouts/readthedocs.org/user_builds/agda/envs/stable-2.5/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/agda/.cache/pip sphinx==1.3.5 Pygments==2.1.3 setuptools==20.1.1 docutils==0.12 mkdocs==0.15.0 mock==1.0.1 pillow[...]
Collecting sphinx==1.3.5
  Using cached Sphinx-1.3.5-py2.py3-none-any.whl
Requirement already up-to-date: Pygments==2.1.3 in /home/docs/checkouts/readthedocs.org/user_builds/agda/envs/stable-2.5/lib/python3.4/site-packages
Requirement already up-to-date: setuptools==20.1.1 in /home/docs/checkouts/readthedocs.org/user_builds/agda/envs/stable-2.5/lib/python3.4/site-packages
[...]
```

**Comment by asr** [comment]
I see. Thanks!

**Comment by andreasabel** [comment]
If I do

```
pip3 install sphinx
```

I do not get a new `sphinx-builder` in `.local/bin`.  The closest I get is `rst2html.py` which uses python 3.  My `sphinx-builder` still uses python 2, so `make html` crashes for the documentation.

**Comment by asr** [comment]
I used the following steps for installing Sphinx with Python 3 in Ubuntu 12.04. I _don't know_ if these steps work in a different version of Ubuntu:
1. I removed all the Python 3 packages from the distribution
2. I installed Python 3.5 using [these](http://askubuntu.com/questions/682869/how-do-i-install-newer-python-versions-using-apt-get/682875) instructions
3. I got the `get-pip.py` file from  [here](http://stackoverflow.com/questions/29712519/how-to-use-pip3-with-python-3-4) and I installed in the _user space_ the latest version of `pip` using
   
   ```
   python3.5 get-pip.py --user
   ```
4. Finally, I installed Sphinx using
   
   ```
   agda$ pip install --user -r doc/user-manual/requirements.txt
   ```

**Comment by asr** [comment]
I edited the steps 3 and 4 above.

**Pull request closed without merging**
