### PR TITLE
Revert "fix #7212: Mimer respects C-u modifiers"

### LINKED ISSUE #7212: Mimer doesn't fill with simplified solution
In Agda master-32724f0, Mimer fills the second example with `refl (map (_+_ 1) [])`. Expect both holes to be filled with `refl []` as Agsy does in Agda v2.6.4.3.

```
open import Agda.Builtin.List
open import Agda.Builtin.Nat

map : {X Y : Set} → (X → Y) → List X → List Y
map f []        = []
map f (x ∷ xs)  = f x ∷ map f xs

data _≡_ {A : Set} : A → A → Set where
  refl : (x : A) → x ≡ x

example1 : [] ≡ map (1 +_) []
example1 = {!!}     -- Mimer fills with "refl []"

example2 : map (1 +_) [] ≡ []
example2 = {!!}     -- Mimer fills with "refl (map (_+_ 1) [])"
```

### PR DESCRIPTION
**Pull request by UlfNorell**
This reverts commit 4abc209542404c378541a27a57bded746fe4e68f.

That commits breaks argument passing to Mimer and it requires some elisp wizardry to fix properly, so reverting for now.

See also discussion in #7371.

### CODE REVIEW

**Comment by andreasabel** [comment]
> That commits breaks argument passing to Mimer

What exactly is broken (what is meant by "argument passing")?  Could you post a MWE here?

**Comment by UlfNorell** [comment]
The hole contents is not passed to Mimer anymore, so if you try to give hints or pass options like `-s 1` they are ignored. The problem is in the elisp code which we don't have any way to test at the moment.

**Comment by andreasabel** [comment]
It seems restoring the argument passing (at least for `Cmd_autoOne`) is just a one-word replacement in the elisp code: 
- https://github.com/agda/agda/pull/7423

@UlfNorell Could you evaluate whether PR #7423 fixes the issue?

**Comment by andreasabel** [comment]
So I guess we can close this one...

**Pull request closed without merging**
