### PR TITLE
fix invalid escape character syntax error

### LINKED ISSUE #6525: Recent Emacs's escape character handling improvement leads to an error when loading agda-mode
Like https://github.com/zkry/yaml.el/issues/45, with this commit: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=b8e7061232f9a5b06af70031dcc4b48c6575a364, there is an error when loading agda-mode:

```
Debugger entered--Lisp error: (error "Invalid escape character syntax")
  read(#<buffer  *load*-889718>)
  load-with-code-conversion("/home/vitalyr/.cabal/store/ghc-9.4.4/Agda-2.6.3-4e..." "/home/vitalyr/.cabal/store/ghc-9.4.4/Agda-2.6.3-4e..." nil t)
  require(agda-input)
  load-with-code-conversion("/home/vitalyr/.cabal/store/ghc-9.4.4/Agda-2.6.3-4e..." "/home/vitalyr/.cabal/store/ghc-9.4.4/Agda-2.6.3-4e..." nil t)
  command-execute(agda2-mode record)
  execute-extended-command(nil "agda2-mode" nil)
  funcall-interactively(execute-extended-command nil "agda2-mode" nil)
  command-execute(execute-extended-command)
```
Agda version: 2.6.3
GHC version: 9.4.4
OS: Arch Linux, 6.2.2
Emacs: GNU Emacs 30.0.50, Development version d19416d15c29 on master branch; build date 2023-03-12

### PR DESCRIPTION
**Pull request by VitalyAnkh**
Fix #6525

### CODE REVIEW

**Comment by andreasabel** [comment]
@phikal : Can you have a look?

**Comment by VitalyAnkh** [comment]
May be replaced by #6123.

**Comment by phikal** [comment]
@VitalyAnkh is right that is also part of my proposed changes.

**Comment by VitalyAnkh** [comment]
Closed in favor of @phikal's series of improvements.

**Pull request closed without merging**
