### PR TITLE
Update nix flake; fix a haddock comment

### PR DESCRIPTION
**Pull request by ncfavier**

### CODE REVIEW

**Comment by andreasabel** [comment]
@ncfavier : Thanks for the PR!

@shlevy : Could you please have a look at this change of the nix flake?

**Comment by andreasabel** [comment]
I think atm we do not have an official nix maintainer for Agda.  Volunteers? @ncfavier @shlevy @MatthiasHu

**Comment by ncfavier** [comment]
I volunteer!

**Comment by andreasabel** [comment]
Ok @ncfavier , I invited you to the `agda` organization.

Since you are the maintainer now, you can merge this yourself.  Of course, you can wait for reviews or solicit more reviews/opinions.

When merging something, make sure that individual commits are meaningful and have meaningful commit messages.
In this concrete case, it seems that commits 2&3 should be squashed, I think.

**Comment by andreasabel** [comment]
Perfect, thanks!

**Comment by shlevy** [comment]
Looks good. I'm happy to be a co-maintainer of the Nix code as well if desired.

**Comment by andreasabel** [comment]
@shlevy : Great, I invited you to the `agda` organization as well!

Also here the admonition to pay attention to a good commit history...

**Pull request merged**
