### PR TITLE
Add missing test case

### PR DESCRIPTION
**Pull request by ice1000**
Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>

Add a test case which was originally added in #3313 but possibly deleted by @vlopezj by accident when rebasing my changes.

### CODE REVIEW

**Review by UlfNorell — APPROVED** [review]

**Comment by UlfNorell** [comment]
You now have the power to merge at your own discretion.

**Comment by ice1000** [comment]
> You now have the power to merge at your own discretion.

I know, I just want others to get my code reviewed.

**Comment by ice1000** [comment]
> `s/reserved/preserved/g` ?
> ;)

It's just a test case, let's let it go 😅

**Comment by UlfNorell** [comment]
> I know, I just want others to get my code reviewed.

Yes, submitting a PR is still good practice. I just meant that you should feel free to merge it yourself once people had had a look.

**Pull request merged**
