### PR TITLE
Remove fiddly attempt at instance postponement

### LINKED ISSUE #7295: with-abstraction regression
The following works in agda-2.6.4.3 but fails on master.

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Bool
open import Agda.Builtin.Equality

postulate
  IsPreorder : {A : Set} → (A → A → Set) → (A → A → Set) → Set₁

module NatOrder where
  postulate
    _≤_ : Nat → Nat → Set
    ≤-isPreorder : IsPreorder _≡_ _≤_

module BoolOrder where
  postulate
    _≤_ : Bool → Bool → Set
    ≤-isPreorder : IsPreorder _≡_ _≤_

record HasPreorder (A : Set) (_≈_ : A → A → Set) : Set₁ where
  infix 4 _≤_
  field
    _≤_          : A → A → Set
    ≤-isPreorder : IsPreorder _≈_ _≤_

open HasPreorder ⦃...⦄ public

_∋_ : ∀ {a} (A : Set a) → A → A
A ∋ x = x

instance
  Nat-hasPreorder  = HasPreorder _ _ ∋ record {NatOrder}
  Bool-hasPreorder = HasPreorder _ _ ∋ record {BoolOrder}

data Dec (P : Set) : Set where
  yes : P → Dec P
  no : Dec P

case_of_ : ∀ {A B : Set} → A → (A → B) → B
case x of f = f x

record _⁇ (P : Set) : Set where
  constructor ⁇_
  field dec : Dec P

open _⁇ ⦃...⦄ public

¿_¿ : ∀ (X : Set) → ⦃ X ⁇ ⦄ → Dec X
¿ _ ¿ = dec

instance
  postulate Dec≤ : ∀ {n m : Nat} → (n ≤ m) ⁇

top : Set
top = Nat
  where  -- only fails in a `where` block
    IsGood : (new : Nat) → Set
    IsGood new = 1 ≤ new

    -- case/with over this works:
    -- checkGood : ∀ new → Dec (IsGood new)
    -- checkGood new = ¿ IsGood new ¿

    foo : ∀ new → Bool
    foo new = case ¿ IsGood new ¿ of λ where
      (yes _) → true
      no → true

    bar : ∀ new → foo new ≡ true
    bar new with ¿ IsGood new ¿   -- with-abstraction fails
    ... | yes _ = refl
    ... | no    = refl
```

### PR DESCRIPTION
**Pull request by plt-amy**
Fixes #7295. The deleted code was just an attempt at reducing the amount of instance candidates we'd consider before necessary; it turns out not to have too great an effect to begin with, in addition to being *extra* fiddly, so I'm just going to get rid of it. In addition to the issues with scheduling constraints, it violates the invariant that instance selection should not depend on the discrimination tree returning a minimal set of constraints.

### CODE REVIEW

**Review by UlfNorell — APPROVED** [review]
Thank you!

Do you know why the tests got cancelled?

**Comment by andreasabel** [comment]
Seems to be a (hopefully temporary) problem with GitHub actions:
- https://github.com/actions/runner-images/issues/9959

**Comment by plt-amy** [comment]
Yeah, actions were randomly being skipped in the 1Lab repo too.. I tried to kick them into starting last night, but I guess I'll just do the time-honored approach of pushing a whitespace change to get a CI run. Fwiw, `succeed`, `fail` and `interaction` all passed locally

**Comment by andreasabel** [comment]
Closing and reopening a PR also restarts the checks.

**Comment by plt-amy** [comment]
@andreasabel Nice, thank you! Scary notification to wake up to but I guess GitHub servers have sorted themselves out

**Pull request merged**
