### PR TITLE
Make more flags infective

### PR DESCRIPTION
**Pull request by jespercockx**
This solves the first part of #5264 by making a number of flags infective. Specifically: `--type-in-type`, `--omega-in-omega`, `--injective-type-constructors`, `--experimental-irrelevance`, `--cumulativity`, and `--allow-exec`.

### CODE REVIEW

**Comment by nad** [comment]
I think we should go ahead with this.

**Comment by UlfNorell** [comment]
@jespercockx Any reason this didn't get merged?

**Comment by plt-amy** [comment]
This seems like an unambiguous win to me

**Comment by jespercockx** [comment]
I've updated this to current master, it's ready to merge once CI passes.

**Comment by nad** [comment]
The user manual should also be updated, right?

**Comment by andreasabel** [comment]
Reverted for 2.7.0 in 
- #7406

So, putting the milestone _of this PR_ to `never`, a new PR will be opened for this.

**Pull request merged**
