### PR TITLE
Json serialization

### PR DESCRIPTION
**Pull request by ice1000**
Ported some `EncodeTCM` things from @banacorn's `json` branch, support showing `A.Expr`s, `Rewrite`s, `ComputeMode`s, `Info_GoalSpecific`, `ResponseContextEntry`s, and some more.

This is an initial work for #4183. I'm pull-requesting before every json serialization is finished because I think it's gonna make a too-big PR if I put everything together.

### CODE REVIEW

**Comment by ice1000** [comment]
Can anyone help me with the CI error? It fails with:

```
/home/travis/build/agda/agda/std-lib/src/Data/Nat/Binary/Properties.agda:781,13-29
Could not parse the left-hand side x y
Operators used in the grammar:
  None
when scope checking ∀ _ @ (x y) → x ≤ y + x
 289,295,552,912 bytes allocated in the heap
  40,079,256,576 bytes copied during GC
   1,254,389,240 bytes maximum residency (55 sample(s))
       5,200,392 bytes maximum slop
```

I haven't touched the parser.

**Comment by ice1000** [comment]
Also, another CI task fails with:

```
cabal: Could not resolve dependencies:
[__0] trying: lib-1.2 (user goal)
[__1] next goal: base (dependency of lib)
[__1] rejecting: base-4.13.0.0/installed-4.1... (conflict: lib =>
base>=4.8.0.0 && <4.13)
[__1] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: base, lib)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, lib
```

**Comment by ice1000** [comment]
Seems that these errors happen as well on the master branch.

**Comment by ice1000** [comment]
Relevant people are not likely to review this 😢 I'm merging it.

**Comment by L-TChen** [comment]
I know that @banacorn is currently on holiday, so he won't be able to review it right now.

**Comment by ice1000** [comment]
> I know that @banacorn is currently on holiday, so he won't be able to review it right now.

Ok. I think we have chances to fix what I've done wrong anyway. I also have coming PRs with more serializations and test suites.

**Comment by banacorn** [comment]
Hi I'm back! 

You probably remember pull request https://github.com/agda/agda/pull/3221, where I attempted to serialize `TCErr` along with **all of the concrete syntax tree**. Now the branch is kinda rotting on [my fork](https://github.com/banacorn/agda/tree/json/src/full/Agda/Interaction/JSON), and it's lagging thousands of commits behind. But I'm keeping the branch because I don't want to throw those serializations away.

The current `json` branch on Agda is a fresh reboot. This time I started from removing some of the roadblocks (https://github.com/agda/agda/pull/3811), but I didn't get the time to put the serializations back.

Now it looks like we are back on track!

**Comment by ice1000** [comment]
Cool! Are you cool with the things I committed recently? I did some little serializations, based on your existing work. Note: I didn't expect anyone to get the AST, so I'm serializing the terms by prettifying them as strings.

**Comment by ice1000** [comment]
I didn't yet serialize the context entries (the existing one is dumbly implemented, I believe), and there's many other things to do here

**Comment by ice1000** [comment]
> Note: I didn't expect anyone to get the AST, so I'm serializing the terms by prettifying them as strings.

For passersby: there's https://github.com/banacorn/agda/tree/json/src/full/Agda/Interaction/JSON/Syntax, which is @banacorn serializing the entire AST, which I didn't expect anyone to be brave enough to do so.
(providing information so when 100 years later, archeologists can understand what's going on)

**Review by banacorn — COMMENTED** [review]
LGTM!

**Comment by ice1000** [comment]
I'm sorry that I didn't give you credit for these commits. I was commiting them as authored by ice1000, but most of them come from your codebase.

**Comment by banacorn** [comment]
> I'm sorry that I didn't give you credit for these commits. I was commiting them as authored by ice1000, but most of them come from your codebase.

Nah it's okay

Serializing them bit by bit is the way to go.
Otherwise it will ended up like https://github.com/agda/agda/pull/3221. 
Serializing everything in one fell swoop would be too much for a single PR.

**Comment by ice1000** [comment]
\o/

**Pull request merged**
