### PR TITLE
Add "bump agda2-mode-pkg.el" to release docs

### LINKED ISSUE #2032: Emacs mode should use package.el
Hello,

It would be nice if the Emacs mode was packaged as a package.el package.

Here is a sample `agda2-mode-pkg.el`:

```
(define-package "agda2-mode" "2.5.1"
  "interactive development for Agda, a dependently typed functional programming language")
```

Thanks.

### PR DESCRIPTION
**Pull request by Blaisorblade**
Fix #2032 again: ensure that this file is updated during the release cycle.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
There are yet more copies of that list of files to update, with slight differences. Is it safe to assume all those lists should be the same?

**Comment by asr** [comment]
> Is it safe to assume all those lists should be the same?

Yes.

**Comment by Blaisorblade** [comment]
FWIW the build failure appears related to FTP, not this patch (`traverse` is not found on GHC < 7.10, probably a missing import).

**Comment by andreasabel** [comment]
I am lacking the necessary knowledge to judge this PR. @asr?

**Comment by asr** [comment]
LGTM except that the PR should be based on the stable branch.

**Pull request closed without merging**
