### PR TITLE
[ cubical ] make more arguments implicit in hcomp and Glue

### PR DESCRIPTION
**Pull request by mortberg**
Make the type and formula implicit in `hcomp` and the formula implicit in `Glue`

### CODE REVIEW

**Comment by Saizan** [comment]
Merged with 9a641e3d90efd585bf65d0fa31d38dfab25ae027

**Comment by ice1000** [comment]
Why is this PR merged in this way? All commits by @mortberg are now authored by @Saizan now. It's making git blame difficult.

**Comment by gallais** [comment]
? `git show ee32208a30d4380994739916b1396cb0a42791c1` (visible [here](https://github.com/agda/agda/commit/ee32208a30d4380994739916b1396cb0a42791c1) on github) gives me
"Author: Anders Mörtberg". The 4 commits have been squashed but that's actually good practice.

**Comment by ice1000** [comment]
Oh! It's because the commits are too long ago so it's displayed separately.

image

Sorry for bothering.

**Comment by ice1000** [comment]
It's quite confusing that 9a641e3d90efd585bf65d0fa31d38dfab25ae027 and ee32208a30d4380994739916b1396cb0a42791c1 exist at the same time :sweat_smile:

**Pull request closed without merging**
