### PR TITLE
remove the cubical identity type

### PR DESCRIPTION
**Pull request by plt-amy**
See agda/cubical#1005, the computational behaviour of the builtin `Id` is precisely replicated by the user-definable identity type, so we do not need the duplicated implementation in the builtin.

### CODE REVIEW

**Review by UlfNorell — APPROVED** [review]
🎉

**Comment by andreasabel** [comment]
N.B. Tests for these (non-)issues get removed:
- https://github.com/agda/agda/issues/2846

**Comment by andreasabel** [comment]
There is still the `test/Compiler/simple/Erased-cubical` failing atm: https://github.com/agda/agda/actions/runs/12280884214/job/34269260800?pr=7652#step:16:57

**Comment by andreasabel** [comment]
This needs a CHANGELOG entry labeled as "breaking change".

**Comment by plt-amy** [comment]
@andreasabel is the changelog entry I added sufficient?

**Comment by jamesmckinna** [comment]
How does/might this PR affect those users (eg. of `stdlib`) who, while remaining `cubical-compatible`, do not make any use of `cubical` features?

**Comment by plt-amy** [comment]
It doesn't.

**Comment by andreasabel** [comment]
> @andreasabel is the changelog entry I added sufficient?

Yes, perfect!

**Pull request merged**
