### PR TITLE
Issue2200

### PR DESCRIPTION
**Pull request by identicalsnowflake**
I added trigonometric primitives for Agda in TC and the GHC and JS backends. I don't know anything about UHC so I ignored it. I also updated tests and documentation which referenced the existing `primSin` to include the rest of the new primitives.

### CODE REVIEW

**Comment by asr** [comment]
Please include tests for the GHC and JS backends. Since you ignored the UHC backend, you can add the tests into the `test/Compiler/simple/FloatsUHCFails.agda` file.

**Comment by UlfNorell** [comment]
Nice. Can you make the PR against `stable-2.5` instead of `master`?

**Comment by asr** [comment]
> Can you make the PR against stable-2.5 instead of master?

See https://github.com/blog/2224-change-the-base-branch-of-a-pull-request.

**Comment by asr** [comment]
There is something wrong in the PR. There are many commits that belong to the master branch.

**Comment by asr** [comment]
I just realised that the instructions on

  https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

didn't apply in this case. Sorry!

**Comment by identicalsnowflake** [comment]
So I should move it back to master? Or remake the PR on stable-2.5?

**Comment by asr** [comment]
Please remake it on stable-2.5.

**Comment by UlfNorell** [comment]
I'm closing this so we don't merge it by accident.

**Pull request closed without merging**
