### PR TITLE
Fixed #5611?

### LINKED ISSUE #5611: Standard library `Data.Nat.DivMod` fails with cubical error, even though no `--cubical` is used
Lifted from https://github.com/agda/agda/issues/5605#issuecomment-948912125:
```
/home/runner/work/agda/agda/std-lib/src/Data/Nat/DivMod.agda:205,1-47
Agda.Primitive.Cubical.primTransp
(λ i →
   m /
   Agda.Primitive.Cubical.primComp (λ i₁ → ℕ)
   (λ i₁ .o →
      Agda.Primitive.Cubical.primPOr
      (Agda.Primitive.Cubical.primIMax
       (Agda.Primitive.Cubical.primINeg i) φ)
      i (λ .o₁ → suc m₁) (λ .o₁ → x i₁) _)
   (suc m₁)
   ≤ n / x₁ i)
φ (/-mono-≤ x₂ (s≤s x₃)) is not usable at the required modality
when checking the definition of /-mono-≤
```
I suppose this is a regression in 2.6.3, because the `master` of the std lib is supposed to build with 2.6.2.

### PR DESCRIPTION
**Pull request by nad**

### CODE REVIEW

**Comment by nad** [comment]
The test suite has failed twice now, with the `Could not load module ‘Agda.Version’` error in the interaction tests (see #5753).

**Comment by andreasabel** [comment]
@Mergifyio rebase

**Comment by Saizan** [comment]
Looks good to me, assuming we are right that we only need to check the quantity (Which is not true with `--experimental-irrelevance` but i guess that's just not supported with --cubical then).

Btw, it could make sense to make `usableAtModality` polymorphic on the modality type, so that we could say `usableAtModality (getQuantity mod) rhs` and not get type errors involving irrelevance.

**Review by Saizan — APPROVED** [review]

**Comment by nad** [comment]
> Looks good to me, assuming we are right that we only need to check the quantity (Which is not true with `--experimental-irrelevance` but i guess that's just not supported with --cubical then).

I guess it would make sense to enforce this.

**Comment by nad** [comment]
> I guess it would make sense to enforce this.

We currently allow `--with-K` and `--cubical` (if `--safe` is not used). I would not be surprised if this breaks some internal invariants. I actually use this mode in a README file that imports code that uses `--with-K` as well as code that uses `--cubical`.

As long as this is allowed the additional harm of allowing `--cubical`/`--erased-cubical`/`--cubical-compatible` and `--experimental-irrelevance` (without `--safe`) might not be so large. I suggest that we leave things as they are for the moment.

Any opinions?

**Comment by andreasabel** [comment]
@nad wrote:
> The test suite has failed twice now, with the `Could not load module ‘Agda.Version’` error in the interaction tests (see #5753).

After rebasing to master, CI succeeds now.

**Comment by andreasabel** [comment]
I think we should merge this and see what happens.

**Comment by nad** [comment]
> (Which is not true with `--experimental-irrelevance` but i guess that's just not supported with --cubical then).

Two questions:

* Can one construct an example showing that `--experimental-irrelevance` is incompatible with (postulated) univalence?
* Is the new problem introduced with this commit restricted to univalence (as opposed to other cubical features)?

If both questions can be answered with "yes", then we could state in the documentation that `--experimental-irrelevance` is incompatible with univalence.

**Comment by nad** [comment]
> If both questions can be answered with "yes", then we could state in the documentation that `--experimental-irrelevance` is incompatible with univalence.

I had hoped that I could write the following in the changelog:
```markdown
* The option `--experimental-irrelevance` is now incompatible with
  univalence (see [#5611](https://github.com/agda/agda/issues/5611)
  and [#5861](https://github.com/agda/agda/pull/5861)).

  This is not meant to imply that the option was not already
  incompatible with univalence. Note that `--experimental-irrelevance`
  cannot be used together with `--safe`.
```
And the following in the user manual:
```rst
     Note that :option:`--experimental-irrelevance` is incompatible
     with univalence.
```
Because I don't know the answers to the questions I posed I instead went with the following in the changelog (and nothing in the user manual):
```markdown
* The option `--experimental-irrelevance` is now perhaps incompatible
  with Cubical Agda and perhaps also postulated univalence (see
  [#5611](https://github.com/agda/agda/issues/5611) and
  [#5861](https://github.com/agda/agda/pull/5861)).

  This is not meant to imply that the option was not already
  incompatible with those things. Note that
  `--experimental-irrelevance` cannot be used together with `--safe`.
```
If there was concrete evidence that something can go wrong when `--experimental-irrelevance` is used in Cubical Agda, then we could write something a little less vague.

**Pull request merged**
