### PR TITLE
Build copy inst hooks

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by asr** [comment]
@phadej, please see the Travis errors.

**Comment by phadej** [comment]
The Cabal travis job seems to fail with master also

**Comment by asr** [comment]
I was talking about some errors with some versions of GHC (I don't remember which versions). The Travis test on `master` was fixed and I accidentally restarted the Travis test for this PR. I'm waiting for Travis for pointing out the problems.

**Comment by asr** [comment]
@phadej, you can fix the white-space issues reported by Travis by running

```
make fix-whitespace
```

Let me know when you fixed it.

**Comment by phadej** [comment]
```
 % make fix-whitespace 
stack build fix-agda-whitespace

Error: While constructing the build plan, the following exceptions were encountered:

Unknown package: fix-agda-whitespace

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be convenient when dealing with many complicated constraint
    errors, but results may be unpredictable.


Plan construction failed.
Makefile:395: recipe for target 'build-fix-agda-whitespace' failed
make: *** [build-fix-agda-whitespace] Error 1
```

**Comment by asr** [comment]
Oops, sorry!  Someone tweaked the `Makefile` for working with stack, but we are not testing it. I filed #3573.

While the issue is fixed, could you erase your `stack.yaml` file and try again.

**Comment by phadej** [comment]
I won't run `cabal v1-build` on my machine. (I tested `sandbox` in a docker container I already destroyed), running `make fix-whitespace` is probably easier for you @asr.

**Comment by phadej** [comment]
Travis seems to be green

**Comment by banacorn** [comment]
It seems like the `Makefile` chose to use `stack` instead of `cabal` as the mean of building stuff. It would only happen when a file named `stack.yaml` is present. And the `stack.yaml` is kaput.

**EDIT** @phadej, can I take a look at your `stack.yaml`?

**Comment by asr** [comment]
It seems this PR is a good solution for supporting both Cabal new and legacy commands. Thanks @phadej.

**Pull request merged**
