### PR TITLE
Fix for issue #5765

### PR DESCRIPTION
**Pull request by jespercockx**
Fix for issue #5765. It would be good to get confirmation from @nad that this isn't breaking anything.

### CODE REVIEW

**Comment by nad** [comment]
If the code had been on a branch of the main repository, then I could have obtained the code using `git fetch` and `git checkout Issue5765`. However, the code is on your fork. Can the code be obtained just as easily in this case? I don't want to set up a new remote.

**Comment by jespercockx** [comment]
According to the instructions Github provides, the following should do it (I haven't tested):
```
git checkout -b jespercockx-Issue5765 master
git pull https://github.com/jespercockx/agda.git Issue5765
```

**Comment by nad** [comment]
Thanks. My code seems to work fine with your change in place.

**Comment by andreasabel** [comment]
@mergifyio rebase

**Pull request merged**
