### PR TITLE
Fix #5349: Allow eta-expansion of instance metavariables

### LINKED ISSUE #5349: Instance resolution should not require type annotations in unambiguous situations
It seems that Agda 2.6.1.3 or earlier has introduced a regression with regards to instance resolution.  A whole lot of my code that previously typechecked now needs additional type annotations in situations that do not seem like they should require such annotations.

Arjen confirms the failure happens also in Agda 2.6.2-4f87d39.

```agda
data Type : Set where
  *   : Type
  _⊃_ : Type → Type → Type

record Model : Set₁ where
  field
    W   : Set
    V   : W → Set
    _≤_ : W → W → Set

open Model {{…}}

module Works where
  _⊩_ : ∀ {{M : Model}} → W → Type → Set
  w ⊩ *       = V w
  w ⊩ (A ⊃ B) = ∀ {w′ : W} → w′ ≤ w → w′ ⊩ A → w′ ⊩ B

module UsedToWork where
  _⊩_ : ∀ {{M : Model}} → W → Type → Set
  w ⊩ *       = V w
  w ⊩ (A ⊃ B) = ∀ {w′} → w′ ≤ w → w′ ⊩ A → w′ ⊩ B

{-
_39 : Set  [ at /Users/mietek/Desktop/InstanceResolutionRegression.agda:21,20-22 ]
_r_41 : Model  [ at /Users/mietek/Desktop/InstanceResolutionRegression.agda:21,29-30 ]
_M_47 : Model  [ at /Users/mietek/Desktop/InstanceResolutionRegression.agda:21,38-39 ]
_M_51 : Model  [ at /Users/mietek/Desktop/InstanceResolutionRegression.agda:21,47-48 ]

———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  Resolve instance argument
    _M_47
      : ⦃ M = M₁ : Model ⦄ (w₁ : Model.W M₁) (A₁ B₁ : Type)
        {w′ = w′₁ : _39 (w = w₁) (A = A₁) (B = B₁)} →
        Model
  No candidates yet
  Resolve instance argument
    _r_41
      : ⦃ M = M₁ : Model ⦄ (w₁ : Model.W M₁) (A₁ B₁ : Type)
        {w′ = w′₁ : _39 (w = w₁) (A = A₁) (B = B₁)} →
        Model
  No candidates yet
  Resolve instance argument
    _M_51
      : ⦃ M = M₁ : Model ⦄ (w₁ : Model.W M₁) (A₁ B₁ : Type)
        {w′ = w′₁ : _39 (w = w₁) (A = A₁) (B = B₁)} →
        Model
  No candidates yet
  _39 =< Model.W _M_51
  _39 =< Model.W _M_47
  Model.W M =< Model.W _r_41
  _39 =< Model.W _r_41
-}
```

### PR DESCRIPTION
**Pull request by jespercockx**
Fixes #5349

### CODE REVIEW

**Comment by andreasabel** [comment]
Looks like the `cubical` test times out, so maybe this introduced a loop.

Agda gets stuck at:     
> Checking Cubical.Relation.Binary.Poset

**Comment by jespercockx** [comment]
I unfortunately do not have the time to look at this further so it seems this will have to wait until 2.6.4 after all.

**Comment by jespercockx** [comment]
I'm looking at this again, and there's an interesting message in the debug log:
```
...
{ etaExpandMeta _1422@14973596973578533204
we do not expand meta variable _1422 (requested was expansion of [SingletonRecords,Levels])
}
Debug printing tc.meta.eta:15 failed due to exception:
  An internal error has occurred. Please report this as a bug.
  Location of the error: impossible, called at src/full/Agda/TypeChecking/Rules/LHS.hs:767:95 in Agda-2.6.4-ISoQEJiMwTNBNCkCIkpFcd:Agda.TypeChecking.Rules.LHS
}
```
Seems like the LHS checker is doing something naughty.

**Comment by andreasabel** [comment]
@jespercockx : Do you want to finish this for `2.6.4` or bump to `later`?

**Comment by jespercockx** [comment]
Unlikely I'll have the time, so bumping this.

**Pull request closed without merging**
