### PR TITLE
[ re #5399 #3699 ] Add primitives `tcDeclareData`, `tcDefineData`, and a syntax for declaring top-level datatype definitinons by metaprograms

### PR DESCRIPTION
**Pull request by Zekt**
To define data types by metaprograms, this PR extends the reflection framework with two primitives `declareData`, `defineData` and a new syntax `unquoteDecl data d constructor c1 c2 ... = e`.

In detail, the two primitives 
```agda
declareData : Name → Nat → Type → TC ⊤
```
and
```agda
defineData : Name → List (Σ Name (λ _ → Type)) → TC ⊤
```
in `Agda.Builtin.Reflection` are used to declare and define a datatype respectively similar to `declareDef` and `defineFun`. Note that the type of a constructor does not include the type parameters. The `unquoteDecl data ... constructor ...` introduces names for a datatype and its constructors into the scope. It allows overloaded constructor names but they need to be referred by their fully qualified names.

E.g., 
```agda
open import Agda.Builtin.Reflection
open import Agda.Builtin.Nat
open import Agda.Builtin.Unit
open import Agda.Builtin.Sigma
open import Reflection
open import Data.List

define : Name → Name → TC _
define n c = do
  declareData n 1 (quoteTerm ((A : Set) → Nat → Set))
  defineData n [ (c , pi (vArg (def (quote List) [ vArg (var 0 []) ]))
                         (abs "" (def n (vArg (var 1 [])
                                        ∷ vArg (def (quote length)
                                                    [ vArg (var 0 []) ])
                                        ∷ [])))) ]

unquoteDecl data D constructor C = define D C
unquoteDecl data D' constructor C = define D' D'.C

k : D Nat 0
k = C []
```
declares data types `D` and `D'` that are equivalent to:
```agda
data D (A : Set) : Nat → Set where
  C : (l : List A) → D A (length l)
data D' (A : Set) : Nat → Set where
  C : (l : List A) → D' A (length l)
```

### CODE REVIEW

**Comment by L-TChen** [comment]
This proposed syntax follows the current convention of `unquoteDecl` and `unquoteDef`, but in the presence of overloaded names, it becomes overly verbose and shows why the proposal in https://github.com/agda/agda/issues/5864 is better. 

At worst, if we overload `_∷_` and `[]` to define, say variants of lists, then each of the names needs to be fully qualified. For example, 
```agda
unquoteDecl data Vec constructor [] _∷_ = e Vec (Vec.[] List.∷ Vec._∷_ List.∷ List.[])
```

We may implement this change differently by applying the list of `QName` declared on the left-hand side during type-checking, so there is no need to apply them manually. However, it is not consistent with `unquoteDecl`.

It is very close to the release of 2.6.3, so maybe we (I ?) can still merge this PR while implementing and experimenting https://github.com/agda/agda/issues/5864 afterwards.

**Review by jespercockx — APPROVED** [review]
This looks very good to me! I agree that we should merge this soon and in the meantime look into further developing the more principled but invasive solution

**Comment by jespercockx** [comment]
If @UlfNorell is also fine with this, I think it can be merged as-is.

**Comment by L-TChen** [comment]
It seems that @UlfNorell is currently not active. Maybe someone else (ping @nad, @andreasabel)  would like to have a look before merging?

**Comment by L-TChen** [comment]
I am inclined to merge this PR in 7 days (Aug 15) if no one objects. 😝

**Pull request merged**
