### PR TITLE
Fix for issues #4390 and #4401

### PR DESCRIPTION
**Pull request by jespercockx**
This PR provides a fix for (part of) #4390 and for #4401. 

When solving an equation `_X y1 .. yn =?= v` with `_X := \y1 .. yn -> v`, Agda will now check that the types of `y1 .. yn` are actually equal to the context where `_X` was created, for otherwise `v` might not be well-typed in the context of the meta.

An alternative (more permissive) solution would be to re-check in the context of the metavariable using checkInternal, but this might be too expensive in general. Since it is possible that another constraint will pop up that is created in a less selective context, the current check never produces a hard failure but only unsolved constraints.

Other limitations: the check does not yet include subtyping for sizes, and it also does not handle the "related example" given by Ulf in #4390.

### CODE REVIEW

**Comment by andreasabel** [comment]
Current failure of `std-lib-test`:
```
 Checking Relation.Binary.HeterogeneousEquality.Quotients (/home/travis/build/agda/agda/std-lib/src/Relation/Binary/HeterogeneousEquality/Quotients.agda).

An internal error has occurred. Please report this as a bug.

Location of the error: src/full/Agda/TypeChecking/MetaVars.hs:1142
```
Could turn into a shrinking marathon...

**Comment by jespercockx** [comment]
I've added a missing case for metavariables to the subtyping check, but it seems it's still failing with an internal error on Relation.Binary.HeterogeneousEquality.Quotients. I wonder what's going on here.

**Comment by jespercockx** [comment]
So the main problem with this fix is that it makes some cases of variable generalization fail, because generalizable metas are created in a context with dummy types which my check here doesn't like. I think this is more of a problem with generalization than with the check, and anyway it seems to occur only rarely, so I do not think it is a showstopper.

Another potential problem that I haven't really tested yet is that this test is run for each context variable each time a metavariable is instantiated, which could potentially be a performance problem. I have tried to keep the test itself as quick as possible, but I haven't really done any performance testing yet.

Finally, the current test takes into account subtyping for cumulativity, irrelevance, erasure, and cohesion, but not yet sized types. This could be added by adding the appropriate functionality to the new `checkSubtypeIsEqual` function.

**Comment by jespercockx** [comment]
I tested the performance of this change on the standard library and unfortunately it has quite a negative impact: total time went from 443s to 602s. That does not seem like an acceptable price to pay for fixing a bug that only occurs with certain features (irrelevance, sized types, erasure, cumulativity, cohesion) that are not even used in the standard library. Irrelevance and erasure are turned on by default, so it is not possible either to enable the check only when one of these features is used. So at the moment this PR is dead in the water (as is the release of 2.6.1, I guess).

**Comment by nad** [comment]
Would the problems go away if we removed subtyping?

**Comment by jespercockx** [comment]
> Would the problems go away if we removed subtyping?

Yes.

**Comment by jespercockx** [comment]
Now the check is only run when `--subtyping` is enabled (which it currently is by default), so at least now there's a way to avoid the performance hit by using `--no-subtyping`.

**Comment by gallais** [comment]
> (irrelevance, sized types, erasure, cumulativity, cohesion) that are not even used in the standard library.

We do use [irrelevance](http://agda.github.io/agda-stdlib/Data.Erased.html) & [sized types](http://agda.github.io/agda-stdlib/Data.Tree.Rose.html) (although in very small parts of the lib).

**Comment by jespercockx** [comment]
I've implemented the solution I proposed in #4474. Now we are in the following situation:

- By default `--subtyping` is disabled, which means you do not get any subtyping related to relevances. In particular, you need to eta-expand some functions manually.
- You can get those subtyping rules by enabling the `--subtyping` flag, but you incur a performance hit because of the extra checks.
- When you enable `--cumulativity`, `--subtyping` is also enabled automatically.
- Subtyping for sized types does NOT require `--subtyping` flag and is not handled by the new check even if you enable `--subtyping` manually.

If this seems acceptable, I will write something for the changelog and the user manual and merge it into master.

**Comment by jespercockx** [comment]
It seems `Data.Erased` in the standard library no longer typechecks without `--subtyping`, so we'd have to coordinate a patch to the stdlib together with this one.

EDIT: actually we can already put the `--subtyping` flag in the experimental branch of the library, so there is no dependency on this PR.

**Comment by gallais** [comment]
> EDIT: actually we can already put the --subtyping flag in the experimental branch of the library, so there is no dependency on this PR.

`master` is currently sync'd up with Agda's `master` because we want to release
at the same time as 2.6.1.

That being said, I would much rather fix `Data.Erased` (and `Data.Refinement`
and `Text.Pretty.*`) by eta-expansion if that is possible.

**Comment by nad** [comment]
Here is a test case:
```agda
data _≡_ {A : Set} : A → A → Set where
  refl : (x : A) → x ≡ x

record Erased (A : Set) : Set where
  constructor [_]
  field
    @0 erased : A

open Erased

record _↔_ (A B : Set) : Set where
  field
    to      : A → B
    from    : B → A
    to∘from : ∀ x → to (from x) ≡ x
    from∘to : ∀ x → from (to x) ≡ x

postulate
  A : Set
  P : (B : Set) → (Erased A → B) → Set
  p : (B : Set) (f : Erased A ↔ B) → P B (_↔_.to f)

works : P (Erased (Erased A)) [_]
works =
  p _ (record
         { from    = λ ([ x ]) → [ erased x ]
         ; to∘from = refl
         ; from∘to = λ _ → refl _
         })

fails : P (Erased (Erased A)) (λ (x : Erased A) → [ x ])
fails =
  p _ (record
         { from    = λ ([ x ]) → [ erased x ]
         ; to∘from = refl
         ; from∘to = λ _ → refl _
         })
```
The only difference between `works` and `fails` is that a function has been η-expanded. Currently `works` and `fails` are not handled consistently. Are they handled consistently by the code discussed above (when subtyping is turned on)? Furthermore Agda should not reject `fails`, but complain about unsolved meta-variables, because `fails` is accepted when `from∘to = λ _ → refl _` is replaced by `from∘to = λ _ → refl [ _ ]`. Thus Agda (with subtyping) should either accept both definitions, or complain about unsolved metas for both, but not reject either of them.

**Comment by jespercockx** [comment]
No, they are still not handled consistently after my changes. The problem seems to be orthogonal to the issue handled by this PR, so I will create a separate issue for it.

**Comment by jespercockx** [comment]
I pushed entries for the changelog and user manual. If there are no complaints, I will push this later today.

**Review by UlfNorell — APPROVED** [review]

**Comment by jespercockx** [comment]
Note to self: we need to wait until https://github.com/agda/agda-stdlib/pull/1092 is merged before merging this PR.

**Pull request merged**
