### PR TITLE
Fix compatibility with strict 0.4

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by felixonmars** [comment]
The failures look irrelevant to this change.

**Comment by asr** [comment]
Thanks!

**Comment by asr** [comment]
> The failures look irrelevant to this change.

Well, `strict 0.4` is a dependency of `aeson 1.5.3.0` and the failures are due to this version of `aeson`. Anyway, I'm testing a fix in #4838.

**Comment by felixonmars** [comment]
@asr I just realized it too... Sorry!

**Pull request merged**
