### PR TITLE
Fix GHC 8.10 on Travis

### PR DESCRIPTION
**Pull request by rwe**
This attempts to fix GHC-8.10.2 on Travis by passing the `+RTS -M4G -RTS` options to Stack build when invoked directly. Will it work? Let's see.

In order to do this, I had to fix up a number of unsafely quoted argument/command lists.

### CODE REVIEW

**Comment by rwe** [comment]
Argh. Made it past the compilation phase. But then tripped over accidentally passing `--ghc-options` to `stack path`…let's try again.

**Comment by rwe** [comment]
Ta da!

**Comment by asr** [comment]
Great! Thanks!

Now the `Makefile` and Travis are using `+RTS -M4G -RTS`. I think it is a good idea to add this option to the GitHub workflows. @rwe, could you do it?

**Comment by rwe** [comment]
Yep, I'll take a quick look tomorrow. The fact that wasn't failing there makes me think that the GitHub workers might have more available memory, though I'm not sure how GHC decides the default heap.

**Comment by asr** [comment]
Note that GitHub workflows are not using GHC 8.10.2 because https://github.com/actions/setup-haskell/pull/32.

**Pull request merged**
