### PR TITLE
added contents of wiki for a variety of stubs

### PR DESCRIPTION
**Pull request by drull95**

### CODE REVIEW

**Comment by jespercockx** [comment]
LGTM. It's nice to see the documentation a little more fleshed out. Thank you very much! I'm planning to write some more about pattern matching (dot patterns and absurd patterns), --without-K, and rewriting when I can find the time.

**Comment by phile314** [comment]
I merged the following commits with some edits so far:
- be6084d
- de210a1
- 655b8f5
- 2988bc1
- e80457d
- c419e42

TODO:
- 26ba6be

**Comment by jespercockx** [comment]
So, who decides when this PR can be merged? We shouldn't wait until the merge becomes harder. I can do it if no-one objects.

**Comment by phile314** [comment]
Please don't merge the whole pull-request as is! I already merged some parts of this pull request, but feel free to cherry-pick the commits I haven't yet merged. This pull-request also causes some warnings in the user manual build which should be fixed before or after merging.

I can finish the merge soonish if that's okay with you?

**Comment by jespercockx** [comment]
Ah, I didn't realize there were still issues you are working on. Please ignore my message and continue what you were doing.

**Comment by phile314** [comment]
I merged most things, only one commit left. However, I'm not really up-to-date what the current state of coinduction in Agda is. Can someone take a look at the following commit and tell me if it's more-or-less correct and up-to-date?

https://github.com/agda/agda/commit/26ba6bedb0a892877c2e354ca79330482d844223

**Comment by phile314** [comment]
Everything is merged now.

@drull95 Thanks for the pull request!

**Pull request closed without merging**
