### PR TITLE
Add Markdown support for literate Agda.

### PR DESCRIPTION
**Pull request by ghost**
What do you think? Is it useful?

### CODE REVIEW

**Comment by andreasabel** [comment]
I think it would be useful.
@vlopezj : Could you please review this pull request?

**Comment by asr** [comment]
@ak3n, thanks for the PR. Please close this PR and create a new one using the stable-2.5 branch.

**Comment by ghost** [comment]
@asr, sorry, you mean into `agda:stable-2.5` or based on `agda:stable-2.5` or both?

**Comment by asr** [comment]
I mean based on `agda:stable-2.5`.

**Pull request closed without merging**
