### PR TITLE
re #6298: Only consider arguments mentioned by the result type

### LINKED ISSUE #6298: Code is rejected with `--cubical-compatible`, but not with `--without-K`
The following code is accepted when `--without-K` is used, but rejected when `--cubical-compatible` is used:
```agda
open import Agda.Builtin.Equality

J :
  ∀ {@0 A : Set} {@0 x : A}
  (P : {y : A} → x ≡ y → Set) →
  P (refl {x = x}) →
  {y : A} (eq : x ≡ y) → P eq
J P p refl = p
```
Error message with `--cubical-compatible`:
```
This clause has target type
Agda.Primitive.Cubical.primTransp
(λ i →
   Agda.Primitive.Cubical.primTransp
   (λ i₁ →
      {y : A} →
      x
      (Agda.Primitive.Cubical.primIMin i₁
       (Agda.Primitive.Cubical.primINeg i))
      ≡ y →
      Set)
   (Agda.Primitive.Cubical.primIMax i φ) P
   (Agda.Builtin.Equality.transpX-_≡_
    (λ j →
       x
       (Agda.Primitive.Cubical.primIMax j
        (Agda.Primitive.Cubical.primINeg i)))
    (Agda.Primitive.Cubical.primIMax
     (Agda.Primitive.Cubical.primINeg i) φ)
    refl))
φ
(J
 (Agda.Primitive.Cubical.primTransp (λ i → {y : A} → x i ≡ y → Set)
  φ P)
 (Agda.Primitive.Cubical.primTransp
  (λ i →
     Agda.Primitive.Cubical.primTransp
     (λ j → {y : A} → x (Agda.Primitive.Cubical.primIMin i j) ≡ y → Set)
     (Agda.Primitive.Cubical.primIMax
      (Agda.Primitive.Cubical.primINeg i) φ)
     P refl)
  φ x₁)
 refl)
which is not usable at the required modality @irrelevant.

Note: to maintain compatibility with Cubical Agda, the target type
must be usable at the modality in which the function was defined,
since it is used for computing transports

when checking the definition of J
```
The error message's range matches that of the only clause of `J`, so it is natural to assume that "this clause" refers to that clause, but perhaps it actually refers to some generated clause.

@plt-amy, can you explain what is going on here?
* The code does not use irrelevance, so why does the error message state that the "target type […] is not usable at the required modality @irrelevant"?
* Does the error message refer to some generated code?
* I thought that the idea was that, after your changes, one should get this kind of error message also when `--without-K` is used. Why is that not the case for this code?

### PR DESCRIPTION
**Pull request by plt-amy**
Opening up a new PR since #6312 was beyond my Git abilities to salvage. Closes #6298

### CODE REVIEW

**Comment by plt-amy** [comment]
@Mergifyio rebase

**Comment by plt-amy** [comment]
CI failure was a timeout during setup-haskell, I'm hoping that upon a rerun it'll go back to working. Since we've settled on merging the conservative check for now I'll go ahead and merge once the rebase is done and CI passes

**Comment by plt-amy** [comment]
CI's failing because of caching nonsense (package Agda is unusable due to missing dependencies [...])

**Comment by andreasabel** [comment]
Thanks for landing this PR!

Please cherry-pick this to `release-2.6.3` and then leave a comment here that it is done.

**Comment by plt-amy** [comment]
@andreasabel Done, thanks for the reminder :slightly_smiling_face:

**Comment by andreasabel** [comment]
> CI's failing because of caching nonsense (package Agda is unusable due to missing dependencies [...])

See:
- https://github.com/agda/agda/issues/5258#issuecomment-1326094029

**Pull request merged**
