### PR TITLE
[ refactor ] Introduce arity-generic killRangeN

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by nad** [comment]
Did you test whether this change has an effect on performance?

**Comment by gallais** [comment]
Running `agda +RTS -s -RTS` on the stdlib.

On `master`:

```
958,566,092,760 bytes allocated in the heap
  21,750,356,720 bytes copied during GC
   1,510,719,720 bytes maximum residency (25 sample(s))
       6,151,152 bytes maximum slop
            1440 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0       377 colls,     0 par   37.480s  37.410s     0.0992s    0.8671s
  Gen  1        25 colls,     0 par    3.392s   3.387s     0.1355s    0.7142s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.002s  (  0.002s elapsed)
  MUT     time  489.745s  (489.014s elapsed)
  GC      time   40.872s  ( 40.797s elapsed)
  EXIT    time    0.000s  (  0.010s elapsed)
  Total   time  530.619s  (529.822s elapsed)

  Alloc rate    1,957,276,623 bytes per MUT second

  Productivity  92.3% of total user, 92.3% of total elapsed
```

On the `killRangeN` branch:

```
 959,397,547,600 bytes allocated in the heap
  23,021,274,984 bytes copied during GC
   1,396,261,440 bytes maximum residency (24 sample(s))
       2,005,072 bytes maximum slop
            1331 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0       381 colls,     0 par   37.443s  37.380s     0.0981s    0.7921s
  Gen  1        24 colls,     0 par    4.034s   4.029s     0.1679s    0.5764s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.002s  (  0.002s elapsed)
  MUT     time  475.561s  (474.905s elapsed)
  GC      time   41.477s  ( 41.408s elapsed)
  EXIT    time    0.001s  (  0.007s elapsed)
  Total   time  517.040s  (516.322s elapsed)

  Alloc rate    2,017,401,667 bytes per MUT second

  Productivity  92.0% of total user, 92.0% of total elapsed
```

**Comment by gallais** [comment]
Wondering if building Agda itself could be slower though as type families & friends are notoriously slow.
Note that I am on ghc 8.8.4.

### Running `time make type-check`.

On `master`:
```
real     1m12.818s
user     1m58.517s
sys      0m57.002s
```

On the `killRangeN` branch:
```
real     1m11.506s
user     1m54.266s
sys      0m55.511s
```


### Running `make quicker-install-bin`.

On `master`:
```
real      3m52.432s
user      3m45.565s
sys       0m7.084s
```

On the `killRangeN` branch:
```
real      3m56.632s
user      3m49.579s
sys       0m7.222s
```

### Running `make`

On `master`:
```
real      28m2.825s
user      27m48.156s
sys      0m16.884s
```

On the `killRangeN` branch:
```
real      28m51.628s
user      28m35.812s
sys       0m17.612s
```

**Review by andreasabel — APPROVED** [review]
Great!

**Pull request merged**
