### PR TITLE
Left-hand side `let`

### PR DESCRIPTION
**Pull request by UlfNorell**
This is a resurrected version of #4077 with the bugs fixed.

cf #4041

### CODE REVIEW

**Comment by andreasabel** [comment]
Would be good to have a _natural_ example where this new feature is making things easier.
I guess a final `using` on the lhs could just be a let on the rhs.
The `contrived` example is a real use, but then it is not natural, but well, _contrived_.

**Comment by UlfNorell** [comment]
It's hard to come up with natural examples, because the real wins are when you have larger proofs. Fwiw some people seem to think it will help a lot: https://github.com/agda/agda/pull/4077#issuecomment-596545594

**Comment by UlfNorell** [comment]
Just to forestall the inevitable bikeshedding: I tried `let` instead of `using` as the keyword, but the happy parser exploded in shift/reduce conflicts.

**Review by gallais — APPROVED** [review]
I'm really excited to see this come back!

**Review by jespercockx — APPROVED** [review]

**Comment by andreasabel** [comment]
Maybe change `using` to `let` if we can get it through `happy`. (See above.)

**Comment by UlfNorell** [comment]
Update on this after dev meeting. If we want to use the same keyword for non-abstracting with functions (which makes sense because that what we do for irrefutable `with` and normal `with`), `using` is actually a better keyword than `let`.

**Pull request merged**
