### PR TITLE
[ re #2837 ] Add support for holes in `.lagda.org` files

### PR DESCRIPTION
**Pull request by emilyhorsman**
+ This commit duplicates the efforts of 2068c65ab to add support for holes when editing `.lagda.org` files in Emacs.
+ #2837 is already closed after 2068c65ab added support for Markdown.
+ #3548 added support for compiling Org documents.

Demo:
Screen Shot 2019-03-30 at 4 41 02 PM

A note on the diff: I've aligned the S-expressions in the same way as before, so it looks like more substance has changed. Only L1488 has been changed substantially, and L1523-4 added.

### CODE REVIEW

**Comment by UlfNorell** [comment]
Nice. Thanks.

**Comment by JacquesCarette** [comment]
If anything was going to get me to seriously try org mode, this was it!

**Comment by spacekitteh** [comment]
Hmm. Goals no longer seem to be detected in .lagda.org files anymore, and don't get expanded to `{ }0` etc.

**Comment by spacekitteh** [comment]
Ok, I figured it out, the `#+begin_src` has to be in lower-case for it to work. The `#+end_src` can be either upper or lower case. Everything other than goals seem to work when it's `#+BEGIN_SRC`, however.

**Pull request merged**
