### PR TITLE
Mention possibility of comment lines in libraries file.

### LINKED ISSUE #6605: Doc: comments in "libraries" file
Is it possible to comment out lines in the "libraries" file?
The answer should be documented [here](https://agda.readthedocs.io/en/v2.6.3/tools/package-system.html), and if it is negative, I have a feature request :-)

### PR DESCRIPTION
**Pull request by anuyts**
Closes #6605 .
(Correctness of the added documentation yet to be confirmed.)

### CODE REVIEW

**Comment by anuyts** [comment]
Confirmed, but a space is needed after the `--`.

**Comment by anuyts** [comment]
Right so I get the output
```
/home/runner/work/agda/agda/doc/user-manual/tools/package-system.rst:142: WARNING: Inline literal start-string without end-string.
/home/runner/work/agda/agda/doc/user-manual/tools/package-system.rst:142: WARNING: Inline literal start-string without end-string.
```
but my rst syntax looks fine to me, I'm not sure what I'm doing wrong. Maybe
```
``-- ``
```
triggers something else than just an inline code block and I should escape that?

**Comment by andreasabel** [comment]
Thanks, @anuyts for the PR!  I am not an expert at RST, so I pushed a simple workaround.

**Comment by andreasabel** [comment]
On top of this, we get an error from readthedocs.org:
```
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. 
See: https://github.com/urllib3/urllib3/issues/2168
````
Need to investigate...

OK, it is this issue:
- https://github.com/readthedocs/readthedocs.org/issues/10290

PR for that:
- https://github.com/agda/agda/pull/6609

**Comment by andreasabel** [comment]
@Mergifyio rebase

**Comment by andreasabel** [comment]
Rendering here: https://agda--6607.org.readthedocs.build/en/6607/tools/package-system.html#installing-libraries

**Review by andreasabel — APPROVED** [review]

**Comment by andreasabel** [comment]
@anuyts: Happy with my fix?

**Comment by anuyts** [comment]
> @anuyts: Happy with my fix?

Yes, it's clearer actually!

**Pull request merged**
