### PR TITLE
Add a 'Toggle irrelevant arguments' command to emacs mode

### PR DESCRIPTION
**Pull request by SimonBoulier**
This PR adds a 'Toggle display of irrelevant arguments' command to emacs mode.
I think it is a very useful feature when working with Prop.

I followed how 'Toggle display of hidden arguments' is implemented.

It seems to work well but I didn't add any test in `test` (I don't know how it works and if it is necessary).

Any comment welcome.

### CODE REVIEW

**Review by andreasabel — CHANGES_REQUESTED** [review]
Thanks, looks good!

Could you please add a description to the CHANGELOG and to the documentation?

**Comment by SimonBoulier** [comment]
Thanks.
I added the chandelog entry. I already added documentation, do you want that I expand it?

**Comment by andreasabel** [comment]
Thanks for the CHANGELOG and the documentation.

The Travis CI shows a failure of the interaction test suite. Run `make interaction` with the Agda from your PR and approve the changes to the `.out` files.  The commit the changed `.out` files to your branch.

**Comment by andreasabel** [comment]
Thanks, Simon, for the contribution!

**Comment by SimonBoulier** [comment]
Thanks for merging!

**Pull request merged**
