### PR TITLE
I've tried to cherry-pick the fix to #3177

### PR DESCRIPTION
**Pull request by gallais**
As the title says, I've tried to cherry-pick the fix to #3177 and drop the irrelevant changes (i.e. the ones related to Prop & Cubical primitives)

ping #3228

### CODE REVIEW

**Comment by asr** [comment]
Great!

**Comment by asr** [comment]
@gallais, are you thinking that I should be merge this PR?

**Comment by gallais** [comment]
I'm not sure whether I like the fact the history make it look like it's seamless. Would it
be nicer to have the cherry-picked commits first and then the patches to make them
work with 2.5.4.2? But then again it's *semantically* the right notion of cherry-picking. :/

**Comment by asr** [comment]
It's OK for me. What I miss is the information "(cherry picked from commit 123)" in every commit message.

**Comment by gallais** [comment]
> What I miss is the information "(cherry picked from commit 123)" in every commit message.

done

**Pull request merged**
