### PR TITLE
[ fix #3417 fix #4348 ] highlight warnings as they are created

### LINKED ISSUE #3417: No highlighting for code that fails termination checking when an error is encountered
Consider the following code:
```agda
A : Set
A = A

B : Set
B = Set
```
Agda rejects this code:
```
———— Warning(s) ————————————————————————————————————————————
[...]/Bug.agda:1,1-2,6
Termination checking failed for the following functions:
  A
Problematic calls:
  A (at [...]/Bug.agda:2,5-6)
———— Error —————————————————————————————————————————————————
[...]/Bug.agda:5,5-8
Set₁ != Set
when checking that the expression Set has type Set
```
However, the problematic call in `A` is not highlighted as such in Emacs. (I tried using both non-interactive and interactive highlighting.)

### LINKED ISSUE #4348: Seemingly needless repetition of highlighting of warnings
Consider the following code:
```agda
{-# OPTIONS --warning ShadowingInTelescope #-}

Non-terminating : Set₁
Non-terminating = Non-terminating

postulate
  Shadowing : (A A : Set) → Set
```
Let us see what kind of highlighting is produced for this code (using `echo 'IOTCM "Test.Agda" NonInteractive Direct (Cmd_load "Test.agda" [])' | agda --interaction`):
```
(agda2-highlight-clear)
```
Clear everything.
```
(agda2-highlight-add-annotations 'nil '(1 4 (symbol) t) '(5 12 (keyword) t) '(13 22 (pragma) t) '(23 43 (pragma) t) '(44 47 (symbol) t) '(65 66 (symbol) t) '(67 70 (primitivetype) t) '(87 88 (symbol) t) '(106 115 (keyword) t) '(128 129 (symbol) t) '(130 131 (symbol) t) '(135 136 (symbol) t) '(137 140 (primitivetype) t) '(140 141 (symbol) t) '(142 143 (symbol) t) '(144 147 (primitivetype) t))
```
Token-based highlighting.
```
(agda2-highlight-add-annotations 'nil '(49 64 (function) nil nil ("/tmp/Test.agda" . 49)) '(71 86 (function) nil nil ("/tmp/Test.agda" . 49)) '(89 104 (function) nil nil ("/tmp/Test.agda" . 49)) '(118 127 (postulate) nil nil ("/tmp/Test.agda" . 118)) '(131 132 (bound) nil nil ("/tmp/Test.agda" . 131)) '(133 134 (bound) nil nil ("/tmp/Test.agda" . 133)))
```
Highllighting of the three occurrences of `Non-terminating`, the single occurrence of `Shadowing`, and the two occurrences of `A`. (I think this is the highlighting that is done after scope-checking.)
```
(agda2-highlight-add-annotations 'nil '(49 64 (function) nil nil ("/tmp/Test.agda" . 49)) '(65 66 (symbol) t) '(67 71 (primitivetype) t) '(132 133 (deadcode)))
(agda2-highlight-add-annotations 'nil '(49 64 (function) nil nil ("/tmp/Test.agda" . 49)) '(72 87 (function) nil nil ("/tmp/Test.agda" . 49)) '(88 89 (symbol) t) '(90 105 (function) nil nil ("/tmp/Test.agda" . 49)) '(132 133 (deadcode)))
(agda2-highlight-add-annotations 'nil '(49 64 (terminationproblem)) '(90 105 (terminationproblem)) '(119 128 (postulate) nil nil ("/tmp/Test.agda" . 119)) '(129 130 (symbol) t) '(131 132 (symbol) t) '(132 133 (deadcode bound) nil nil ("/tmp/Test.agda" . 132)) '(134 135 (bound) nil nil ("/tmp/Test.agda" . 134)) '(136 137 (symbol) t) '(138 141 (primitivetype) t) '(141 142 (symbol) t) '(143 144 (symbol) t) '(145 148 (primitivetype) t))
(agda2-highlight-add-annotations 'nil '(49 64 (terminationproblem)) '(90 105 (terminationproblem)) '(132 133 (deadcode)))
```
Presumably highlighting done during the type-checking of the code. Note that each of these four lines include `'(132 133 (deadcode))` or `'(132 133 (deadcode bound) nil nil ("/tmp/Test.agda" . 132))`.
```
(agda2-highlight-add-annotations 'nil '(1 4 (symbol) t) '(5 12 (keyword) t) '(13 22 (pragma) t) '(23 43 (pragma) t) '(44 47 (symbol) t) '(107 116 (keyword) t))
```
A final round of token-based highlighting.

Why is the `deadcode` highlighting repeated so many times? Note that the highlighting of the termination problem is also repeated.

### PR DESCRIPTION
**Pull request by andreasabel**
[ fix #3417 fix #4348 ] highlight warnings as they are created

Previously, *all* warnings of a file were highlighted upon successfully type-checking a declaration.  Problem was: if the declaration following a termination error had a hard error, the termination problems were not highlighted.

Now, we simply highlight warnings as they are created using the "warning" method.  This fixes the highlighting repetition for warnings observed in #4348, and also the missing warning highlighting upon hard errors.

### CODE REVIEW

**Review by gallais — APPROVED** [review]
AFAIK only errors are used for control flow and may be rolled back so highlighting
warnings as soon as they are raised in the TCM (i.e. immediately for the TC one and
after a slight delay for the Parser & Concrete.Definitions ones) should be fine.

**Comment by nad** [comment]
Is there no need for a test case for #4348?

**Comment by fredrikNordvallForsberg** [comment]
> Is there no need for a test case for #4348?

The added test case `test/interaction/Issue3417.agda` also demonstrates this: without applying the fix (and leaving out the final hard error), I e.g. get eight `(206 243 (deadcode))` in the highlighting output, which is reduced to only one in the `.out` file of the fix. But perhaps it would be good to record this as a comment in the test file?

**Review by fredrikNordvallForsberg — APPROVED** [review]

**Comment by andreasabel** [comment]
> Is there no need for a test case for #4348?

@fredrikNordvallForsberg answered this.  Also, the changes to the `.out` files included in this PR are witnesses for #4348: duplicate warning highlightning have been removed, a regression of #4348 would reintroduce them.

**Comment by andreasabel** [comment]
Pushed to master.

**Pull request closed without merging**
