### PR TITLE
Janitorial Changes to agda-mode

### PR DESCRIPTION
**Pull request by phikal**
This was formerly part of #6123 (see #5917), but has been restricted to just fixing superficial issues related to Elisp conventions.

### CODE REVIEW

**Comment by phikal** [comment]
See #6537.

**Comment by plt-amy** [comment]
I might be getting confused by the GitHub interface, but it looks like each of these PRs have all the changes?
Edit: Yup, I am getting confused. They all have the common prefix of the changes + whatever they describe. Ignore me!

**Comment by phikal** [comment]
If you check out my repository with all the branches, you should see a linear history.  The PRs are all just check-points.

I am more used to a mailing-like oriented workflow that are more flexible that what GitHub provides, so I apologize for the confusion

**Comment by phikal** [comment]
@andreasabel @nad Are there any objections or suggestions to these changes?

**Comment by phikal** [comment]
In the CI it seems this job failed due to external reason: https://github.com/agda/agda/actions/runs/4473173434/jobs/7860232876?pr=6536.  Does anyone know how I can restart the check?

**Comment by jespercockx** [comment]
I've restarted the failed check

**Comment by phikal** [comment]
Thanks, that seems to have resolved the "issue".

**Comment by phikal** [comment]
Should I split this up into smaller pull requests?

**Comment by andreasabel** [comment]
@phikal:  So these PRs are not independent, if I understand correctly.  But they are ordered, right?
Could you please lay down the order in which these PRs should be evaluated and merged?  Then we can tackle them one by one.

So I suggest you open a new issue in which you list these PRs in the order in which they should be evaluated, and then we can check them off one by one.
That would help me greatly in moving forward with testing the changes you propose.

**Comment by phikal** [comment]
I had given an order in https://github.com/agda/agda/pull/6123#issuecomment-1472151296, is this enough or should I create a separate issue?

**Comment by phikal** [comment]
I have merged the master branch into my development branch, but the documentation couldn't be re-built.  I don't seem to have touched any documentation in the last commit, so I don't understand why this happened.  Does anyone have an idea?

**Comment by UlfNorell** [comment]
There's a minor conflict with the new commands for mimer, but otherwise this could be merged? @phikal @andreasabel

**Comment by phikal** [comment]
Ulf Norell ***@***.***> writes:

> There's a minor conflict with the new commands for mimer, but
> otherwise this could be merged? @phikal @andreasabel

What is mimer?

**Comment by UlfNorell** [comment]
Mimer is the new proof search implementation that's replaced Agsy. The only change to the emacs mode was that a few functions changed name:
```
agda2-auto-maybe-all -> agda2-mimer-maybe-all
agda2-autoOne -> agda2-mimer
agda2-autoAll -> agda2-mimerAll
```
So resolving the conflict should be very easy.

**Comment by phikal** [comment]
Ulf Norell ***@***.***> writes:

> Mimer is the new proof search implementation that's replaced Agsy. The only change to the emacs mode was that a few functions changed name:
> ```
> agda2-auto-maybe-all -> agda2-mimer-maybe-all
> agda2-autoOne -> agda2-mimer
> agda2-autoAll -> agda2-mimerAll
> ```
> So resolving the conflict should be very easy.

I have already pushed a commit that should do that, hope it works.

**Comment by phikal** [comment]
What is `interaction-latex-html`?

**Comment by UlfNorell** [comment]
It's the test suite for interaction (including emacs mode) and latex/html backends. The failure is
```
In toplevel form:
.stack-work/install/x86_64-linux-tinfo6/c[23](https://github.com/agda/agda/actions/runs/7899951138/job/21560919935?pr=6536#step:10:24)f5779f04ca365f7af9f8d9932e847eec90e64c6a7ddb9ecf116023008e198/9.8.1/share/x86_64-linux-ghc-9.8.1/Agda-2.6.5/emacs-mode/agda2-mode.el:1990:1:
Error: the function ‘agda2-auto-maybe-all’ is not known to be defined.
Unable to compile the following Emacs Lisp files:
  /home/runner/work/agda/agda/.stack-work/install/x86_64-linux-tinfo6/c23f5779f04ca365f7af9f8d9932e847eec90e64c6a7ddb9ecf116023008e198/9.8.1/share/x86_64-linux-ghc-9.8.1/Agda-2.6.5/emacs-mode/agda2-mode.el
```
Looks like there's an `agda2-auto-maybe-all` that should be `agda2-mimer-maybe-all`.

**Comment by phikal** [comment]
Ulf Norell ***@***.***> writes:

> It's the test suite for interaction (including emacs mode) and
> latex/html backends. The failure is
> ```
> In toplevel form:
> .stack-work/install/x86_64-linux-tinfo6/c[23](https://github.com/agda/agda/actions/runs/7899951138/job/21560919935?pr=6536#step:10:24)f5779f04ca365f7af9f8d9932e847eec90e64c6a7ddb9ecf116023008e198/9.8.1/share/x86_64-linux-ghc-9.8.1/Agda-2.6.5/emacs-mode/agda2-mode.el:1990:1:
> Error: the function ‘agda2-auto-maybe-all’ is not known to be defined.
> Unable to compile the following Emacs Lisp files:
>   /home/runner/work/agda/agda/.stack-work/install/x86_64-linux-tinfo6/c23f5779f04ca365f7af9f8d9932e847eec90e64c6a7ddb9ecf116023008e198/9.8.1/share/x86_64-linux-ghc-9.8.1/Agda-2.6.5/emacs-mode/agda2-mode.el
> ```
> Looks like there's an `agda2-auto-maybe-all` that should be
> `agda2-mimer-maybe-all`.

Right, I have adjusted that, the byte-compiler doesn't appear to
complain on my system anymore.

**Comment by phikal** [comment]
OK, looks like that was the mistake.

**Comment by UlfNorell** [comment]
Nice. Anyone with more elisp experience want to weigh in on this? @nad @andreasabel?

**Comment by phikal** [comment]
FWIW there already was some discussion in https://github.com/agda/agda/pull/6123. @nad had some critical comments, where I am not sure if he was satifisied by my response.  I hope I am not mistaken by the impression that @andreasabel is supportive of these changes, considering his helpful assistance along the way.

**Comment by phikal** [comment]
I see that my changes have been merged in a single commit.  Is there any particular reason for this, because it losses information on what change was made why, e.g. when using `git blame`.

**Comment by UlfNorell** [comment]
Ah, sorry, that's our default merge strategy. You can tag with the label `pr: preserve commits` if you want the history to be preserved.

**Comment by phikal** [comment]
Where can I add that tag?  Asking for the other PRs.

**Comment by andreasabel** [comment]
@UlfNorell : The Agda mode now badly malfunctions on my machine since today, when I pulled and rebuilt from master.
So I guess this merge should be reverted.

**Comment by phikal** [comment]
Andreas Abel ***@***.***> writes:

> @UlfNorell : The Agda mode now badly malfunctions on my machine since today, when I pulled and rebuilt from master.
> So I guess this merge should be reverted.

Could you describe the issues you've been having?

Also, I wouldn't object to reverting the commit if we could apply it
again without squashing the commits.

**Comment by andreasabel** [comment]
It prints tons of errors and beeps inbetween.  Here is an excerpt of my `*Messages*` buffer, but it goes on for hundreds of lines...
```
error in process filter: car-safe: Wrong type argument: listp, olders/lg/qcd3v89j59l3m6520kr42bdm0000gn/T/agda2-mode83084-17
error in process filter: Wrong type argument: listp, olders/lg/qcd3v89j59l3m6520kr42bdm0000gn/T/agda2-mode83084-17
error in process filter: car-safe: Wrong type argument: listp, ighlight-add-annotations
error in process filter: Wrong type argument: listp, ighlight-add-annotations
error in process filter: car-safe: Wrong type argument: listp, 2-highlight-add-annotations
error in process filter: Wrong type argument: listp, 2-highlight-add-annotations
error in process filter: eval: Symbol’s function definition is void: typechecks
error in process filter: Symbol’s function definition is void: typechecks
error in process filter: car-safe: Wrong type argument: listp, 8
error in process filter: Wrong type argument: listp, 8
error in process filter: car-safe: Wrong type argument: listp, -annotations
error in process filter: Wrong type argument: listp, -annotations
error in process filter: car-safe: Wrong type argument: listp, s
error in process filter: Wrong type argument: listp, s
error in process filter: car-safe: Wrong type argument: listp, 87
error in process filter: Wrong type argument: listp, 87
error in process filter: car-safe: Wrong type argument: listp, gda2-highlight-add-annotations
error in process filter: Wrong type argument: listp, gda2-highlight-add-annotations
error in process filter: car-safe: Wrong type argument: listp, 897
error in process filter: Wrong type argument: listp, 897
error in process filter: car-safe: Wrong type argument: listp, light-add-annotations
error in process filter: Wrong type argument: listp, light-add-annotations
error in process filter: car-safe: Wrong type argument: listp, dd-annotations
error in process filter: Wrong type argument: listp, dd-annotations
error in process filter: car-safe: Wrong type argument: listp, 3294
error in process filter: Wrong type argument: listp, 3294
error in process filter: car-safe: Wrong type argument: listp, 3233
...
```

I'm on Emacs 29.1 (9.0) on macOS.

**Comment by phikal** [comment]
I can locate where the error is coming from, but I'll have to study what has changed since I last worked on agda2-mode (I don't use Agda regularly anymore, so I might have missed some interal changes), and I'll have to see when I'll find the time to dive into that again.  So in the meanwhile, please feel free to revert the commit, and my appologies for any problems this might have caused anyone.

**Comment by andreasabel** [comment]
Reverting fixed the problem for me, so I am pushing a revert now.

**Comment by UlfNorell** [comment]
> Where can I add that tag? Asking for the other PRs.

The labels are on the right side, but maybe you have to be a member of the organisation to add labels. I sent you an invite.

**Comment by phikal** [comment]
Seems to work now, thanks.

**Comment by phikal** [comment]
OK, it turns out the issue wasn't that complicated, so I have pushed a commit on my branch: https://github.com/phikal/agda/commit/4b8c6e664c71a511e6c871770362a8735a33e7ef.  It appears that this PR is borked, so I'll have to open up a new one, right?

**Comment by UlfNorell** [comment]
Yes, I don't think it's possible to reopen this one after it's been merged.

**Comment by phikal** [comment]
These that GitHub mentions above should actually be all the interesting changes, if we ignore matters of style and preferences of taste.  I was deliberating if https://github.com/agda/agda/pull/6536/commits/592dca63c2c44758cc812fa078682cfaebe932f9 might also be interesting (to avoid tab-vs-spaces issues in the future), perhaps with an additional `bug-reference-url-format` entry (which would allow Emacs highlighting occurrences of bug#1234 in comments as clickable buttons, also outside of `elisp-mode`), but decided against it for now.

**Pull request merged**
