### PR TITLE
Minor option+library cleanups

### PR DESCRIPTION
**Pull request by rwe**
Sorry that this is a bit of a hodgepodge. Happy to split up into isolated PRs if it will help.

Fixes:
  * Fixes an incorrect flag in recently-introduced `--show-identity-substitutions` flag.

Enhancements:
  * Removed the `MonadIO` requirement for `runOptM` by performing the library path validation later. This is consistent with other options and validation and didn't belong here.
  * Replaces all of the string-literal concatenated `libdir </> "prim"` expressions a new utility `getPrimitiveLibDir`.

Moves (in service of reducing dependency cycles):
  * `defaultCutoff` got moved out of `Agda.Interaction.Options` and into the module that defines `CutOff`.
  * `getIncludeDirs` got moved out of `Agda.Interaction.Options` and next to `setIncludeDirs` and so on in  `Agda.TypeChecking.Monad.Options`.
  * The `HasOptions` typeclass definition got moved out of `Agda.TypeChecking.Monad.Base` and into its own module `Agda.Interaction.Options.HasOptions`.
  * Moved `Agda.Interaction.Options` into an internal `Agda.Interaction.Options.Base`, re-exported from the former. (This is to avoid future dependency cycles between those internal modules).

Other cleanup:
  * Removed some outdated special-casing related to `Main` execution modes (e.g. "show version") that was _truly_ `__IMPOSSIBLE__` and served no purpose anymore.

### CODE REVIEW

**Review by jespercockx — APPROVED** [review]
Another great set of refactorings. I don't really see a need to split this up further into separate PRs.

**Comment by rwe** [comment]
There's a minor conflict introduced by the couple one-line changes in #5088. (I was hoping separating the `git mv` and modification would allow that to merge automatically, but I guess not; probably depends on GitHub's rename similarity threshold config). I'll go ahead and fix that conflict.

Also, the Travis build had earlier failed due to connection error pulling Stack. I'll let Travis do a full run before merging, just in case anything silly like the the flag fix causes a test failure since I last ran full suite.

**Comment by rwe** [comment]
The travis failure (after 8 hours of waiting!) was the spurious Issue 4967 test that for some reason sometimes gives extra output:
```
Agda.Builtin.Sigma.Σ.fst =
  λ a → case a of Agda.Builtin.Sigma._,_ b _ → b
Agda.Builtin.Sigma.Σ.snd =
  λ a → case a of Agda.Builtin.Sigma._,_ _ b →
```

I'm satisfied that this is not due to these changes.

**Comment by rwe** [comment]
Ah, and now there's a merge conflict already on master. Guess that's for tomorrow.

**Pull request merged**
