### PR TITLE
[ cubical ] Boundary-sensitive elaboration

### LINKED ISSUE #5997: Collect interaction point boundaries while elaborating right-hand-sides?
# Background

The user experience for Cubical Agda is subpar, and one of the biggest problems is that, even though interaction points _appear_ to have boundaries, there is a very limited set of circumstances that will actually cause an interaction point's boundary to be restricted. To wit: this only happens in `checkIApplyConfluence`, so if the interaction point does not have a boundary specified by the LHS of its clause, it will never have a boundary at all.

This poses some problems! For example, consider the following example:

```agda
double-comp
  : ∀ {ℓ} {A : Type ℓ} {w x y z : A} (p : w ≡ x) (q : x ≡ y) (r : y ≡ z)
  → w ≡ z
double-comp {ℓ = ℓ} {A = A} p q r i =
  hcomp {ℓ = ℓ} {A = A}
    (λ { j (i = i0) → {!   !} -- 0
       ; j (i = i1) → {!   !} -- 1
       })
      {! !}                   -- 2
```

Here, all the interaction points are "cubical", and thus have _some_ boundary (even though IP 2's boundary is fairly unspecified). But these boundaries are not fixed by the LHS, so the interaction points do not carry information about their boundary. Put concretely, the problems with the current interaction point boundary mechanism are as follows:

**Problem 1**: The boundary of an interaction point is usually _not_ fully determined simply by the LHS of the clause.

**Problem 2**: Interaction points in the same clause can have different boundaries.

**Problem 3**: The data which specifies an interaction point's boundary is underspecified for the purposes of computation.

# A proposal

1. The type of interaction point boundaries (`IPBoundary'`) should contain more specific information about what specific face is being described. Rather than carrying around a list of `(Term, Term)` equations (`ipbEquations`), each boundary condition should have a list of `(Var, Bool)` mappings specifying the _specific_ face. (I'll get to why we would want this refinement in a second). The rest of the type can stay as-is.

2. The list of `Closure IPBoundary` should not be attached to the clause. It should be attached directly to the `InteractionPoint`. This is a matter of both semantics and cleanliness: Semantically, the clause has nothing to do with the interaction points' boundary, as the `double-comp` example shows, and for cleanliness, this would keep the
invariant that `IPClause` is set only once by the coverage checker, and that _same_ `IPClause` is used by all the IPs in that clause.

3. Rather than collecting the boundary up-front, any suitable unification problem against an interaction point should refine its boundary. Concretely: In `Agda.TypeChecking.MetaVars.assign`, the `inverseSubst` function would have a new failure case: a refinement of `NeutralArg` for when the argument is one of the endpoints of the interval --- let's say it's `BoundaryArg`, but I'm not too concerned about the name. On this specific failure case, we would try to recover the unification problem as follows.

Let's use one of the unsolved constraints from `double-comp` as a representative example.

```
  z = ?1 (p = p) (q = q) (r = r) (j = i1) : A (blocked on _17)
```

`inverseSubst`, faced with these `Args`, would throw our new `BoundaryArg` exception, indicating the position of the first interval argument, which in this case is position `n = 3`. Then, we run the following checks:

- Taking the first _n_ arguments should give a list of `Args` in the pattern fragment, i.e., `inverseSubst` should _succeed_ for that `Args`. If this fails, we abort.

- Arguments in positions _n_ and up should consist only of applications to endpoints. I believe that the `Args` is guaranteed to be well-typed, but in case it is not, we can also enforce that dropping the first `n` binders from `telViewUpToPath (length args)` leaves us with `length args - n`-many interval-typed binders.

If both these checks succeed _and_ we are in one of the cubical modes _and_ the `MetaId` refers to an interaction point, then we are looking at a boundary, and _not_ an unsolved constraint. In that case I believe we can:

- Record the _n_-and-up'th arguments as making up the `Face`;
- Record the RHS of the equation as making up.. well, the right-hand-side of the boundary;
- Add this boundary constraint to the interaction point's data
- _Ignore the unification problem._ This is the part I'm iffiest about: I believe it'd be fine, since it would otherwise go unsolved after all, but perhaps it is more correct for it to be "blocked on boundary".

# Benefits

The biggest immediate benefit is that, assuming it is alright to drop the unification problem, cubical programs in the process of being written would have _a lot less_ type errors than they usually appear to have. Hopefully this would reduce the amount of yellow being shown to the user but I'm a bit less sure of that.

This refactoring means that `IPBoundary` now has a semantic meaning.  Specifically, we can look at an interaction point (say the same `?0` above) and construct a _precise_ cubical type specifying what terms would fit there. An interaction point in telescope `Γ` of type `T` with boundary conditions given by `φ₁ ⊢ t`, `φ₂ ⊢ s`, ..., is really `outS` of some term typable in the empty context as

```
Π Γ → Sub T (φ₁ ∨ φ₂ ∨ ...) λ { (φ₁ = i1) → t ; (φ₂ = i1) → s ; ... }
```

While it appears that this doesn't immediately translate to a benefit for the user, it _does_: If `⋁ φ` is logically equivalent to the disjunction `⋁ (i ∨ ~ i)` (`i` ranges over the variables mentioned in `φ`), then the `Sub` above is really an iterated `PathP`, _and we can tell the user that_! The interaction command which computes a helper function type can look for this special case and show the helper function type as a Path-type.

As an example, after specifying the base for `double-comp` (i.e. the user specifying that `?2 = q i`), we would be left with the following "type-and-boundaries" for the interaction points 0 and 1:

```
?0 :
  ∀ {l} {A : Type l} {w x y z : A} (p : w ≡ x) (q : x ≡ y) (r : y ≡ z)
  → (j : I) → Sub A (j ∨ ~ j) λ { (j = i0) → x ; (j = i1) → w }
?1 :
  ∀ {l} {A : Type l} {w x y z : A} (p : w ≡ x) (q : x ≡ y) (r : y ≡ z)
  → (j : I) → Sub A (j ∨ ~ j) λ { (j = i0) → y ; (j = i1) → z }
```

which, since `j ∨ ~ j` _is_ the disjunction of the boundary of `j`, could be displayed in simplified form as

```
?0 :
  ∀ {l} {A : Type l} {w x y z : A} (p : w ≡ x) (q : x ≡ y) (r : y ≡ z)
  → Path A x w
?1 :
  ∀ {l} {A : Type l} {w x y z : A} (p : w ≡ x) (q : x ≡ y) (r : y ≡ z)
  → Path A y z
```

### LINKED ISSUE #6009: Cubical: User-friendly usage of HLevel proofs
For a while, I've been quite annoyed by the fact that in the following code, I cannot let Agda solve (C-c C-s) both goals below or just write underscores, even though it seemed clear to me that `x` and `y` are the only possible solutions:

```agda
{-# OPTIONS --cubical #-}

open import Cubical.Foundations.Prelude

module InvokeHLevelSimple where

variable A : Type

prop : (A : Type) → isProp A → isProp A
prop A isPropA x y i = isPropA {!!} {!!} i
```

A bit to my surprise, I realized this is not true. The first goal is only constrained at `i = i0` and the second one at `i = i1`:

```agda
prop1 : (A : Type) → isProp A → isProp A
prop1 A isPropA x y i = isPropA x y i

prop2 : (A : Type) → isProp A → isProp A
prop2 A isPropA x y i = isPropA (isPropA x y i) (isPropA x y i) i
```

The consequences of this are grave: whenever you want to invoke a type's HLevel when you have already abstracted over the dimensions, you are forced to repeat its entire boundary. (And of course knowing a type's HLevel is a relief in particular when this boundary is complicated.)

I was hoping to write a macro to remove a variable from the context, so that we could at least write

```agda
prop3 : (A : Type) → isProp A → isProp A
prop3 A isPropA x y i = isPropA (i # _) (i # _) i
```

but I ran into at least two problems:
* Agda's reflection mechanism doesn't have a substitution operation,
* Macro invocations one of whose arguments is a metavariable or underscore, seem to wait for it to be solved rather than being called with a quotation of the metavariable/underscore.

A macro would probably be just one of multiple solutions to this problem, but I do consider this a severe problem w.r.t. the usability of cubical agda.

The core problem described above seems superficially related to proposals #5884 and #5997.

### LINKED ISSUE #6017: Uninformative error when checking boundaries of functions defined on HITs
This code:

```agda
{-# OPTIONS --cubical #-}
open import Cubical.Foundations.Prelude

data T : Type where
  base : T
  p : base ≡ base
  surf : p ∙ p ≡ p

f : (x : T) → x ≡ x
f base = refl
f (p i) = refl
f (surf i j) = refl
```

produces this error:

```
(~ i ∨ i) ∨ ~ i₁ ∨ i₁ != ~ i ∨ i of type I
when checking the definition of f
```

on both Agda 2.6.2.2 and master (5d2d77abbc0c97f5b23d7089797c3ef8796508dc).

For context, I stumbled upon this error while trying to prove that the definition of the torus in terms of `p ∙ q ≡ q ∙ p` is equivalent to the one in the cubical library:
https://github.com/ncfavier/cubical-experiments/blob/f14da384b38cdea9eed82507cd12f6263a85969e/Torus.agda#L55-L57

cc. @mortberg @plt-amy @aljungstrom

### PR DESCRIPTION
**Pull request by plt-amy**
Refactors the type checker to keep track of cubical constraints as a dedicated field in the `TCEnv`. The constraints associated with any given metavariable are printed in the goal, as before, but their _precise_ representation allows us to e.g. reify the boundary as a `Sub` type (implemented as `agda2-goal-type-as-sub`). Going under introduction forms refines the boundary with the corresponding elimination.

Super WIP, no attention has been paid to making sure tests still pass, boundaries in goal types are printed with their internal representation rather than a user-facing representation, etc, etc.

TODO (off the top of my head):

- [x] ~~Can I really axe `IApplyConfluence` like that? Probably not. Let's only call it when there's ≥2 definitions in the mutual block: that way we can be sure that it _still works_ for mutual higher recursion, but for the most common case, we get a nice boundary and no yellow.~~ `IApplyConfluence` lives again (it just uses the `Boundary` machinery to get better error messages)
- [ ] Replace `hcomp`-and-friends' magical type-checking rules with boundary constraints
- [x] Refine the boundary when going into record constructors, record literals and record updates
- [ ] Understand interaction between boundaries and pattern lambdas
- [ ] Automated tests for _everything_
- [ ] Expose a reflection primitive to reify the boundary (fixes #6009)

Mosquito nuke: this fixes #6017, but I need to make the error term less _absolutely massive_. "Fixes" #5884 since the boundary at any interaction point can be reified to a `Sub`-type. Supersedes #5999 and closes #5997.

### CODE REVIEW

**Comment by plt-amy** [comment]
Error message from #6017 w/ the current implementation:

```
~ i₁ ∨ i₁ != (~ i₁ ∨ i₁) ∨ ~ i₂ ∨ i₂ of type I
when checking the boundary condition
(i = i0) ⊢ primHComp
           (λ i₂ .o →
              primTransp
              (λ i₃ →
                 primHComp
                 (λ j →
                    primPOr (~ i₁ ∨ i₁) (~ i₃ ∧ ~ i₂)
                    ((λ { i₄ (i₁ = i0) → p i0 ; i₄ (i₁ = i1) → p i₄ }) ((i₃ ∨ i₂) ∧ j))
                    (λ .o₁ → p i₁))
                 (p i₁)
                 ≡
                 primHComp
                 (λ j →
                    primPOr (~ i₁ ∨ i₁) (~ i₃ ∧ ~ i₂)
                    ((λ { i₄ (i₁ = i0) → p i0 ; i₄ (i₁ = i1) → p i₄ }) ((i₃ ∨ i₂) ∧ j))
                    (λ .o₁ → p i₁))
                 (p i₁))
              i₂ (f ((λ { i₃ (i₁ = i0) → p i0 ; i₃ (i₁ = i1) → p i₃ }) i₂ _)))
           (primTransp
            (λ i₂ →
               primHComp
               (λ j →
                  primPOr (~ i₁ ∨ i₁) (~ i₂)
                  ((λ { i₃ (i₁ = i0) → p i0 ; i₃ (i₁ = i1) → p i₃ }) (i₂ ∧ j))
                  (λ .o → p i₁))
               (p i₁)
               ≡
               primHComp
               (λ j →
                  primPOr (~ i₁ ∨ i₁) (~ i₂)
                  ((λ { i₃ (i₁ = i0) → p i0 ; i₃ (i₁ = i1) → p i₃ }) (i₂ ∧ j))
                  (λ .o → p i₁))
               (p i₁))
            i0 refl) = refl
```

**Comment by plt-amy** [comment]
Y'know I was expecting CI to fail on the previous commit but I wasn't expecting it to fail _so fast_

**Comment by plt-amy** [comment]
Putting this here as a note to myself: There's a recurring problem that I _really_ need to minimize, but line 278 in `ZCohomology/GroupStructure` always causes unsolved metas when the boundary checks aren't postponed. Like, I've had literally this same issue before.. at least I recognised it before spending hours and hours debugging

**Comment by plt-amy** [comment]
@Mergifyio rebase

**Comment by andreasabel** [comment]
Closed in favor of
- #6529

**Pull request closed without merging**
