### PR TITLE
Fix for #4727

### LINKED ISSUE #4727: Meta-variable solutions contain subterms with the wrong modality
This problem was discovered by @Saizan.

The following code is accepted:
```agda
{-# OPTIONS --without-K --safe #-}

open import Agda.Builtin.Equality
open import Agda.Builtin.Sigma

private
  variable
    A B   : Set
    P Q   : A → Set
    f x y : A

id : A → A
id x = x

_∘_ : {B : A → Set} {C : {x : A} → B x → Set} →
      (∀ {x} (y : B x) → C y) → (g : (x : A) → B x) →
      ((x : A) → C (g x))
f ∘ g = λ x → f (g x)

Σ-map : (f : A → B) → (∀ {x} → P x → Q (f x)) →
        Σ A P → Σ B Q
Σ-map f g (x , y) = f x , g y

record Erased (@0 A : Set) : Set where
  constructor [_]
  field
    @0 erased : A

open Erased

cong : (f : A → B) → x ≡ y → f x ≡ f y
cong f refl = refl

Contractible : Set → Set
Contractible A = Σ A λ x → ∀ y → x ≡ y

Contractibleᴱ : Set → Set
Contractibleᴱ A = Σ A λ x → Erased (∀ y → x ≡ y)

_⁻¹_ : (A → B) → B → Set
f ⁻¹ y = Σ _ λ x → f x ≡ y

_⁻¹ᴱ_ : {@0 B : Set} → @0 (A → B) → @0 B → Set
f ⁻¹ᴱ y = Σ _ λ x → Erased (f x ≡ y)

Is-equivalence : (A → B) → Set
Is-equivalence f = ∀ y → Contractible (f ⁻¹ y)

Is-equivalenceᴱ : @0 (A → B) → Set
Is-equivalenceᴱ f = ∀ y → Contractibleᴱ (f ⁻¹ᴱ y)

@0 Contractibleᴱ→Contractible : Contractibleᴱ A → Contractible A
Contractibleᴱ→Contractible = Σ-map id erased

⁻¹→⁻¹ᴱ : f ⁻¹ y → f ⁻¹ᴱ y
⁻¹→⁻¹ᴱ = Σ-map id (λ x → [ x ])

@0 ⁻¹ᴱ→⁻¹ : f ⁻¹ᴱ y → f ⁻¹ y
⁻¹ᴱ→⁻¹ = Σ-map id erased

@0 Is-equivalenceᴱ→Is-equivalence :
  Is-equivalenceᴱ f → Is-equivalence f
Is-equivalenceᴱ→Is-equivalence eq y =
    ⁻¹ᴱ→⁻¹ (fst (eq y))
  , (cong ⁻¹ᴱ→⁻¹ ∘ (erased (snd (eq y)) ∘ ⁻¹→⁻¹ᴱ))

record _≃_ (A B : Set) : Set where
  constructor ⟨_,_⟩
  field
    to             : A → B
    is-equivalence : Is-equivalence to

  from : B → A
  from y = fst (fst (is-equivalence y))

  right-inverse-of : ∀ y → to (from y) ≡ y
  right-inverse-of y = snd (fst (is-equivalence y))

  irrelevance : ∀ y (p : to ⁻¹ y) → (from y , right-inverse-of y) ≡ p
  irrelevance y = snd (is-equivalence y)

record _≃ᴱ_ (A B : Set) : Set where
  constructor ⟨_,_⟩
  field
    to             : A → B
    is-equivalence : Is-equivalenceᴱ to

  from : B → A
  from y = fst (fst (is-equivalence y))

  @0 equivalence : A ≃ B
  equivalence =
    ⟨ to , Is-equivalenceᴱ→Is-equivalence is-equivalence ⟩

record Erased-proofs {A B : Set} (to : A → B) (from : B → A) : Set where
  field
    right-inverse-of : ∀ y → to (from y) ≡ y
    irrelevance      : ∀ y (p : to ⁻¹ y) →
                       (from y , right-inverse-of y) ≡ p

[proofs] :
  (A≃B : A ≃ B) → Erased-proofs (_≃_.to A≃B) (_≃_.from A≃B)
[proofs] A≃B .Erased-proofs.right-inverse-of =
  _≃_.right-inverse-of A≃B
[proofs] A≃B .Erased-proofs.irrelevance =
  _≃_.irrelevance A≃B

[≃]→≃ᴱ :
  {to : A → B} {from : B → A} →
  @0 Erased-proofs to from →
  A ≃ᴱ B
[≃]→≃ᴱ {to = to} {from = from} ep =
  ⟨ to
  , (λ y → (from y , [ Erased-proofs.right-inverse-of ep y ])
         , [ cong ⁻¹→⁻¹ᴱ ∘ (Erased-proofs.irrelevance ep y ∘ ⁻¹ᴱ→⁻¹) ])
  ⟩

Σ-cong :
  (A≃B : A ≃ B) →
  (∀ x → P x ≃ Q (_≃_.to A≃B x)) →
  Σ A P ≃ Σ B Q
Σ-cong = {!!}

Σ-congᴱ :
  (A≃B : A ≃ B) →
  (∀ x → P x ≃ᴱ Q (_≃_.to A≃B x)) →
  Σ A P ≃ᴱ Σ B Q
Σ-congᴱ f g =
  [≃]→≃ᴱ {to = {!!}} {from = {!!}}
    ([proofs] (Σ-cong f (_≃ᴱ_.equivalence ∘ g)))
```
The last two meta-variables are solved. However, the solutions include `_≃ᴱ_.equivalence`, which is erased:
```
?1 := _≃_.to (Σ-cong f (λ x → _≃ᴱ_.equivalence (g x)))
?2 := _≃_.from (Σ-cong f (λ x → _≃ᴱ_.equivalence (g x)))
```

### LINKED ISSUE #5042: Double-check modalities
I don't think the double-checker checks that modalities (except for relevance) are correct. Here's one example:

https://github.com/agda/agda/blob/bc327151a92f20b0ff2e2d3b18270e4b4797bca8/src/full/Agda/TypeChecking/CheckInternal.hs#L281-L285

### PR DESCRIPTION
**Pull request by jespercockx**
This is my proposed fix for #4727. Unfortunately it does not yet pass the test suite, so if anyone wants to look at the remaining problems that would be great.

### CODE REVIEW

**Comment by jespercockx** [comment]
Thanks to the help by @Saizan and @UlfNorell I think this should now be fixed! (fingers crossed for CI)

**Comment by jespercockx** [comment]
Hm, there are still two more issues:

- The error message for `test/Fail/Issue3855d.agda` has changed from "unsolved constraints" to the following:
```
Expected an erased argument, but found a unrestricted argument
when checking that the clause
works = record { to = [_] ; from = _ ; to∘from = λ _ → refl } has
type {A : Set} → A ↠ Erased A
```
I'm not sure if this is expected or not, maybe @nad has a better intuition about erasure.

- The standard library test also fails with unsolved metas. Here is a minimized example:
```
open import Agda.Primitive

private
  variable
    a ℓ : Level
    A : Set a

postulate Rel : Set a → (ℓ : Level) → Set (a ⊔ lsuc ℓ)

module _ (_∼_ : Rel A ℓ) where
```
This used to work but now end up with an unsolved meta `_A.a_15 : Level`. Probably the change to generalization means this meta is no longer generalized over, but I'm not sure why. Perhaps @UlfNorell has an idea?

**Comment by UlfNorell** [comment]
What's the `-v tc.generalize:30` output. Specifically the metas that are considered for generalization. Maybe the checkpoint  filtering does the wrong thing for generalization in module headers?

**Comment by nad** [comment]
> ```
> Expected an erased argument, but found a unrestricted argument
> when checking that the clause
> works = record { to = [_] ; from = _ ; to∘from = λ _ → refl } has
> type {A : Set} → A ↠ Erased A
> ```
> 
> I'm not sure if this is expected or not, maybe @nad has a better intuition about erasure.

If a function expects an erased argument, then it should be fine to give a non-erased argument, so the error message sounds strange to me. In this case Agda should not solve the meta-variable: it should not be possible to instantiate the underscore with `erased`.

**Comment by jespercockx** [comment]
I found the cause of the problem with the standard library. It did not in fact have anything to do with the filtering of old metas I implemented this week. Instead, somehow some metavariables were created with quantity `@1` instead of `@ω`, which caused the quantity check part of the occurs check to fail under certain conditions, which lead to an unsolved constraint, which lead to the level metavariable to be considered as "constrained", which caused it not to be generalized over. Ugh.

As far as I can tell the mechanism for `@1` is not fully implemented yet, and when I replace the definition of `unitModality` from `Quantity1` to `Quantityω` then the problem seems to disappear. So that's what I'm going to do now, though this might require a deeper investigation when the plans for `@1` are picked up again.

**Comment by jespercockx** [comment]
@UlfNorell I found an easter egg! Too bad it's only on a version of Agda with my own modifications...
```agda
{-# OPTIONS --cubical #-}
open import Agda.Primitive
open import Agda.Builtin.Cubical.Sub

private
  variable
    ℓ : Level
    A : Set ℓ

postulate
  w/e : ∀ {ℓ} {A : Set ℓ} → A

postulate
  hcomp-equivFillerSub : Sub A _ (λ { _ → w/e })
```
Error:
```
Congratulations! You have found an easter egg (#RFCX). Be the first
to submit a self-contained test case (max 50 lines of code)
producing this error message to
https://github.com/agda/agda/issues/3672 to receive a small prize.
The error is caused by complicated dependencies between unsolved
metavariables and generalized variables. In particular, this meta:
  _ℓ_15 at [...]:14,43-46
when checking that the expression w/e has type A
```

**Comment by nad** [comment]
I ran a test on my own code, and got the following error message:
```
Expected an erased argument, but found an erased argument
```
Here is a small test case:
```agda
postulate
  A : Set

record R : Set₁ where
  field
    F : @0 A → Set
    f : (x : A) → F x

postulate
  r : R

open R r

G : A → Set₁
G x with f x
… | _ = Set
```
```
Expected an erased argument, but found an erased argument
when checking that the type (x : A) → F x → Set₁ of the generated
with function is well-formed
```
This code should presumably be accepted.

**Comment by jespercockx** [comment]
Here is a version without cubical that still triggers the easter egg:
```agda
open import Agda.Primitive

variable
  ℓ : Level
  A : Set ℓ

postulate
  w/e : ∀ {a} {A : Set a} → A

  Sub : {a : Level} (A : Set a) → (Set → A) → Set

  hcomp-equivFillerSub : Sub A (λ { _ → w/e {_} {_} })
```

**Comment by nad** [comment]
The following code is rejected:
```agda
open import Agda.Builtin.Equality

variable
  A      : Set
  eq x y : A

postulate
  subst  : {A : Set} {x y : A} (P : A → Set) → x ≡ y → P x → P y
  substᴱ : {@0 A : Set} {@0 x y : A}
           (P : @0 A → Set) → @0 x ≡ y → P x → P y
  lemma  : (P : ∀ {y} → x ≡ y → Set) (x≡y : x ≡ y) → P x≡y

substᴱ≡subst :
  {P : @0 A → Set} {p : P x} →
  substᴱ P eq p ≡ subst (λ x → P x) eq p
substᴱ≡subst {eq = eq} {P = P} {p = p} = lemma
  (λ eq → substᴱ P eq p ≡ subst (λ x → P x) eq p)
  eq
```
The problem is that Agda infers the following type for `substᴱ≡subst`:
```agda
{A : Set} {x : A} {@0 y : A} {eq : x ≡ y} {P : @0 A → Set} {p : P x} →
substᴱ P eq p ≡ subst (λ x₁ → P x₁) eq p
```
Note that `y` is erased. It should not be (#5058).

**Comment by nad** [comment]
> Note that `y` is erased. It should not be (#5058).

Debugging suggests that `y` is in `alsoGeneralize`:
```
  alsoGeneralize       =  _y_54
```
Thus I would have thought that `y` [should](https://github.com/jespercockx/agda/blob/c954eebba9d46b65ab258827888413f9cfce8c9e/src/full/Agda/TypeChecking/Generalize.hs#L305-L307) have gotten the default modality. However, it didn't:
```
genTel = {A : Set} {x : A} {@0 y : A} {eq : x ≡ y}
```

**Comment by nad** [comment]
Ignore the previous two messages, I had compiled the wrong branch…

**Comment by nad** [comment]
The following code is rejected, but it is accepted by Agda 2.6.2-977396f:
```agda
{-# OPTIONS --sized-types #-}

open import Agda.Builtin.Equality
open import Agda.Builtin.Size

mutual

  data D (i : Size) : Set where
    c : D′ i → D i

  record D′ (i : Size) : Set where
    coinductive
    field
      force : (j : Size< i) → D j

data R (i : Size) : D ∞ → D ∞ → Set where
  c₁ : ∀ x y → R i (c x) (c y)
  c₂ : ∀ x y → R i (c x) y

postulate
  F : (x : D ∞) (x′ : D′ ∞) → x ≡ c x′ → Set₁

G : Size → Set₁
G i = Set
  where
  G′ :
    (x′ y′ : D ∞) (x y : D′ ∞) →
    R i (c x) y′ →
    R i x′ (c y) →
    x .D′.force _ {- ∞ -} ≡ x′ →
    Set₁
  G′ _ _ _ _ (c₁ x _) (c₂ u _) eq   = F _ {- x .D′.force ∞ -} u eq
  G′ _ _ _ _ (c₂ _ _) _        refl = Set
  G′ _ _ _ _ _        _        _    = Set
```
The code is accepted if either of the two underscores that are followed by a comment are replaced by the code in the comment.

This might be a problem with the implementation of sized types, and it is easy to work around, so I suggest that we just add the test case to `test/Bugs` and move on.

**Comment by nad** [comment]
The following code is rejected, but accepted by Agda 2.6.2-977396f:
```agda
record R₁ : Set₂ where
  field
    _≡_ : {A : Set₁} → A → A → Set

postulate
  A B : Set

record R₂ (r₁ : R₁) : Set₂ where
  open R₁ r₁
  field
    cong  : (A : Set₁) (x y : A) (F : A → Set) → x ≡ y → F x ≡ F y
    subst : (P : Set → Set₁) → A ≡ B → P A → P B

postulate
  _≡_ : {A : Set₁} → A → A → Set

r₁ : R₁
r₁ .R₁._≡_ = _≡_

postulate
  r₂ : ∀ r₁ → R₂ r₁

open R₂ (r₂ r₁)

record R₃ (@0 A : Set₁) : Set₁ where
  constructor [_]
  field
    f : A

postulate
  r₃            : R₃ Set
  push-subst-[] :
    (P : Set → Set₁) (p : P A) (eq : A ≡ B) →
    subst (λ A → R₃ (P A)) eq [ p ] ≡ [ subst P eq p ]

_ :
  (eq : A ≡ B) →
  (subst (λ _ → R₃ Set) eq r₃ ≡ r₃) ≡
  ([ subst (λ _ → Set) eq (R₃.f r₃) ] ≡ r₃)
_ = λ eq → cong _ _ _ (_≡ _) (push-subst-[] _ _ _)
```
```
Failed to solve the following constraints:
  _47 (section = [ subst (λ v → _P_44 v) _eq_43 _p_42 ]) = r₃
    : R₃ (_P_44 B)
    (blocked on _47)
  [ subst (λ v → _P_44 v) _eq_43 _p_42 ]
    = [ subst (λ _ → Set) eq (R₃.f r₃) ]
    : R₃ (_P_44 B)
    (blocked on _49)
  _P_44 B = Set : Set₁ (blocked on _P_44)
  _47 (section = (subst (λ A₁ → R₃ (_P_44 A₁)) _eq_43 [ _p_42 ]))
    = r₃
    : R₃ (_P_44 B)
    (blocked on _47)
  subst (λ A₁ → R₃ (_P_44 A₁)) _eq_43 [ _p_42 ]
    = subst (λ _ → R₃ Set) eq r₃
    : R₃ (_P_44 B)
    (blocked on _46)
```
If the last definition is replaced by the following code, then there are fewer unsolved constraints:
```agda
_ :
  (eq : A ≡ B) →
  (subst (λ _ → R₃ Set) eq r₃ ≡ r₃) ≡
  ([ subst (λ _ → Set) eq (R₃.f r₃) ] ≡ r₃)
_ = λ eq → cong _ _ _ (_≡ _) (push-subst-[] _ _ eq)
```
```Failed to solve the following constraints:
  [ subst (λ v → _P_43 v) eq _p_42 ]
    = [ subst (λ _ → Set) eq (R₃.f r₃) ]
    : R₃ (_P_43 B)
    (blocked on _48)
  _P_43 B = Set : Set₁ (blocked on _P_43)
  subst (λ A₁ → R₃ (_P_43 A₁)) eq [ _p_42 ]
    = subst (λ _ → R₃ Set) eq r₃
    : R₃ (_P_43 B)
    (blocked on _45)
```
If the last definition is replaced by the following code, then Agda 2.6.2-977396f also rejects:
```agda
postulate
  eq : A ≡ B

_ :
  (subst (λ _ → R₃ Set) eq r₃ ≡ r₃) ≡
  ([ subst (λ _ → Set) eq (R₃.f r₃) ] ≡ r₃)
_ = cong _ _ _ (_≡ _) (push-subst-[] _ _ _)
```
```
Failed to solve the following constraints:
  _40 (section = (subst (λ A₁ → R₃ Set) eq r₃)) = r₃ : R₃ Set
    (blocked on _40)
  _40 (section = [ subst (λ _ → Set) eq (R₃.f r₃) ]) = r₃ : R₃ Set
    (blocked on _40)
```

**Comment by nad** [comment]
I did not find any other problems in my code.

**Comment by jespercockx** [comment]
> The following code is rejected, but accepted by Agda 2.6.2-977396f:
> 
> ```agda
> record R₁ : Set₂ where ...

I found the cause of this problem: `antiUnifyArgs` was using the `Eq` instance for `Modality` instead of `sameModality`, which caused it to fail for equal modalities with different origins. I've pushed the fix now to this branch.

**Comment by nad** [comment]
> I found the cause of this problem

Great!

> `antiUnifyArgs` was using the `Eq` instance for `Modality` instead of `sameModality`, which caused it to fail for equal modalities with different origins.

Aren't we asking for trouble by having such an `Eq` instance? Is there any use for it?

**Comment by jespercockx** [comment]
> Aren't we asking for trouble by having such an Eq instance? Is there any use for it?

I was wondering the same thing. This is the second time that this Eq instance has caused problems for me.

**Comment by jespercockx** [comment]
Finally found (and fixed) the problem with generalized variables as well, this should now (hopefully) be ready to merge.

**Comment by jespercockx** [comment]
The remaining test failure seems to be some kind of artifact of the CI rather than a genuine error, so I'll merge this in now.

**Pull request merged**
