### PR TITLE
[ re #4250 ] update main for stdlib 1.5

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by gallais** [comment]
The build error seems unrelated?

**Comment by L-TChen** [comment]
Looks like #5107.

**Comment by gallais** [comment]
I don't know that the final program is "so much more" verbose
(you commented on a broken version).

One problem is that IO is pretty complicated and we are exposing
newcomers to IO vs. IO.Primitive already (something we were lying
to ourselves about by not giving `main`'s type declaration and
relying on inference to work, a bad practice in DTP)...

This could perhaps be somewhat mitigated by introducing a `Main`
alias for `IO.Primitive.IO {0ℓ} ⊤` in `IO` and have `main : Main`.

**Comment by MatthewDaggitt** [comment]
> This could perhaps be somewhat mitigated by introducing a Main
alias for IO.Primitive.IO {0ℓ} ⊤ in IO and have main : Main.

I'd be in favour of that :+1:

**Comment by gallais** [comment]
Haha, turns out our `README.IO` was broken too (but we were not typechecking it so
we did not notice it!).

**Comment by gallais** [comment]
I've introduced `Main` and revamped [`README.IO`](https://github.com/agda/agda-stdlib/pull/1415/files#diff-538d3c3fcd5b504afb537fe11a46a8618fc4823327f274ece9a91b6d57dac357)

**Comment by gallais** [comment]
Fixed by #5223

**Pull request closed without merging**
