### PR TITLE
[ fix #5558 ] add new fatal warning MissingDeclarations

### LINKED ISSUE #5558: IMPOSSIBLE when defining constructors for an undefined type in interleaved mutual
To reproduce:

```agda
module _ where
interleaved mutual
  -- we don't do `data A : Set`
  data A where
    -- you don't have to actually define any constructor to trigger the error, the "where" is enough
```

This is clearly an error, but instead of pointing out to the user that `A` is not defined, Agda outputs:

```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/Syntax/Concrete/Definitions.hs:851:18 in Agda-2.6.2-a32bc3e9a1957922ee5c93d8f1383f8060330e499a4b7f40506de5275251d0c9:Agda.Syntax.Concrete.Definitions
```

I'm using Agda version 2.6.2

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Review by andreasabel — APPROVED** [review]
This fix is likely superior to #5560.

**Comment by gallais** [comment]
What's our course of action @andreasabel? Should I cherry-pick the refactorings
from your branch and push them to this PR before merging the whole thing?

**Comment by andreasabel** [comment]
@gallais: I'll push the refactorings to master and then we can rebase your PR.  I think (hope) there won't be any conflicts.

**Comment by andreasabel** [comment]
Actually, I put my refactorings on a new PR, #5566.

You can go ahead an merge your PR first, @gallais, while #5566 finishes building.

**Pull request merged**
