### PR TITLE
[ actions ] Pack artifact with installation script

### PR DESCRIPTION
**Pull request by ice1000**
To get a try: download one of the zips from this page: https://github.com/agda/agda/commit/5dbec274542bcf6762d3ccaddf192a987e25f784/checks?check_suite_id=332616110

You should see the list of zips at the top-right corner that looks like the following:
Screenshot from 2019-11-28 00-08-20

The zip file is self-contained -- all you need to do is to download, unzip it and run the `dist_install_user.sh` script.

### CODE REVIEW

**Comment by ice1000** [comment]
TODO: document this.

From now on, newcomers may not be forced to install Haskell toolchain for Agda.
(The Windows installation script is not yet tested, I'll do it soon)

**Comment by nad** [comment]
Do the artifacts that you produce follow all the relevant licences? For instance, Agda depends on a number of libraries (see `src/agda-licences`), and if you include DLLs, then those presumably also fall under some kind of licence.

**Comment by ice1000** [comment]
I didn't -- let's add them?

**Comment by L-TChen** [comment]
I will move this step to a separate workflow running periodically, if there is any change to the codebase, on `master` branch and compiling `Agda` with the option `-O`. Since the artifact is to provide a nightly release, there is little point of providing different binaries based on GHC versions. Maybe just upload the one compiled by the latest supported GHC? 

Any objection or suggestion? 

By the way, is the license issue solved?

**Pull request merged**
