### PR TITLE
Use exception for error reporting in Parser

### PR DESCRIPTION
**Pull request by vlopezj**
Do not merge just yet.

Re: https://github.com/agda/agda/issues/2224

### CODE REVIEW

**Comment by nad** [comment]
My idea was to use something like `Agda.TypeChecking.Monad.Base.genericError`. You can change the type signature of `parseFile'` to `(MonadTCM tcm, Show a) => Parser a -> AbsolutePath -> tcm a`.

**Comment by vlopezj** [comment]
@nad Importing `Agda.TypeChecking.Monad.Base` introduces a cyclic dependency:

```
Module imports form a cycle:
         module ‘Agda.TypeChecking.Monad.Base’ (src/full/Agda/TypeChecking/Monad/Base.hs)
        imports ‘Agda.Interaction.Exceptions’ (src/full/Agda/Interaction/Exceptions.hs)
  which imports ‘Agda.Syntax.Parser’ (src/full/Agda/Syntax/Parser.hs)
  which imports ‘Agda.TypeChecking.Monad.Base’ (src/full/Agda/TypeChecking/Monad/Base.hs)
```

I could presumably fix it by tinkering with the hs-boot files. But I don't like the idea of introducing a circular dependency between the type-checking and the parsing phases. 

On the other hand, introducing a new data type `ParseFileError` just for errors occurring a single module is too verbose. If there is an already-implemented general infrastructure for errors that does not introduce further cyclical dependencies between modules I could use that instead.

**Comment by nad** [comment]
It seems as if the `MonadIO` instance for `TCMT` catches `ParseError`s. Perhaps you could use that type (suitably modified?) to report errors.

**Comment by vlopezj** [comment]
@nad How about this? I extended `ParseError` with a few more constructors.

**Comment by vlopezj** [comment]
Merged into stable-2.5, master.
https://github.com/agda/agda/commit/355eb3536b34ce9638d6eaa231cd340b0ba975af

**Pull request closed without merging**
