### PR TITLE
Replace `__IMPOSSIBLE__` and remove `undefined.h`

### LINKED ISSUE #3718: Replace `__IMPOSSIBLE__` with throw + HasCallStack
It would be useful to replace the [`__IMPOSSIBLE__` preprocessor macro](https://github.com/agda/agda/blob/47eecb71752536effba9f26b337a66f7b2c722a9/src/full/undefined.h#L1) by decorating [`throwImpossible`](https://github.com/agda/agda/blob/47eecb71752536effba9f26b337a66f7b2c722a9/src/full/Agda/Utils/Impossible.hs#L47) with [`GHC.Stack.HasCallStack`](https://hackage.haskell.org/package/base-4.9.0.0/docs/GHC-Stack.html) (introduced in `base-4.9.0.0`) for locating the error.

By doing that, in conjunction with #1875, the C preprocessor can be dropped from (nearly) all the Haskell source files. This simplifies use of source analysis, refactoring, and formatting tools.

(Which was/is a speed-bump for #3512; refactoring tools don't tend to work well in the presence of a preprocessor).

For example, in `src/full/Agda/Utils/Impossible.hs`:
```diff
+import GHC.Stack (CallStack, HasCallStack, callStack, freezeCallStack, prettyCallStack)
 
 data Impossible
-  = Impossible  String Integer
+  = Impossible CallStack
```
```diff
-throwImpossible :: Impossible -> a
-throwImpossible = throw
+throwImpossible :: HasCallStack => a
+throwImpossible = throw (Impossible (freezeCallStack callStack))
```

And the other random files:
```diff
-#include "undefined.h"
 import Agda.Utils.Impossible
```
```diff
 -- …
-  when (null cs) __IMPOSSIBLE__
+  when (null cs) throwImpossible
```

### Caveat: Depends on #3719
This suggestion cannot be implemented before dropping support for `ghc@7.10`, which uses `base-4.8.*`. I have implemented this `HasCallstack` change locally already—not well-tested—but decided to shelve the work when I realized the GHC restriction. So this issue is to serve as a reference point for whether/how/when to continue that work.

### PR DESCRIPTION
**Pull request by rwe**
* Fixes #3718 (_Replace `__IMPOSSIBLE__` with `throw` + `HasCallStack`_)
* Based on/includes #3728 (_Remove support for GHC 7.10_). Please see that PR first to avoid duplicate comments.

For review clarity, I will rebase this branch once #3728 is merged so that it's easier to review the specific changes here. In the meantime, the relevant commit range to this PR can be viewed here:
  * https://github.com/erydo/agda/compare/ghc-7.10-removal...inconceivable

Some things that are *not* in this PR:
  * This does not completely from `LANGUAGE CPP` from all files, only many of them.
  * This does not improve the names of `__IMPOSSIBLE__`, etc.
  * This does not add additional call stack information to the error messages. The error messages remain identical. (At least, that is the intention).

Rather than replacing all instances of `__IMPOSSIBLE__` with a new identifier like `throwImpossible` or `impossible`, I chose instead to initially reimplement the functionality of those macros with identifiers of the same name.

The main motivation of that choice is to reduce code churn and likelihood of significant merge conflicts with other large PRs such as #3589, since those identifiers are used pretty much everywhere. However, I think it's worth considering renaming them in the future to something more Haskell-y.

There are additional details within the commit messages themselves.

### CODE REVIEW

**Comment by jespercockx** [comment]
Wow, this is great! Thanks for working on this, it will surely save a lot of time in the future!

**Comment by jespercockx** [comment]
@erydo does this mean we could also add more detailed call stacks to __IMPOSSIBLE__ error messages instead of just the file+line number we have now? Or does that require more work (like adding `HasCallStack` constraints)?

**Comment by rwe** [comment]
The recent force-push was a commit message rewrite due to the discussion here: https://github.com/agda/agda/pull/3726#issuecomment-487963875

The PR contents themselves are unchanged: https://github.com/erydo/agda/compare/12562c1..ae40f0b

**Comment by rwe** [comment]
@jespercockx A bit of both. Additional information available immediately is stuff like the function name, module name, and package name. Also column number and line/col spans. To have additional callstack information (like an actual stack), either additional `HasCallStack` constraints can be be added to various callers _or_ compilation with `-prof` as per usual.

**Comment by asr** [comment]
@erydo, let me know when Travis is green.

**Comment by rwe** [comment]
@asr — Travis ✅

**Pull request merged**
