### PR TITLE
[ new ] Make Abs and Arg in Builtin.Reflection universe polymorphic

### PR DESCRIPTION
**Pull request by L-TChen**

### CODE REVIEW

**Comment by jespercockx** [comment]
What is the motivation for this patch? As far as I know none of the reflection datatypes are level-polymorphic.

**Comment by L-TChen** [comment]
> What is the motivation for this patch? As far as I know none of the reflection datatypes are level-polymorphic.

It takes a bit to explain... 

It happens to be some cases that types of different universe need to be combined through applicative functor or monad. However, in most of definitions,  only types of the same level are allowed to chain together, e.g., in the standard library

```agda
 record RawIMonad {i f} {I : Set i} (M : IFun I f) :
                 Set (i ⊔ suc f) where
 ...
  field
    return : ∀ {i A} → A → M i i A
    _>>=_  : ∀ {i j k A B} → M i j A → (A → M j k B) → M i k B
```

When defining instances of `RawIMonad` for universe polymorphic functor, we actually have an instance for each universe level, so every operation's level is determined. To solve this inflexibility, we can define instead using `Setω` in the following way:

```agda
record IMonad (M : ∀ {ℓ} → I → I → Set ℓ → Set ℓ) : Setω where
...
  field
    return : A → M i i A
    _>>=_  : M i j A → (A → M j k B) → M i k B
```
Now instances of `_>>=_` retains universe polymorphism. However, the new definition only accepts universe polymorphic functors only, so `Arg` and `Abs` are ruled out. 

We can of course define another typeclass for those functors, but it also means there will be duplicated code and namespace pollution. On the other hand, I don't see any harm if we make `Arg` and `Abs` universe polymorphic since 

* It takes no extra effort to maintain. 
* Little effort to change it. 
* Consistent with other instances. 

If you know any other easy workaround, please let me know.

**Comment by jespercockx** [comment]
Thanks for the explanation, I've encountered this issue with universe-polymorphic monads myself before. I'm not opposed to making this change, more just curious for the reason.

**Comment by L-TChen** [comment]
Sorry for being lazy. 

By the way, `Setω` and `--omega-in-omega` are quite useful in practice...;-)

**Comment by L-TChen** [comment]
Oops, I overlooked this change. I will fix this soon. Don't merge it.

**Comment by L-TChen** [comment]
CI fails because it is tested against the standard library, but the `Reflection` module is not universe polymorphic there. Otherwise, I think I have updated the testing suite in Agda/Agda.

**Comment by nad** [comment]
If the standard library test fails, then you should fix the standard library and update the standard library submodule accordingly.

**Comment by jespercockx** [comment]
I guess the changes to the standard library also depend on this patch, so both of them have to be merged at the same time. I'm not sure what's the proper procedure for cases like this?

**Comment by gallais** [comment]
Given that `Arg` is a BUILTIN, I am a bit surprised you can simply change the type
annotation in the `prim/` file without having to modify the `.hs` that implements
this builtin.

**Comment by UlfNorell** [comment]
The BUILTIN will bind to `Arg` at `lzero` and the constructors didn't change, which is why the Haskell  code doesn't have to change.

**Comment by nad** [comment]
> I'm not sure what's the proper procedure for cases like this?

One possibility:

1. Modify Agda, but don't commit the changes.
2. Modify the standard library. Commit the changes.
3. Update the standard library submodule.
4. Make sure all test cases succeed.
5. Commit all changes in the same commit, to avoid breaking any test cases.

**Comment by asr** [comment]
Note that the standard library submodule is not updated frequently so before modify the standard library I suggest to update the submodule in a different PR.

**Comment by L-TChen** [comment]
Huh, maybe first to have a backward compatible change in stdlib is better. Instead of making functions in `Reflection` of the standard library  universe polymorphic, first we fix it to Set0, i.e.
```agda
  arg₁ : ∀ {A : Set} {i i′} {x x′ : A} → arg i x ≡ arg i′ x′ → i ≡ i′
  arg₁ refl = refl
```
So the current and the patched version can all accept it. Then we proceed with the PR if testing are passed on both sides. Where can I make a PR for the submodule?

**Comment by gallais** [comment]
Note that you could put a

```agda
private
  variable
    a : Level
    A : Set a
```

block at the top of `Reflection` and `arg₁ : ∀ {i i′} {x x′ : A} → arg i x ≡ arg i′ x′ → i ≡ i′`
should silently be upgraded to a level-polymorphic variant once `Arg` is.

**Comment by asr** [comment]
> Where can I make a PR for the submodule?

In the Agda repository.

**Comment by rwe** [comment]
Re git procedure, the following would be safe and does not require precise timing:
  * Push (or merge a PR of) the corresponding change to `agda/std-lib` to its _own branch_ on that repo, so that the repo has the commit ID. It does not need to be merged into `master` immediately.
  * In `agda/agda` PR (this one), update the `std-lib` submodule to point to that commit ID.

If this PR is approved, merge this one into `master`, and then merge the branch to `master` in `agda-stdlib`.

Git submodules refer to commit ID on a particular remote/repo, not branch names, so as long as the remote (`agda/agda-stdlib`) has the commit ID on it somewhere, it's fine.

**Comment by L-TChen** [comment]
> Note that you could put a
> ... 
> block at the top of `Reflection` and `arg₁ : ∀ {i i′} {x x′ : A} → arg i x ≡ arg i′ x′ → i ≡ i′`
> should silently be upgraded to a level-polymorphic variant once `Arg` is.

Thanks for the suggestion. I did this in the PR for agda-stdlib but for instance the shorthand `Args` needs an explicit argument. I split the PR now, so `Args` remains in Set_0 but those used to define decidable equality are updated. Both versions of Agda should pass the testing suite after merging the PR for standard library.

**Comment by L-TChen** [comment]
Following the solution of #3792, the maximum heap size is increased to 3GB  for all GHC versions in order to finish Compiler `with-stdlib` test against a newer stdlib without timeout. I didn't manage to update the stdlib and pass Compiler test without this tweak... 

So, is it still okay to merge this PR?

**Pull request merged**
