### PR TITLE
Literate mode revamp

### PR DESCRIPTION
**Pull request by vlopezj**
Typecheckable documentation. See CHANGELOG

P.S.: The branch name is misleading; this does not involve the `pandoc` library.

### CODE REVIEW

**Comment by asr** [comment]
@vlopezj please note that the Travis test failed (if you didn't receive an email notification from Travis, you need to sign in to Travis using your GitHub account).

**Comment by asr** [comment]
@vlopezj please also add the new `make user-manual-test` to Travis.

**Comment by vlopezj** [comment]
@asr Thanks! It should be working now. Please do not merge; I will rebase it myself once the build passes.

**Comment by asr** [comment]
@vlopezj This PR wasn't pushed into the stable-2.5 branch. Was it on purpose?

**Pull request merged**
