### PR TITLE
Fix #6807: Add UnfoldingDecl to Eq Declaration instance

### LINKED ISSUE #6807: Caching is broken in the presence of `opaque`
It seems as if the introduction of `opaque` has broken the caching mechanism. Consider the following code:
```agda
{-# OPTIONS -vtc.decl:5 #-}

opaque

  A : Set₁
  A = Set

B : Set₁
B = Set
```
If I load this code using the Emacs mode, then I get the following output in the `*Agda debug*` buffer:
```
Checking A.
Checked A.
Checking B.
Checked B.
```
If I then comment out the definition of `B` and reload the code, then I get the following output:
```
Checking A.
Checked A.
```
However, `A` should not be type-checked again.

### PR DESCRIPTION
**Pull request by plt-amy**
I have no idea how to write a test for this. @andreasabel @nad do you have any suggestions?

### CODE REVIEW

**Comment by andreasabel** [comment]
The problem is that GHC cannot help us here to check for missing cases, as spelling out all the cases would be quadratic.
It could be refactored to a form that matches exhaustively on the lhs and uses a view on the rhs.
```haskell
data D
  = A A1 A2
  | B 
  | C C1 C2

isA : D -> Maybe (A1, A2)
isA = \case
  A a1 a2 -> Just (a1, a2)
  _ -> Nothing

isB : D -> Maybe ()
isC : D -> Maybe (C1, C2)

instance Eq D where
  (== d) = \case 
    A a1 a2 -> caseMaybe (isA d) False \ (a1', a2') -> a1 == a1'
    B       -> caseMaybe (isB d) False \ () -> True
    C c1 c2 -> caseMaybe (isC d) False \ (c1', c2') -> (c1, c2) == (c1', c2')
```
This way, no catch-all is needed.

Even better, make record types for the data of each constructor:
```haskell
data D
  = A AData
  | B BData
  | C CData
-- maybe some pattern syonyms

data AData = AData A1 A2
data BData = BData
data CData = CData C1 C2

isA : D -> Maybe AData
isA = \case
  A a -> Just a
  _ -> Nothing

isB : D -> Maybe BData
isC : D -> Maybe CData

instance Eq D where
  (== d) = \case 
    A (AData a1 a2) -> caseMaybe (isA d) False \ (AData a1' a2') -> a1 == a2'
    B BData         -> caseMaybe (isB d) False \ (BData) -> True
    C (CData c1 c2) -> caseMaybe (isC d) False \ (CData c1' c2') -> (c1, c2) == (c1', c2')
```

**Comment by plt-amy** [comment]
```haskell
instance Eq D where
  (==) = \case 
    A a1 a2 -> \case { A a1' a2' -> (a1, a2) == (a1', a2') ; _ -> False }
    B       -> \case { B -> True; _ -> False }
    C c1 c2 -> \case { C c1' c2' -> (c1, c2) == (c1', c2') ; _ -> False }
```

Seems to work just as well and doesn't need the many helper functions --- though sometimes it's handy to have those helper functions, so I'd like to point out that `lens` has TH to generate them as `makePrisms`.

**Comment by andreasabel** [comment]
> I'd like to point out that `lens` has TH to generate them as `makePrisms`.

We moved away from TH (Easter 2020) so that we can have `make type-check`:
- https://github.com/agda/agda/issues/2038
- https://github.com/agda/agda/pull/4574

For me, having a type-checking only GHC pass is a major productivity boost: quick feedback on type errors.
Maybe nowadays HLS is an alternative (can't get it to work, though).

**Comment by andreasabel** [comment]
(Off-topic: @plt-amy Will you make it to the dev meeting tomorrow (Wed 13 Sep 3pm MEST)?  I sent the zoom link in an email yesterday.)

**Comment by plt-amy** [comment]
Yes, I'll be there

**Comment by nad** [comment]
> I have no idea how to write a test for this. @andreasabel @nad do you have any suggestions?

In `test/interaction`:
* Add an empty file `Issue6807.agda`.
* Add a file `Issue6807.hs` with the following contents:
  ```haskell
  {-# LANGUAGE RecordWildCards #-}

  import RunAgda

  file = "Issue6807.agda"

  secondCode = unlines
    [ "opaque"
    , ""
    , "  A : Set₁"
    , "  A = Set"
    ]
  firstCode = secondCode ++ unlines
    [ "B : Set₁"
    , "B = Set"
    ]

  main :: IO ()
  main = runAgda [ "--no-libraries"
                 , "--caching"
                 , "-vtc.decl:5"
                 ] $ \(AgdaCommands { .. }) -> do

    -- Discard the first prompt.
    echoUntilPrompt

    -- Create the file.
    writeUTF8File file firstCode

    -- Load the file, and wait for Agda to complete.
    loadAndEcho file

    -- Edit the file.
    writeUTF8File file secondCode

    -- Reload.
    loadAndEcho file

    -- Clean up.
    writeUTF8File file ""

    return ()
  ```
* Run `make Issue6807.cmp`, and add `Issue6807.out`.

**Pull request merged**
