### PR TITLE
[fix #4072] fix-agda-whitespace supports custom configuration

### LINKED ISSUE #4072: Moving fix-agda-whitespace away
This is another issue concerning the development of Agda. 

I propose to move the package `fix-agda-whitespace` to a new repository and upload it to hackage for the following reasons: 

1. `fix-agda-whitespace` can be installed without downloading Agda source code. Good for contributors to the standard library. 

2.  A precompiled binary can be released via GitHub. Good for testing---there is no need to compile it every time. 

I cannot think of any disadvantage...

### PR DESCRIPTION
**Pull request by L-TChen**
As suggested in #4072, this PR adds the custom configuration support to `fix-agda-whitespace`.

In detail, the program now takes a configuration file called `fix-agda-whitespace.yaml` in the working directory to determine what files to check (see the comment inside), so there is no need to recompile  `fix-agda-whitespace` in order to exclude or include files/directories.

A precompiled binary is uploaded to https://github.com/agda/fix-whitespace/releases by/for Travis. 

If this PR is approved, then I will upload this to Hackage and Stackage and remove `fix-agda-whitespace` from the Agda's codebase. In return, contributors to the standard library, for example, only need to install this program via `stack`/`cabal` without downloading Agda’s source code. 

[ I was bored enough to make this when having a cold ... ]

### CODE REVIEW

**Comment by L-TChen** [comment]
By the way, the compilation takes much longer since it depends on the package `yaml`. This is not a problem for Travis as the precompiled binary will be used directly. 

Maintenance should not be a problem either, since `yaml` is actively maintained and has been used by `stack`.

**Comment by gallais** [comment]
Should this be renamed to `fix-whitespace` now that it is independent from Agda?

**Comment by L-TChen** [comment]
> Should this be renamed to `fix-whitespace` now that it is independent from Agda?

Hmm, Is there any other use case independent from Agda?

**Comment by gallais** [comment]
I miss this configurable executable in pretty much all of my Haskell and Agda
projects. :D

**Comment by jespercockx** [comment]
I'm using `fix-agda-whitespace` pretty much all the time for writing LaTeX code. It only gets annoying when collaborating with other people since I automatically fix THEIR whitespace as well.

**Comment by nad** [comment]
I've configured Emacs to take care of trailing whitespace for me. However, I thought it was annoying when other people checked in code with trailing whitespace, because if I later edited those files there could be lots of semantically irrelevant changes in them. "Fortunately" there was some problem related to trailing whitespace (#352) which I could fix by implementing `fix-agda-whitespace` and incorporating it into the test suite.

@jespercockx, note that trailing whitespace is (sometimes) semantically significant in LaTeX.

**Comment by L-TChen** [comment]
Right, I see. @nad would you like to approve it and suggest a license for it?

**Comment by L-TChen** [comment]
Right, thanks for the above comments. @nad, would you like to approve the change and suggest a license for it?

**Comment by WolframKahl** [comment]
> Hmm, Is there any other use case independent from Agda? 

Everywhere.

Even in workflows striving to avoid attacks on cryptographic hashes by padding with “invisible and irrelevant” whitespace.

**Comment by L-TChen** [comment]
Removing trailing whitespace itself is another subject as it is usually managed by editors. The reason that I felt less easy to rename it is that it does not follow the convention of Unix command, and it needs a good reason for not following the convention.

If it was a Unix command  like `rm`,  it would take filenames and options like `-R`. To deal with a large set of files, one would use `find` to make it. That is certainly not very convenient if the command needs to be executed repeatedly and maintained. 

But, now, I feel that the current design is general enough for other purposes rather than for some weird whitespace issue on Windows.

**Comment by nad** [comment]
> @nad, would you like to approve the change and suggest a license for it?

The code already has a licence.

**Comment by L-TChen** [comment]
I assume that as fix-whitespace is part of the Agda's test suite, so it has the license https://github.com/agda/agda/blob/master/LICENSE. Shall I just change the set of contributors and authors to make it independent from Agda 2?

**Pull request closed without merging**
