### PR TITLE
Only consider arguments mentioned in the result, for #6298

### PR DESCRIPTION
**Pull request by plt-amy**
@nad This should fix the issue you spotted with my original fix in #6299. Your new test case passes, at least.

@asr I pointed this PR at the `release-2.6.3` branch since it has to make it there; is this right? Or should I merge towards master then cherry-pick it manually?

### CODE REVIEW

**Comment by plt-amy** [comment]
@Mergifyio rebase

**Comment by asr** [comment]
> I pointed this PR at the `release-2.6.3` branch since it has to make it there; is this right?

No.

> Or should I merge towards master then cherry-pick it manually?

Yes, please.

**Comment by plt-amy** [comment]
Will do, thanks! Let's just see if I can salvage this PR or if I'll need another branch to deal with Git...

**Comment by plt-amy** [comment]
I'll cherry-pick my commit onto a new branch since it'll be easier.

**Pull request closed without merging**
