### PR TITLE
Fix cropping generalized variables in helper functions (#6844)

### LINKED ISSUE #6844: Agda 2.6.4: Generated helper function lacks a visible argument
The fix of #6677 maybe went to far, as "generate helper" (`C-c C-h`) also drops an argument now that was explicitly requested to be a visible argument of the helper function.
This bug was caught in the wild by this development using the standard library:
```agda
open import Level using (Level; _⊔_; 0ℓ) renaming (suc to lsuc)

open import Data.Unit using (⊤)
open import Data.Product.Base using (∃; _,_; proj₁; proj₂)
import Relation.Binary.PropositionalEquality as ≡
open ≡ using (_≡_; refl)
open import Data.Empty    using (⊥)
open import Data.Sum.Base using (_⊎_; inj₁; inj₂; [_,_])
open import Function.Base using (_∘_)
open import Axiom.Extensionality.Propositional

1ℓ = lsuc 0ℓ

variable
  ℓ ℓ′ : Level
  A : Set ℓ

postulate
  Base : Set

mutual
  record Cxt : Set₁ where
    inductive; pattern; constructor co; no-eta-equality
    field Ind : Set
          at  : Ind → Ty

  record Ty : Set₁ where
    inductive; constructor _⇒_; eta-equality
    field dom : Cxt
          rng : Base

open Cxt
open Ty

_⊛_ : (Γ Δ : Cxt) → Cxt
Γ ⊛ Δ = record
  { Ind = Γ .Ind ⊎ Δ .Ind
  ; at  = [ Γ .at , Δ .at ]
  }

_⇛_ : Cxt → Ty → Ty
Γ ⇛ (Δ ⇒ b) = (Γ ⊛ Δ) ⇒ b

data Var (Γ : Cxt) : (τ : Ty) → Set₁ where
  var : (i : Γ .Ind) → Var Γ (Γ .at i)

mutual
  record Ne (Γ : Cxt) (b : Base) : Set₁ where
    inductive; pattern; constructor ne
    field Ar   : Cxt
          call : Var Γ (Ar ⇒ b)
          args : Subst Γ Ar

  record Nf (Γ : Cxt) (τ : Ty) : Set₁ where
    inductive; pattern; constructor abs
    field body : Ne (Γ ⊛ τ .dom) (τ .rng)

  record Subst (Γ Δ : Cxt) : Set₁ where
    inductive
    field at : (i : Δ .Ind) → Nf Γ (Δ .at i)
open Subst

pattern tm Ar x σ = abs (ne Ar x σ)

variable
  b : Base
  τ : Ty
  Γ Δ Φ Ψ Σ Ξ : Cxt
  x : Var Γ τ
  t : Nf Γ τ
  σ : Subst Δ Γ

record Ren (Γ Δ : Cxt) : Set₁ where
  field at : (i : Δ .Ind) → Var Γ (Δ .at i)
open Ren

variable
  ρ : Ren Δ Γ

ρₗ : ∀ Γ Δ → Ren (Γ ⊛ Δ) Γ
ρₗ _ _ .at i = var (inj₁ i)

ρᵣ : ∀ Γ Δ → Ren (Γ ⊛ Δ) Δ
ρᵣ _ _ .at i = var (inj₂ i)

renₓ : Var Δ τ → Ren Γ Δ → Var Γ τ
renₓ (var i) ρ = ρ .at i

liftᵣ : ∀ Φ → Ren Γ Δ → Ren (Γ ⊛ Φ) (Δ ⊛ Φ)
liftᵣ {Γ} Φ ρ .at (inj₁ i) = renₓ (ρ .at i) (ρₗ Γ Φ)
liftᵣ {Γ} Φ ρ .at (inj₂ j) = ρᵣ Γ Φ .at j

mutual
  renₙ : Ne Δ b → Ren Γ Δ → Ne Γ b
  renₙ (ne Φ (var i) σ) ρ = ne Φ (ρ .at i) (renₛ {Φ = Φ} σ ρ)

  ren : Nf Δ τ → Ren Γ Δ → Nf Γ τ
  ren {τ = Φ ⇒ b} (abs t) ρ = abs (renₙ t (liftᵣ Φ ρ))

  renₛ : Subst Δ Φ → Ren Γ Δ → Subst Γ Φ
  renₛ σ ρ .at i = ren (σ .at i) ρ

postulate
  funExt : Extensionality ℓ ℓ′

module SetModel {ℓ} (⟦_⟧b : Base → Set ℓ) where

  mutual
    ⟦_⟧ : Ty → Set ℓ
    ⟦ Γ ⇒ b ⟧ = ⟦ Γ ⟧c → ⟦ b ⟧b

    ⟦_⟧c : Cxt → Set ℓ
    ⟦ co I τ ⟧c = (i : I) → ⟦ τ i ⟧

  -- Standard model of terms

  Den  = λ Γ τ → ⟦ Γ ⟧c → ⟦ τ ⟧
  Denb = λ Γ b → ⟦ Γ ⟧c → ⟦ b ⟧b
  Denₛ = λ Γ Δ → ⟦ Γ ⟧c → ⟦ Δ ⟧c

  ⦅_⦆ₓ : Var Γ τ → Den Γ τ
  ⦅_⦆ₓ {Γ = co _ _} (var i) γ = (γ i)

  ⦅_⦆ᵣ : Ren Γ Δ → Denₛ Γ Δ
  ⦅_⦆ᵣ {Δ = co _ _} ρ γ i = ⦅ ρ .at i ⦆ₓ γ

  mutual
    ⦅_⦆ₙ : Ne Γ b → ⟦ Γ ⇒ b ⟧
    ⦅ ne Δ x sp ⦆ₙ γ = ⦅ x ⦆ₓ γ (⦅ sp ⦆ₛ γ)

    ⦅_⦆ : Nf Γ τ → Den Γ τ
    ⦅_⦆ {Γ = co _ _} {τ = co _ _ ⇒ b} (abs t) γ δ = ⦅ t ⦆ₙ [ γ , δ ]

    ⦅_⦆ₛ : Subst Γ Δ → Denₛ Γ Δ
    ⦅_⦆ₛ {Δ = co _ _} σ γ i = ⦅ σ .at i ⦆ γ

  mutual
    ⊨renₙ : ∀ (t : Ne Δ b) (ρ : Ren Γ Δ) → ⦅ renₙ t ρ ⦆ₙ ≡  ⦅ t ⦆ₙ ∘ ⦅ ρ ⦆ᵣ
    ⊨renₙ {Δ = co ΔI Δat} {Γ = Γ} (ne Φ (var i) sp) ρ = funExt λ γ →
      ≡.cong (⦅ ρ .at i ⦆ₓ γ) {!⊨renₛ sp ρ γ!}

-- C-c C-h gives
--
-- ⊨renₛ : (ρ : Ren Γ (co ΔI Δat)) (γ : ⟦ Γ ⟧c) →
--         ⦅ renₛ sp ρ ⦆ₛ γ ≡ ⦅ sp ⦆ₛ (λ i → ⦅ ρ .at i ⦆ₓ γ)
--
-- Expected: also abstracts over sp.
```

### PR DESCRIPTION
**Pull request by knisht**
I faintly recall a wiseman [saying](https://github.com/agda/agda/pull/6689#issue-1751298991) that endowing existing entities with unwelcome semantics might not be a good idea. Sadly, his words have never been heard, and now we are reaping the consequences of our ignorance.

On a more serious note, `defArgGeneralizable` is not invariant under the changes of context, which makes it unusable for my purposes. I understand that the field that seemingly carries generalization info is `defGeneralizedParams`, but:
1. This field works originally only for data and records
2. This field is also sensitive to the context
3. Since I need only the number of generalized parameters, it seems unreasonable to waste resources on serialization of whole set of generalized names, especially when these names can be restored from type signature and my newly introduced field.

### CODE REVIEW

**Review by andreasabel — COMMENTED** [review]
Thanks!

I tested this with the OP of #6844 and now it works better: it generates a type signature that can be used in a `where` local to the clause where I asked for it.
We somehow [do not specify](https://agda.readthedocs.io/en/v2.6.3.20230914/language/with-abstraction.html#helper-functions) in which scope the generated function should be used, but the user can control this by adding more or less arguments to the call to the helper function when invoking generalization.  
Or so I thought.  However, if I ask to generate a function fitting the call `⊨renₛ ΔI Δat sp ρ γ` it ignores the first two arguments `ΔI Δat` that come from a pattern match.  Maybe the dropper needs to be more careful making sure nothing gets dropped that the user supplied explicitly.

**Comment by knisht** [comment]
And what would you expect from the helper function if only `ΔI` is provided, without `Δat`? Somehow realize that the user wants to create the function for a parent scope and abstract all other constructor bindings as well?

**Comment by knisht** [comment]
In Arend we delegated this problem to the user via UI, I am not sure how a similar solution should look like in emacs style 
https://github.com/JetBrains/intellij-arend/pull/322

**Comment by knisht** [comment]
Obsolete, a better solution exists in https://github.com/agda/agda/pull/6887

**Pull request closed without merging**
