### PR TITLE
Enable safe GHC LANGUAGE options in cabal's default-extensions field (#1942)

### PR DESCRIPTION
**Pull request by Blaisorblade**
First attempt at fixing #1942. Sending a PR to observe testing results and for discussions.

Possible improvements (revised):
- [x] Is it OK to switch to Haskell2010? (Yes)
- [x] If yes, drop options enabled by Haskell2010: https://wiki.haskell.org/Haskell_2010
- [x] Try adding more options and fixing the compile errors produced? (Not for now).
- [x] Try dropping `NondecreasingIndentation` and fixing the produced errors?
- [x] Stop enabling the picked extensions locally.

### CODE REVIEW

**Comment by asr** [comment]
> Try dropping `NondecreasingIndentation` and fixing the produced errors?

I know @andreasabel disagrees (see https://github.com/agda/agda/issues/1509#issuecomment-129031230).

**Comment by Blaisorblade** [comment]
Ah thanks. Let's keep the plan. But _actually_, I should of course just use `NondecreasingIndentation` locally in files that need it, since @andreasabel did not propose enabling it globally.
EDIT: done in 5b7723d8cdb1332f503e825dbc71625261f23761 (I hope the force push was OK, but every repo has their ideas on this).

**Comment by Blaisorblade** [comment]
So, should `NondecreasingIndentation` be on by default? And what about `RelaxedPolyRec`, the other extension where `Haskell2010` disagrees with `Haskell98`.

### `NondecreasingIndentation`

Of course, to keep coding policies completely unchanged, I could replace `default-language: Haskell2010` with `default-language: Haskell98` (which enables `NondecreasingIndentation` by default), and reconsider readding extensions that were enabled by `Haskell98`.

But I have no opinion, and can't figure out if there's existing consensus on the default; https://github.com/agda/agda/issues/1942#issue-150007506 suggests not adding it, but it was on by default; and right now I needed add it on exactly 5 files.

### `RelaxedPolyRec`

The other "controversial" extension from Haskell2010 is `RelaxedPolyRec`. That appears seriously harmless (can make some types more polymorphic when arguably they should), is only used directly twice, but is implied by `ScopedTypeVariables`. So I'd go for it.

**Comment by UlfNorell** [comment]
`RelaxedPolyRec` seems like a no-brainer. I have no strong opinions about `NondecreasingIndentation`, but since it was actually enabled by `Haskell98` the least invasive thing would be to add it to the default extensions when switching to `Haskell2010`.

**Comment by Blaisorblade** [comment]
Good. I'll wait a bit for any other feedback (at _least_ today) and revise this accordingly.

**Comment by andreasabel** [comment]
It is sufficient to have `NondecreasingIndentation` and other esoteric ones on a per-file basis (= locally = not in the .cabal file).  Some extensions are only used by 3 files or so, they could remain local if they cause trouble in general. 
One a rough look, the list you prepared looks very reasonable.

**Comment by Blaisorblade** [comment]
I looked at the build failure — `hTags` isn't aware of the `default-extensions`, meaning one can't actually omit local extensions and get a working build. See #2030 for a possible fix.

**Comment by Blaisorblade** [comment]
OK, now that #2030 is in, I've rebased this to trigger retesting, hoping it will be successful now.

**Pull request merged**
