### PR TITLE
refactoring: make easier to use the Agda library for generating HTML

### PR DESCRIPTION
**Pull request by divipp**
refactoring: make easier to use the Agda library for generating HTML from Agda source code

With this refactoring, the PandocAgda wrapper shrinks to just 129 SLOC:
https://github.com/divipp/PandocAgda/blob/master/PandocAgda.hs

PandocAgda is used for example in the Agda Tutorial (which is actively used at Eötvös Loránd University, Budapest):
http://people.inf.elte.hu/divip/AgdaTutorial/Index.html

### CODE REVIEW

**Comment by divipp** [comment]
`make test` runs OK on my computer (with the exception of epic-test, because I didn't install epic)

**Comment by divipp** [comment]
(This Travis build system is great!)

**Comment by andreasabel** [comment]
Is there a reason why this is on master by not on maint?  I prefer refactorings on the maintenance branch, otherwise the two branches diverge too much.

**Comment by divipp** [comment]
Ok, I prepare a patch for the maintenance branch.

**Comment by divipp** [comment]
Next try: https://github.com/agda/agda/pull/30

**Comment by divipp** [comment]
Next try: https://github.com/agda/agda/pull/32

**Pull request closed without merging**
