### PR TITLE
make easier to use the Agda library for generating HTML

### PR DESCRIPTION
**Pull request by divipp**
refactoring: make easier to use the Agda library for generating HTML from Agda source code (motivated by the PandocAgda executable application)

### CODE REVIEW

**Comment by divipp** [comment]
Building on GHC 7.4.2 failed with "src/full/Agda/TypeChecking/Monad/MetaVars.hs:338:45: Not in scope: `Map.traverseWithKey'", I think this is not related to the patch.

**Comment by asr** [comment]
> I think this is not related to the patch.

Right. This is the related to https://travis-ci.org/agda/agda/builds/51230598.

**Comment by gallais** [comment]
If you rebase against 638e3ad258a1cf9622c6062f7db8510bce020dad, the build will not fail because of Map.traverseWithKey being out of scope and we'll see whether everything is A-OK or not.

**Comment by divipp** [comment]
Followed the description in 'HACKING' I run 'git rebase maint-2.4.2' but nothing changed - maybe because 638e3ad is in the master branch?
'git rebase 638e3ad' does not work.
I am not sure what to do.

**Comment by divipp** [comment]
More info.
Steps I've done:
- forked the agda repository
- `git checkout maint-2.4.2`
- `git checkout -b issue1418`
- worked on the issue
- `git push -u https://github.com/divipp/agda.git issue1418`
- made a pull request

Today I've done these steps:

- synced my fork with upstream (followed the steps at https://help.github.com/articles/syncing-a-fork/)
- `git rebase maint-2.4.2`
- `git push`

I have also tried to do this:

- `git rebase 638e3ad`

This failed with:

    ...
    CONFLICT (content): Merge conflict in src/full/Agda/TypeChecking/Rewriting.hs
    Failed to merge in the changes.
    ...

So I did

- `git rebase --abort`

**Comment by divipp** [comment]
Maybe it is easier to merge https://github.com/agda/agda/pull/30 ?

**Comment by divipp** [comment]
Another info.
`git status` gives at my computer

    On branch issue1418
    nothing to commit, working directory clean

but somehow this pull request contains merge conflicts which I don't understand and don't know how to resolve.

**Comment by divipp** [comment]
I have found one source of problems:
The pull request was made against `agda:master`.
Finally I figured out how to made a pull request aginst `agda:main-2.4.2`: https://github.com/agda/agda/pull/31

**Pull request closed without merging**
