### PR TITLE
[ #5000 ] Bring back SizeUniv

### PR DESCRIPTION
**Pull request by andreasabel**
After Jesper's overhaul of the sort system, it is rather straightforward to reactivate SizeUniv (with hopefully more stable behavior as when we still relied on a linear universe hierarchy).

Note: This patch requires changes to the `Codata.Thunk` module of the standard library.

### CODE REVIEW

**Comment by jespercockx** [comment]
A worthy one for number 5000. You'll get a prize next time we meet in person!

**Comment by Saizan** [comment]
@andreasabel would you disable functions into `Size` after merging this?

**Comment by andreasabel** [comment]
@jespercockx wrote:
> A worthy one for number 5000. You'll get a prize next time we meet in person!

As it turned out, I stole the price from the much more substantial PR #5001.  ;-)

@Saizan wrote:
> @andreasabel would you disable functions into `Size` after merging this?

Good question; do you second this or have objections against this?

**Comment by andreasabel** [comment]
I create a merge commit for the sake of leaving the commit hashes intact (they are referenced from agda/agda-stdlib).

**Comment by Saizan** [comment]
@andreasabel right now I'm neutral about it. I guess it would break Veltri's and others encoding of GR into Agda's sized types, though.

**Comment by nad** [comment]
Some code broke for me due to this change:
* Some library functions that work for `Set a` do not work for the new size universe. This can be fixed by duplicating code or inlining definitions.
* I guess that extensionality for functions from the size universe does not follow from regular extensionality. For code of the form `Extensionality → …` this can be fixed by adding a new assumption.

**Pull request merged**
