### PR TITLE
[ closed #5935 ] Updated GitHub workflows.

### LINKED ISSUE #5935: On workflow for GitHub workflows
I'm planning to fix [this](https://github.com/agda/agda/runs/6676023533) problem. Without changing the files in `src/github/workflows`, I followed the instructions in https://github.com/agda/agda/blob/46031e1435d323ef79de916bf7d985f7aa63729e/src/github/workflows/README.md#L6-L7

by running

```bash
$ cd .github/workflows
$ make
$ git status
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   deploy.yml
	modified:   stack.yml
	modified:   test.yml
```
Why there where changes in the above files? Shouldn't be the files on `.github/workflows` synchronized with the files on `src/github/workflows`?

### PR DESCRIPTION
**Pull request by asr**
CI testing...

### CODE REVIEW

**Comment by asr** [comment]
Argh!, the first problem is https://github.com/agda/agda/runs/6690369194.

**Comment by andreasabel** [comment]
> Argh!, the first problem is [agda/agda/runs/6690369194](https://github.com/agda/agda/runs/6690369194).

https://github.com/agda/agda/runs/6690369194#step:6:14
```
Running Sphinx v5.0.0
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
```
Maybe because Sphinx was updated upstream? (To 5.0.0)
The last successful run (https://github.com/agda/agda/runs/6637647524?check_suite_focus=true#step:6:13) was with Sphinx 4.5:
```
Running Sphinx v4.5.0
```

**Comment by asr** [comment]
> Maybe because Sphinx was updated upstream? (To 5.0.0)

I don't know. I shall install the new version of Sphinx for testing...

**Comment by asr** [comment]
> Maybe because Sphinx was updated upstream? (To 5.0.0)

Yep. I got the same warning with Sphinx 5.0.0.

**Review by andreasabel — COMMENTED** [review]
Thanks!

**Pull request merged**
