### PR TITLE
[ cubical ] Make phi argument implicit in primitive comp

### PR DESCRIPTION
**Pull request by mortberg**
This makes the builtin comp operation more pleasant to use.

### CODE REVIEW

**Review by Saizan — APPROVED** [review]
Looks good. I'm surprised there weren't more internal calls to comp.

In some places Agda is still using the explicit hcomp/transp combo and we could switch over.

**Comment by mortberg** [comment]
> Looks good. I'm surprised there weren't more internal calls to comp.
> 
> In some places Agda is still using the explicit hcomp/transp combo and we could switch over.

I agree that it would be good to change this, but probably not in this PR. 

If no one objects I would suggest merging this now.

**Comment by Saizan** [comment]
@mortberg yeah, you should merge, will you also update agda/cubical at the same time?

**Comment by mortberg** [comment]
> @mortberg yeah, you should merge, will you also update agda/cubical at the same time?

Yes, I'll do it today

**Comment by nad** [comment]
Please document this change in the changelog.

**Pull request merged**
