### PR TITLE
Separate --without-K and --cubical-compatible

### PR DESCRIPTION
**Pull request by plt-amy**
Re. #6049; Coordinating distributed work is so easy! :stuck_out_tongue:

### CODE REVIEW

**Comment by jespercockx** [comment]
@plt-amy Is there anything I can do to help getting this to a mergeable state? If possible I'd like to integrate this into master soon for the release of 2.6.3.

**Comment by plt-amy** [comment]
@jespercockx Can you try pushing a commit to this branch? Maybe that'll convince CI into running (I got banned _again_)

**Comment by plt-amy** [comment]
A story in three acts (: ("twelve seconds ago" was Oct. 10!)

**Comment by andreasabel** [comment]
@Mergifyio rebase

**Comment by andreasabel** [comment]
Nnnaaaarrrrrgggghhhh!  CI doesn't run despite our rebasing efforts.  Sigh.
I'll steal your PR, again...

**Comment by andreasabel** [comment]
Please continue on
- #6207

**Pull request closed without merging**
